/* Playtest rules and saves are separate from Classic. */
(function(){'use strict';const P=window.VoyagePorts,W=window.VoyageWorld,N=window.VoyageNavigation,M=window.NeonMarket;
const time=n=>String(Math.floor(n/60)%24).padStart(2,'0')+':'+String(Math.floor(n)%60).padStart(2,'0');
function create(seed){const truth=M.pickTruth(P.economy,seed);return {version:1,seed,truth,ship:{x:1320,y:395,angle:Math.PI/2,speed:0},docked:'bar',clock:1420,credits:360,fuel:6,gold:[{grams:2,cost:91,karat:24}],trades:[],quotes:{},flags:{},chats:{},cargo:{},visits:{bar:1},track:null,passages:{},voyage:null,finds:{},rumours:{},log:['Your first voyage begins at Mei’s quay.'],ended:false};}
function valid(s){return (s&& (s.rumours===undefined||(s.rumours&&typeof s.rumours==='object'&&!Array.isArray(s.rumours)&&Object.entries(s.rumours).every(([id,at])=>P.signals.some(r=>r.id===id)&&Number.isFinite(at)&&at>=1420&&at<=s.clock))))&&!!s&&s.version===1&&typeof s.seed==='string'&&['order','vault','both'].includes(s.truth)&&s.ship&&[s.ship.x,s.ship.y,s.ship.angle,s.ship.speed,s.clock,s.credits,s.fuel].every(Number.isFinite)&&N.water(s.ship.x,s.ship.y)&&s.credits>=0&&s.fuel>=0&&s.fuel<=6&&s.clock>=1420&&s.clock<=1800&&(s.docked===null||W.ports.some(p=>p.id===s.docked))&&(!s.docked||Math.hypot(s.ship.x-W.ports.find(p=>p.id===s.docked).x,s.ship.y-W.ports.find(p=>p.id===s.docked).y)<70)&&Array.isArray(s.gold)&&s.gold.every(l=>l&&Number.isFinite(l.grams)&&l.grams>=0&&Number.isFinite(l.cost)&&l.cost>=0)&&Array.isArray(s.trades)&&s.trades.every(t=>t&&['buy','sell'].includes(t.kind)&&W.ports.some(p=>p.id===t.where)&&[t.at,t.grams,t.total,t.price].every(Number.isFinite))&&s.flags&&!Array.isArray(s.flags)&&typeof s.flags==='object'&&Object.values(s.flags).every(v=>typeof v==='boolean')&&s.chats&&!Array.isArray(s.chats)&&typeof s.chats==='object'&&Object.entries(s.chats).every(([id,n])=>P.characters[id]&&Number.isInteger(n)&&n>=0)&&s.quotes&&!Array.isArray(s.quotes)&&typeof s.quotes==='object'&&Object.entries(s.quotes).every(([id,q])=>W.ports.some(p=>p.id===id)&&q&&[q.buy,q.sell,q.at].every(Number.isFinite))&&Array.isArray(s.log)&&s.log.every(x=>typeof x==='string')&&typeof s.ended==='boolean'&&(s.cargo===undefined||validCargo(s.cargo))&&(s.visits===undefined||(!Array.isArray(s.visits)&&s.visits&&Object.entries(s.visits).every(([id,n])=>W.ports.some(p=>p.id===id)&&Number.isInteger(n)&&n>=0)))&&(s.track===undefined||s.track===null||typeof s.track==='string')&&held(s)<=capacity(s)&&(s.passages===undefined||(s.passages&&typeof s.passages==='object'&&!Array.isArray(s.passages)&&Object.entries(s.passages).every(([id,n])=>W.ports.some(p=>p.id===id)&&Number.isInteger(n)&&n>=0)))&&(s.voyage===undefined||s.voyage===null||(s.voyage&&Number.isFinite(s.voyage.distance)&&s.voyage.distance>=0&&W.ports.some(p=>p.id===s.voyage.from)&&s.voyage.line&&typeof s.voyage.line.text==='string'&&typeof s.voyage.line.speaker==='string'&&(s.voyage.to===undefined||s.voyage.to===null||W.ports.some(p=>p.id===s.voyage.to))))&&(s.finds===undefined||(s.finds&&!Array.isArray(s.finds)&&Object.entries(s.finds).every(([id,result])=>P.discoveryText[id]&&P.discoveryText[id].choices.some(c=>c.id===result))));}
function validCargo(cargo){return cargo&&!Array.isArray(cargo)&&typeof cargo==='object'&&Object.entries(cargo).every(([id,c])=>P.freight[id]&&c&&c.cost===P.freight[id].cost&&[0,1].includes(c.units)&&(c.revenue===(c.units?0:P.freight[id].payment)||(!c.units&&c.revenue===0&&c.released===true)));}
function hydrate(s){if(s.cargo===undefined)s.cargo={};if(s.visits===undefined)s.visits={bar:1};if(s.track===undefined)s.track=null;if(s.passages===undefined)s.passages={};if(s.voyage===undefined)s.voyage=null;if(s.finds===undefined)s.finds={};if(s.rumours===undefined)s.rumours={};return s;}
function held(s){return Object.values(s.cargo||{}).reduce((n,c)=>n+c.units,0)+(s.flags.teaAccepted&&!s.flags.teaDelivered?1:0)+(s.flags.lampAccepted&&!s.flags.lampDelivered?1:0);}
function capacity(s){return s.flags.hold?3:2;}
function freight(s,id,deliver){hydrate(s);const d=P.freight[id];if(!d||s.ended||s.docked!==(deliver?d.to:d.from))return false;
 if(deliver){const c=s.cargo[id];if(!c||!c.units||s.clock>d.deadline)return false;c.units=0;c.revenue=d.payment;if(id==='lenses')s.flags.observatorySupplied=true;s.credits+=d.payment;advance(s,5);log(s,d.title+' delivered: '+d.payment+' cr; '+d.cost+' cr purchase.');}
 else{if(s.clock<(d.opens||1420)||s.cargo[id]||held(s)>=capacity(s)||s.credits<d.cost||s.clock+5>d.deadline)return false;s.credits-=d.cost;s.cargo[id]={cost:d.cost,revenue:0,units:1};advance(s,5);log(s,'Bought '+d.title+' for '+d.cost+' cr.');}observe(s);return true;}
function release(s,id){const c=s.cargo&&s.cargo[id],d=P.freight[id];if(s.ended||!s.docked||!c||!c.units||s.clock<=d.deadline)return false;c.units=0;c.released=true;log(s,d.title+' unloaded after its delivery window; no refund or payment.');return true;}
function waitFreight(s,id){const d=P.freight[id];if(s.ended||!d||s.docked!==d.from||!d.opens||s.clock>=d.opens)return false;advance(s,d.opens-s.clock);observe(s);log(s,'Waited for '+d.title+' to clear the desk.');return true;}
function estimate(s,d){const start=W.ports.find(p=>p.id===d.from),end=W.ports.find(p=>p.id===d.to),route=N.route(start,end);let distance=0,prev=start;for(const point of route){distance+=Math.hypot(point.x-prev.x,point.y-prev.y);prev=point;}return {fuel:distance/620*(s.flags.engine?.8:1),minutes:Math.ceil(distance/(86*(s.flags.engine?1.15:1))*2),distance};}
function weather(s){return W.weather(s);}
function routeStats(s,start,end){const route=N.route(start,end);let distance=0,prior=start;for(const point of route){distance+=Math.hypot(point.x-prior.x,point.y-prior.y);prior=point;}return {fuel:distance/620*(s.flags.engine?.8:1),minutes:Math.ceil(distance/(86*(s.flags.engine?1.15:1))*2),distance};}
function plan(s,id){const d=P.freight[id];if(!d)return null;const held=!!(s.cargo&&s.cargo[id]&&s.cargo[id].units),from=W.ports.find(p=>p.id===d.from),to=W.ports.find(p=>p.id===d.to),home=W.ports.find(p=>p.id==='bar');
 const collection=held?{fuel:0,minutes:0}:routeStats(s,s.ship,from),delivery=routeStats(s,held?s.ship:from,to),back=routeStats(s,to,home),arrive=s.clock+collection.minutes,wait=held?0:Math.max(0,(d.opens||1420)-arrive),handoverAt=arrive+wait+(held?0:5)+delivery.minutes;
 return {id,held,cost:d.cost,payment:d.payment,fuel:collection.fuel+delivery.fuel,returnFuel:back.fuel,minutes:collection.minutes+delivery.minutes+wait+(held?0:5),handoverAt,deadline:d.deadline,onTime:handoverAt<=d.deadline,remaining:d.deadline-s.clock,wait};}
function collected(s){const rows=Object.entries(s.cargo||{}).filter(([id,c])=>c.units).map(([id,c])=>({id:'cargo-'+id,title:P.freight[id].title,to:P.freight[id].to,cost:c.cost,payment:P.freight[id].payment,deadline:P.freight[id].deadline}));
 if(s.flags.teaAccepted&&!s.flags.teaDelivered)rows.push({id:'tea',title:P.tea.title,to:'market',cost:0,payment:P.tea.fee,deadline:P.tea.deadline});if(s.flags.lampAccepted&&!s.flags.lampDelivered)rows.push({id:'lamp',title:'Aki’s lighthouse kit',to:'island',cost:0,payment:P.lamp.payment,deadline:P.lamp.deadline});return rows.sort((a,b)=>a.deadline-b.deadline);}
function nearDiscovery(s){if(s.docked||s.ended)return null;return W.discoveries.find(d=>!(s.finds||{})[d.id]&&Math.hypot(W.discoveryPosition(s,d).x-s.ship.x,W.discoveryPosition(s,d).y-s.ship.y)<65)||null;}
function discover(s,id,choice){hydrate(s);const d=W.discoveries.find(d=>d.id===id),c=P.discoveryText[id]&&P.discoveryText[id].choices.find(c=>c.id===choice);if(s.ended||s.docked||!d||!c||s.finds[id]||Math.hypot(W.discoveryPosition(s,d).x-s.ship.x,W.discoveryPosition(s,d).y-s.ship.y)>=65||s.fuel<(c.fuel||0))return false;
 s.finds[id]=choice;s.fuel-=c.fuel||0;s.credits+=c.payment;s.ship.speed=0;advance(s,c.minutes);log(s,c.result);return true;}
function destination(s,id){if(s.docked||!s.voyage||s.ended||(id!==null&&!W.ports.some(p=>p.id===id)))return false;s.voyage.to=id;s.voyage.line=P.crossing(s,s.voyage.from,(s.passages[s.voyage.from]||1)-1,id);return true;}
function people(s){if(!s.docked)return [];const ids=W.ports.find(p=>p.id===s.docked).people.slice();if(s.flags.naoAboard&&!ids.includes('nao'))ids.push('nao');return ids;}
function stories(s){const rows=[];
 if(s.flags.constellationAccepted){const need=!s.flags.constellationTea?'Collect Jun’s roasted tea at Kisaragi · 6 cr, 5 min.':!s.flags.constellationGinger?'Collect Mei’s ginger biscuits at Kurage 33 · 4 cr, 5 min.':!s.flags.naoAboard?'Invite Nao aboard at Lantern Market.':'Sail with Nao to Tsukimi and share the supper · Free, 12 min.';rows.push({id:'constellation',title:'Nao & Mio · A supper drawn from stars',done:!!s.flags.constellationDone,to:!s.flags.constellationTea?'canal':!s.flags.constellationGinger?'bar':!s.flags.naoAboard?'market':'observatory',text:s.flags.constellationDone?'Shared roasted tea, ginger biscuits and a constellation supper with Nao and Mio. Bring Nao home when you are ready.':need});}

 if(s.flags.teaAccepted)rows.push({id:'tea',title:'Mei · Tea across the water',done:!!s.flags.teaDelivered,to:'market',text:s.flags.teaDelivered?'Nao received the tea · 24 cr paid.':s.clock>P.tea.deadline?'Delivery window closed; no automatic payment.':'Take the case to Nao at Lantern Market. Start by 03:40 · 24 cr payment.'});
 if(s.flags.lampAccepted)rows.push({id:'lamp',title:'Aki · Keep the light turning',done:!!s.flags.lampDelivered,to:'island',text:s.flags.lampDelivered?'Lighthouse kit delivered · 40 cr paid.':s.clock>P.lamp.deadline?'Delivery window closed; Aki arranges the day crew. No automatic payment.':'Take Rin’s kit to Aki on Hoshimi Island by 05:00 · 40 cr payment.'});
 if(s.flags.naoInvited)rows.push({id:'nao',title:'Nao · A table beyond the locks',done:!!s.flags.naoReturned,to:s.flags.naoPreview?'market':'canal',text:s.flags.naoReturned?'You shared Nao’s preview supper and brought her home.':s.flags.naoPreview?'Return to Lantern Market and bring Nao back to her counter.':s.flags.naoAboard?'Sail to Kisaragi and join Hana’s preview supper. No stock purchase or deadline.':'Nao’s little festival table is waiting.'});
 if(s.flags.naoOuting||s.flags.naoOutingDone)rows.push({id:'nao-outing',title:'Nao · Another little voyage',done:!!s.flags.naoOutingDone,to:'market',text:s.flags.naoOuting?'Explore together, then bring Nao back to her market counter.':'Shared another crossing and brought Nao home.'});
 if(s.flags.skySeen)rows.push({id:'sky',title:'Mio · A window beyond the city',done:true,to:'observatory',text:s.flags.naoSkySeen?'Calibrated the telescope and shared the outer-bay sky with Nao.':'Calibrated the telescope and watched the outer-bay sky with Mio.'});
 Object.entries(s.finds||{}).forEach(([id,result])=>rows.push({id:'find-'+id,title:W.discoveries.find(d=>d.id===id).name,done:true,text:P.discoveryText[id].choices.find(c=>c.id===result).result}));
 if(s.flags.pump)rows.push({id:'pump',title:'Rin · Second Helping',done:true,to:'yard',text:'Bilge pump repaired · No parts purchase needed.'});
 Object.entries(s.cargo||{}).forEach(([id,c])=>{const d=P.freight[id];rows.push({id:'cargo-'+id,title:d.title,done:!c.units,to:d.to,text:c.released?'Delivery window closed; case unloaded without payment.':!c.units?'Delivered · '+c.revenue+' cr payment − '+c.cost+' cr purchase.':(s.clock>d.deadline?'Delivery window closed. ':'Deliver to '+W.ports.find(p=>p.id===d.to).name+' by '+time(d.deadline)+'. ')+c.cost+' cr purchase · '+d.payment+' cr promised; fuel extra.'});});return rows;}
function hear(s,id){hydrate(s);const r=P.signals.find(r=>r.id===id);if(!r||s.ended||s.clock<r.at)return false;if(s.rumours[id]===undefined)s.rumours[id]=s.clock;return true;}
function rumourRows(s){return Object.entries(s.rumours||{}).map(([id,heard])=>({...P.signals.find(r=>r.id===id),heard,age:Math.floor(s.clock-heard)}));}
function routePreview(s,id){const to=W.ports.find(p=>p.id===id);if(!to||s.ended)return null;const r=routeStats(s,s.ship,to);return {...r,to:to.name,arrival:s.clock+r.minutes,enough:s.fuel>=r.fuel};}
function log(s,text){s.log.unshift(time(s.clock)+' · '+text);s.log=s.log.slice(0,40);}
function advance(s,minutes){s.clock=Math.min(1800,s.clock+minutes);if(s.clock>=1800){s.ended=true;s.ship.speed=0;}}
function observe(s){if(!s.docked)return;const q=M.quote(P.economy,s.truth,s.seed,s.docked,s.clock,s.trades);s.quotes[s.docked]={buy:q.buy,sell:q.sell,at:s.clock};}
function trade(s,kind,amount){if(s.ended||!s.docked||!Number.isInteger(amount)||amount<1||!['buy','sell'].includes(kind))return false;
 const q=M.quote(P.economy,s.truth,s.seed,s.docked,s.clock,s.trades),held=M.lots.total(s.gold);
 if(kind==='buy'){if(amount>q.canBuy||amount*q.buy>s.credits)return false;const total=amount*q.buy;s.credits-=total;s.gold=M.lots.buy(s.gold,amount,q.buy,{where:s.docked,at:s.clock});s.trades.push({kind,grams:amount,total,price:q.buy,where:s.docked,at:s.clock});}
 else{if(amount>held||amount>q.canSell)return false;const sold=M.lots.sell(s.gold,amount),total=amount*q.sell;s.gold=sold.lots;s.credits+=total;s.trades.push({kind,grams:amount,total,basis:sold.basis,price:q.sell,where:s.docked,at:s.clock});}
 log(s,(kind==='buy'?'Bought ':'Sold ')+amount+' g of gold.');observe(s);return true;}
function action(s,id){if(s.ended)return false;
 if(id==='accept-tea'){if(s.docked!=='bar'||s.flags.teaAccepted||held(s)>=capacity(s)||s.clock+5>P.tea.deadline)return false;s.flags.teaAccepted=true;advance(s,5);log(s,'Collected Mei’s sealed tea for Nao.');}
 else if(id==='deliver-tea'){if(s.docked!=='market'||!s.flags.teaAccepted||s.flags.teaDelivered||s.clock>P.tea.deadline)return false;s.flags.teaDelivered=true;s.credits+=P.tea.fee;advance(s,5);log(s,'Nao received Mei’s tea. Courier payment: 24 cr.');}
 else if(id==='meal'){const meal=P.meals[s.docked];if(!meal||s.credits<meal.price)return false;s.credits-=meal.price;advance(s,meal.minutes);log(s,'Sat down for '+meal.name.toLowerCase()+'.');}
 else if(id==='fuel'){if(!['landing','yard','canal','observatory'].includes(s.docked)||s.fuel>=5.99||s.credits<30)return false;s.credits-=30;s.fuel=6;advance(s,10);log(s,'Refuelled at '+W.ports.find(p=>p.id===s.docked).name+'.');}
 else if(id==='engine'){if(s.docked!=='market'||s.flags.engine||s.credits<80)return false;s.credits-=80;s.flags.engine=true;advance(s,15);log(s,'Kenji tuned the engine: faster sailing, 20% less fuel per distance.');}
 else if(id==='hold'){if(s.docked!=='market'||s.flags.hold||s.credits<65)return false;s.credits-=65;s.flags.hold=true;advance(s,10);log(s,'Cargo racks fitted: three shared case slots.');}
 else if(id==='lamp-collect'){if(s.docked!=='yard'||s.flags.lampAccepted||held(s)>=capacity(s)||s.clock+5>P.lamp.deadline)return false;s.flags.lampAccepted=true;advance(s,5);log(s,'Collected Rin’s sealed lighthouse kit for Aki.');}
 else if(id==='lamp-deliver'){if(s.docked!=='island'||!s.flags.lampAccepted||s.flags.lampDelivered||s.clock>P.lamp.deadline)return false;s.flags.lampDelivered=true;s.credits+=P.lamp.payment;advance(s,5);log(s,'Aki received the lighthouse kit: 40 cr courier payment.');}
 else if(id==='repair-pump'){if(s.docked!=='yard'||s.flags.pump)return false;s.flags.pump=true;advance(s,10);log(s,'Helped Rin repair Second Helping’s bilge pump.');}
 else if(id==='nao-invite'){if(s.docked!=='market'||!s.flags.teaDelivered||s.flags.naoInvited)return false;s.flags.naoInvited=true;s.flags.naoAboard=true;advance(s,5);log(s,'Nao prepared a sample and joined the ferry for Kisaragi.');}
 else if(id==='nao-outing'){if(s.docked!=='market'||!s.flags.naoReturned||s.flags.naoAboard)return false;s.flags.naoAboard=true;s.flags.naoOuting=true;s.flags.naoOutingDone=false;advance(s,5);log(s,'Nao joined the Tern for another little voyage. Bring her back to the market.');}
 else if(id==='nao-preview'){if(s.docked!=='canal'||!s.flags.naoAboard||s.flags.naoPreview)return false;s.flags.naoPreview=true;advance(s,10);log(s,'Shared Nao’s preview supper with Hana: a little table on Nao’s terms.');}
 else if(id==='nao-return'){if(s.docked!=='market'||!s.flags.naoPreview||!s.flags.naoAboard)return false;s.flags.naoAboard=false;s.flags.naoReturned=true;if(s.flags.naoOuting){s.flags.naoOuting=false;s.flags.naoOutingDone=true;}log(s,'Brought Nao home to her counter.');}
 else if(id==='sky-watch'){if(s.docked!=='observatory'||!s.flags.observatorySupplied||s.flags.skySeen)return false;s.flags.skySeen=true;if(s.flags.naoAboard)s.flags.naoSkySeen=true;advance(s,12);log(s,'Shared a sky watch through Mio’s calibrated telescope and saved exposures.');}
 else if(id==='share-sky'){if(s.docked!=='observatory'||!s.flags.skySeen||!s.flags.naoAboard||s.flags.naoSkySeen)return false;s.flags.naoSkySeen=true;advance(s,6);log(s,'Shared Mio’s telescope and saved sky exposures with Nao on a return visit.');}
 else if(id==='constellation-start'){if(!people(s).includes('nao')||!s.flags.naoSkySeen||s.flags.constellationAccepted)return false;s.flags.constellationAccepted=true;log(s,'Nao planned a constellation supper: collect Jun’s roasted tea and Mei’s ginger biscuits, then sail with her to Mio.');}
 else if(id==='constellation-tea'||id==='constellation-ginger'){const tea=id==='constellation-tea',flag=tea?'constellationTea':'constellationGinger',port=tea?'canal':'bar',cost=tea?6:4;if(!s.flags.constellationAccepted||s.flags[flag]||s.docked!==port||s.credits<cost)return false;s.flags[flag]=true;s.credits-=cost;advance(s,5);log(s,'Collected '+(tea?'Jun’s roasted tea':'Mei’s ginger biscuits')+' for '+cost+' cr. Recipe basket; no cargo slot used.');}
 else if(id==='constellation-supper'){if(s.docked!=='observatory'||!s.flags.naoAboard||!s.flags.constellationAccepted||!s.flags.constellationTea||!s.flags.constellationGinger||s.flags.constellationDone)return false;s.flags.constellationDone=true;advance(s,12);log(s,'Shared Nao’s constellation supper with Mio: roasted tea, ginger biscuits and a star chart kept for the voyage home.');}
 else if(id==='salvage'){if(s.docked||s.flags.salvage||Math.hypot(s.ship.x-W.salvage.x,s.ship.y-W.salvage.y)>65)return false;s.flags.salvage=true;s.credits+=36;s.ship.speed=0;advance(s,12);log(s,'Recovered a sealed signal-light kit. Salvage value: 36 cr.');}
 else if(id==='tow'){if(s.docked)return false;const fee=Math.min(20,s.credits);s.credits-=fee;s.fuel=Math.max(3,s.fuel);s.docked='landing';s.ship={x:365,y:385,angle:0,speed:0};advance(s,20);log(s,'Harbour tug brought you home for '+fee+' cr.');observe(s);}
 else return false;observe(s);return true;}
function nearby(s){return W.ports.find(p=>Math.hypot(p.x-s.ship.x,p.y-s.ship.y)<65)||null;}
function dock(s){if(s.ended||s.docked)return false;const p=nearby(s);if(!p)return false;s.docked=p.id;hydrate(s);s.visits[p.id]=(s.visits[p.id]||0)+1;s.ship={x:p.x,y:p.y,angle:s.ship.angle,speed:0};observe(s);log(s,'Moored at '+p.name+'.');return true;}
function depart(s){if(s.ended||!s.docked)return false;hydrate(s);const from=s.docked,n=s.passages[from]||0;s.voyage={from,distance:0,line:P.crossing(s,from,n)};s.passages[from]=n+1;s.docked=null;s.ship.speed=0;return true;}
function move(s,input,dt){if(s.ended||s.docked)return 0;if(s.fuel<=0){s.ship.speed=0;return 0;}const distance=N.step(s.ship,input,dt,s.flags.engine);if(distance>0){if(s.voyage)s.voyage.distance+=distance;s.fuel=Math.max(0,s.fuel-distance/620*(s.flags.engine?.8:1));advance(s,Math.max(0,Math.min(.05,dt))*2);}return distance;}
function chat(s,id){hydrate(s);const c=P.characters[id];if(!c||!s.docked||!people(s).includes(id))return null;P.signals.filter(r=>r.who===id&&s.clock>=r.at).forEach(r=>hear(s,r.id));let text;
 if(['nao','mio','jun','mei'].includes(id)&&s.flags.constellationDone&&!s.flags['supperThanks-'+id]){s.flags['supperThanks-'+id]=true;text={nao:'I named the little triangle of biscuits after our ferry. Mio said astronomy could survive that. I’m keeping the recipe and the map together.',mio:'Warm cups beside cold lenses. Your supper gave the star chart a memory I could never have recorded with an instrument.',jun:'Nao sent a drawing of three cups under the stars. That is an excellent destination for a packet of tea.',mei:'The biscuits made it beyond the city lights? Good. A recipe should get to see something of the world.'}[id];}
 else if(Object.entries(s.cargo||{}).some(([key,c])=>{const d=P.freight[key];return !c.units&&!c.released&&(d.recipient===id||d.source===id)&&!s.flags['thanks-'+key+'-'+id];})){const [key,c]=Object.entries(s.cargo).find(([key,c])=>{const d=P.freight[key];return !c.units&&!c.released&&(d.recipient===id||d.source===id)&&!s.flags['thanks-'+key+'-'+id];});s.flags['thanks-'+key+'-'+id]=true;text='The '+P.freight[key].title.toLowerCase()+' arrived safe and sealed. The payment is settled; thank you for making a careful crossing.';}
 else if(id==='nao'&&s.flags.naoSkySeen&&!s.flags.naoSkyThanks){s.flags.naoSkyThanks=true;text='I thought the telescope would make home seem small. It made me glad we had somewhere warm to return to. Thank you for sharing that window with me.';}
 else if(id==='nao'&&s.flags.naoPreview&&!s.flags.naoPreviewThanks){s.flags.naoPreviewThanks=true;text='One little table. Hana didn’t ask me to promise a bigger one next year. Thank you for making the crossing feel like a visit instead of a test.';}
 else if(id==='aki'&&s.flags.lampDelivered&&!s.flags.akiThanks){s.flags.akiThanks=true;text='The new kit is fitted. Watch that steady sweep—your voyage will guide other voyages home.';}
 else if(id==='rin'&&s.flags.pump&&!s.flags.rinThanks){s.flags.rinThanks=true;text='Listen. No knocking. Second Helping is ready for the day crew. That calm little hum has some of your patience in it.';}
 else if(id==='nao'&&s.flags.teaDelivered&&!s.flags.naoThanks){s.flags.naoThanks=true;text='Mei’s tea, safe and dry! Thank you, captain. The delivery fee is settled; this smile is simply mine to give.';}
 else{const n=s.chats[id]||0;text=id==='nao'&&s.flags.naoAboard?P.naoTravel(s,s.docked,n).text:c.chats[n%c.chats.length];s.chats[id]=n+1;}return text;}
window.VoyageModel={create,valid,hydrate,hear,rumourRows,routePreview,held,capacity,freight,release,waitFreight,estimate,weather,routeStats,plan,collected,nearDiscovery,discover,destination,people,stories,time,log,advance,observe,trade,action,nearby,dock,depart,move,chat};})();
