/* Playtest rules and saves are separate from Classic. */
(function(){'use strict';const P=window.VoyagePorts,W=window.VoyageWorld,N=window.VoyageNavigation,M=window.NeonMarket;
const time=n=>String(Math.floor(n/60)%24).padStart(2,'0')+':'+String(Math.floor(n)%60).padStart(2,'0');
function create(seed){const truth=M.pickTruth(P.economy,seed);return {version:1,seed,truth,ship:{x:1320,y:395,angle:Math.PI/2,speed:0},docked:'bar',clock:1420,credits:360,fuel:6,gold:[{grams:2,cost:91,karat:24}],trades:[],quotes:{},flags:{},chats:{},cargo:{},visits:{bar:1},track:null,log:['Your first voyage begins at Mei’s quay.'],ended:false};}
function valid(s){return !!s&&s.version===1&&typeof s.seed==='string'&&['order','vault','both'].includes(s.truth)&&s.ship&&[s.ship.x,s.ship.y,s.ship.angle,s.ship.speed,s.clock,s.credits,s.fuel].every(Number.isFinite)&&N.water(s.ship.x,s.ship.y)&&s.credits>=0&&s.fuel>=0&&s.fuel<=6&&s.clock>=1420&&s.clock<=1800&&(s.docked===null||W.ports.some(p=>p.id===s.docked))&&(!s.docked||Math.hypot(s.ship.x-W.ports.find(p=>p.id===s.docked).x,s.ship.y-W.ports.find(p=>p.id===s.docked).y)<70)&&Array.isArray(s.gold)&&s.gold.every(l=>l&&Number.isFinite(l.grams)&&l.grams>=0&&Number.isFinite(l.cost)&&l.cost>=0)&&Array.isArray(s.trades)&&s.trades.every(t=>t&&['buy','sell'].includes(t.kind)&&W.ports.some(p=>p.id===t.where)&&[t.at,t.grams,t.total,t.price].every(Number.isFinite))&&s.flags&&!Array.isArray(s.flags)&&typeof s.flags==='object'&&Object.values(s.flags).every(v=>typeof v==='boolean')&&s.chats&&!Array.isArray(s.chats)&&typeof s.chats==='object'&&Object.entries(s.chats).every(([id,n])=>P.characters[id]&&Number.isInteger(n)&&n>=0)&&s.quotes&&!Array.isArray(s.quotes)&&typeof s.quotes==='object'&&Object.entries(s.quotes).every(([id,q])=>W.ports.some(p=>p.id===id)&&q&&[q.buy,q.sell,q.at].every(Number.isFinite))&&Array.isArray(s.log)&&s.log.every(x=>typeof x==='string')&&typeof s.ended==='boolean'&&(s.cargo===undefined||validCargo(s.cargo))&&(s.visits===undefined||(!Array.isArray(s.visits)&&s.visits&&Object.entries(s.visits).every(([id,n])=>W.ports.some(p=>p.id===id)&&Number.isInteger(n)&&n>=0)))&&(s.track===undefined||s.track===null||typeof s.track==='string')&&held(s)<=capacity(s);}
function validCargo(cargo){return cargo&&!Array.isArray(cargo)&&typeof cargo==='object'&&Object.entries(cargo).every(([id,c])=>P.freight[id]&&c&&c.cost===P.freight[id].cost&&[0,1].includes(c.units)&&c.revenue===(c.units?0:P.freight[id].payment));}
function hydrate(s){if(s.cargo===undefined)s.cargo={};if(s.visits===undefined)s.visits={bar:1};if(s.track===undefined)s.track=null;return s;}
function held(s){return Object.values(s.cargo||{}).reduce((n,c)=>n+c.units,0)+(s.flags.teaAccepted&&!s.flags.teaDelivered?1:0)+(s.flags.lampAccepted&&!s.flags.lampDelivered?1:0);}
function capacity(s){return s.flags.hold?3:2;}
function freight(s,id,deliver){hydrate(s);const d=P.freight[id];if(!d||s.ended||s.docked!==(deliver?d.to:d.from))return false;
 if(deliver){const c=s.cargo[id];if(!c||!c.units||s.clock>d.deadline)return false;c.units=0;c.revenue=d.payment;s.credits+=d.payment;advance(s,5);log(s,d.title+' delivered: '+d.payment+' cr; '+d.cost+' cr purchase.');}
 else{if(s.cargo[id]||held(s)>=capacity(s)||s.credits<d.cost||s.clock+5>d.deadline)return false;s.credits-=d.cost;s.cargo[id]={cost:d.cost,revenue:0,units:1};advance(s,5);log(s,'Bought '+d.title+' for '+d.cost+' cr.');}observe(s);return true;}
function people(s){if(!s.docked)return [];const ids=W.ports.find(p=>p.id===s.docked).people.slice();if(s.flags.naoAboard&&!ids.includes('nao'))ids.push('nao');return ids;}
function stories(s){const rows=[];
 if(s.flags.teaAccepted)rows.push({id:'tea',title:'Mei · Tea across the water',done:!!s.flags.teaDelivered,to:'market',text:s.flags.teaDelivered?'Nao received the tea · 24 cr paid.':s.clock>P.tea.deadline?'Delivery window closed; no automatic payment.':'Take the case to Nao at Lantern Market. Start by 03:40 · 24 cr payment.'});
 if(s.flags.lampAccepted)rows.push({id:'lamp',title:'Aki · Keep the light turning',done:!!s.flags.lampDelivered,to:'island',text:s.flags.lampDelivered?'Lighthouse kit delivered · 40 cr paid.':s.clock>P.lamp.deadline?'Delivery window closed; Aki arranges the day crew. No automatic payment.':'Take Rin’s kit to Aki on Hoshimi Island by 05:00 · 40 cr payment.'});
 if(s.flags.naoInvited)rows.push({id:'nao',title:'Nao · A table beyond the locks',done:!!s.flags.naoReturned,to:s.flags.naoPreview?'market':'canal',text:s.flags.naoReturned?'You shared Nao’s preview supper and brought her home.':s.flags.naoPreview?'Return to Lantern Market and bring Nao back to her counter.':s.flags.naoAboard?'Sail to Kisaragi and join Hana’s preview supper. No stock purchase or deadline.':'Nao’s little festival table is waiting.'});
 if(s.flags.pump)rows.push({id:'pump',title:'Rin · Second Helping',done:true,to:'yard',text:'Bilge pump repaired · No parts purchase needed.'});
 Object.entries(s.cargo||{}).forEach(([id,c])=>{const d=P.freight[id];rows.push({id:'cargo-'+id,title:d.title,done:!c.units,to:d.to,text:!c.units?'Delivered · '+c.revenue+' cr payment − '+c.cost+' cr purchase.':(s.clock>d.deadline?'Delivery window closed. ':'Deliver to '+W.ports.find(p=>p.id===d.to).name+' by '+time(d.deadline)+'. ')+c.cost+' cr purchase · '+d.payment+' cr promised; fuel extra.'});});return rows;}
function log(s,text){s.log.unshift(time(s.clock)+' · '+text);s.log=s.log.slice(0,40);}
function advance(s,minutes){s.clock=Math.min(1800,s.clock+minutes);if(s.clock>=1800){s.ended=true;s.ship.speed=0;}}
function observe(s){if(!s.docked)return;const q=M.quote(P.economy,s.truth,s.seed,s.docked,s.clock,s.trades);s.quotes[s.docked]={buy:q.buy,sell:q.sell,at:s.clock};}
function trade(s,kind,amount){if(s.ended||!s.docked||!Number.isInteger(amount)||amount<1||!['buy','sell'].includes(kind))return false;
 const q=M.quote(P.economy,s.truth,s.seed,s.docked,s.clock,s.trades),held=M.lots.total(s.gold);
 if(kind==='buy'){if(amount>q.canBuy||amount*q.buy>s.credits)return false;const total=amount*q.buy;s.credits-=total;s.gold=M.lots.buy(s.gold,amount,q.buy,{where:s.docked,at:s.clock});s.trades.push({kind,grams:amount,total,price:q.buy,where:s.docked,at:s.clock});}
 else{if(amount>held||amount>q.canSell)return false;const sold=M.lots.sell(s.gold,amount),total=amount*q.sell;s.gold=sold.lots;s.credits+=total;s.trades.push({kind,grams:amount,total,basis:sold.basis,price:q.sell,where:s.docked,at:s.clock});}
 log(s,(kind==='buy'?'Bought ':'Sold ')+amount+' g of gold.');observe(s);return true;}
function action(s,id){if(s.ended)return false;
 if(id==='accept-tea'){if(s.docked!=='bar'||s.flags.teaAccepted||held(s)>=capacity(s)||s.clock+5>P.tea.deadline)return false;s.flags.teaAccepted=true;advance(s,5);log(s,'Collected Mei’s sealed tea for Nao.');}
 else if(id==='deliver-tea'){if(s.docked!=='market'||!s.flags.teaAccepted||s.flags.teaDelivered||s.clock>P.tea.deadline)return false;s.flags.teaDelivered=true;s.credits+=P.tea.fee;advance(s,5);log(s,'Nao received Mei’s tea. Courier payment: 24 cr.');}
 else if(id==='meal'){const meal=P.meals[s.docked];if(!meal||s.credits<meal.price)return false;s.credits-=meal.price;advance(s,meal.minutes);log(s,'Sat down for '+meal.name.toLowerCase()+'.');}
 else if(id==='fuel'){if(!['landing','yard','canal'].includes(s.docked)||s.fuel>=5.99||s.credits<30)return false;s.credits-=30;s.fuel=6;advance(s,10);log(s,'Refuelled at '+W.ports.find(p=>p.id===s.docked).name+'.');}
 else if(id==='engine'){if(s.docked!=='market'||s.flags.engine||s.credits<80)return false;s.credits-=80;s.flags.engine=true;advance(s,15);log(s,'Kenji tuned the engine: faster sailing, 20% less fuel per distance.');}
 else if(id==='hold'){if(s.docked!=='market'||s.flags.hold||s.credits<65)return false;s.credits-=65;s.flags.hold=true;advance(s,10);log(s,'Cargo racks fitted: three shared case slots.');}
 else if(id==='lamp-collect'){if(s.docked!=='yard'||s.flags.lampAccepted||held(s)>=capacity(s)||s.clock+5>P.lamp.deadline)return false;s.flags.lampAccepted=true;advance(s,5);log(s,'Collected Rin’s sealed lighthouse kit for Aki.');}
 else if(id==='lamp-deliver'){if(s.docked!=='island'||!s.flags.lampAccepted||s.flags.lampDelivered||s.clock>P.lamp.deadline)return false;s.flags.lampDelivered=true;s.credits+=P.lamp.payment;advance(s,5);log(s,'Aki received the lighthouse kit: 40 cr courier payment.');}
 else if(id==='repair-pump'){if(s.docked!=='yard'||s.flags.pump)return false;s.flags.pump=true;advance(s,10);log(s,'Helped Rin repair Second Helping’s bilge pump.');}
 else if(id==='nao-invite'){if(s.docked!=='market'||!s.flags.teaDelivered||s.flags.naoInvited)return false;s.flags.naoInvited=true;s.flags.naoAboard=true;advance(s,5);log(s,'Nao prepared a sample and joined the ferry for Kisaragi.');}
 else if(id==='nao-preview'){if(s.docked!=='canal'||!s.flags.naoAboard||s.flags.naoPreview)return false;s.flags.naoPreview=true;advance(s,10);log(s,'Shared Nao’s preview supper with Hana: a little table on Nao’s terms.');}
 else if(id==='nao-return'){if(s.docked!=='market'||!s.flags.naoPreview||!s.flags.naoAboard)return false;s.flags.naoAboard=false;s.flags.naoReturned=true;log(s,'Brought Nao home to her counter.');}
 else if(id==='salvage'){if(s.docked||s.flags.salvage||Math.hypot(s.ship.x-W.salvage.x,s.ship.y-W.salvage.y)>65)return false;s.flags.salvage=true;s.credits+=36;s.ship.speed=0;advance(s,12);log(s,'Recovered a sealed signal-light kit. Salvage value: 36 cr.');}
 else if(id==='tow'){if(s.docked)return false;const fee=Math.min(20,s.credits);s.credits-=fee;s.fuel=Math.max(3,s.fuel);s.docked='landing';s.ship={x:365,y:385,angle:0,speed:0};advance(s,20);log(s,'Harbour tug brought you home for '+fee+' cr.');observe(s);}
 else return false;observe(s);return true;}
function nearby(s){return W.ports.find(p=>Math.hypot(p.x-s.ship.x,p.y-s.ship.y)<65)||null;}
function dock(s){if(s.ended||s.docked)return false;const p=nearby(s);if(!p)return false;s.docked=p.id;hydrate(s);s.visits[p.id]=(s.visits[p.id]||0)+1;s.ship={x:p.x,y:p.y,angle:s.ship.angle,speed:0};observe(s);log(s,'Moored at '+p.name+'.');return true;}
function depart(s){if(s.ended||!s.docked)return false;s.docked=null;s.ship.speed=0;return true;}
function move(s,input,dt){if(s.ended||s.docked)return 0;if(s.fuel<=0){s.ship.speed=0;return 0;}const distance=N.step(s.ship,input,dt,s.flags.engine);if(distance>0){s.fuel=Math.max(0,s.fuel-distance/620*(s.flags.engine?.8:1));advance(s,Math.max(0,Math.min(.05,dt))*2);}return distance;}
function chat(s,id){const c=P.characters[id];if(!c||!s.docked||!people(s).includes(id))return null;let text;
 if(id==='nao'&&s.flags.naoPreview&&!s.flags.naoPreviewThanks){s.flags.naoPreviewThanks=true;text='One little table. Hana didn’t ask me to promise a bigger one next year. Thank you for making the crossing feel like a visit instead of a test.';}
 else if(id==='aki'&&s.flags.lampDelivered&&!s.flags.akiThanks){s.flags.akiThanks=true;text='The new kit is fitted. Watch that steady sweep—your voyage will guide other voyages home.';}
 else if(id==='rin'&&s.flags.pump&&!s.flags.rinThanks){s.flags.rinThanks=true;text='Listen. No knocking. Second Helping is ready for the day crew. That calm little hum has some of your patience in it.';}
 else if(id==='nao'&&s.flags.teaDelivered&&!s.flags.naoThanks){s.flags.naoThanks=true;text='Mei’s tea, safe and dry! Thank you, captain. The delivery fee is settled; this smile is simply mine to give.';}
 else{const n=s.chats[id]||0;text=c.chats[n%c.chats.length];s.chats[id]=n+1;}return text;}
window.VoyageModel={create,valid,hydrate,held,capacity,freight,people,stories,time,log,advance,observe,trade,action,nearby,dock,depart,move,chat};})();
