(function(){'use strict';
const clone=x=>JSON.parse(JSON.stringify(x)),D=clone(window.NEON_TIDES_TRADE);
D.market.local={bar:0,landing:-3,market:3,metro:.5,yard:-4,pier:4,canal:1,island:2};D.market.dealers={bar:D.market.dealers.bar,landing:D.market.dealers.landing,market:{name:'Sora’s lantern scale',spread:4,depth:12,stock:24,limit:30}};
Object.assign(D.market.dealers,{metro:{name:'Co-op platform scale',spread:6,depth:10,stock:12,limit:20},yard:{name:'Rin’s assayed salvage',spread:5,depth:10,stock:32,limit:24},pier:{name:'Frostline instrument desk',spread:4,depth:12,stock:18,limit:32},canal:{name:'Jun’s canal exchange',spread:6,depth:8,stock:12,limit:12},island:{name:'Aki’s emergency exchange',spread:8,depth:8,stock:6,limit:8}});
D.events=[{id:'coop',at:'00:20',where:'landing',truths:{}},{id:'crews',at:'00:55',where:'market',truths:{}},{id:'instruments',at:'02:00',where:'pier',truths:{}}];
for(const truth of ['order','vault','both']){D.events[0].truths[truth]={mods:[{loc:'landing',pct:-6,ramp:12,hold:'end'}]};D.events[1].truths[truth]={mods:[{loc:'market',pct:5,ramp:15,hold:'end'}]};D.events[2].truths[truth]={mods:[{loc:'pier',pct:7,ramp:12,hold:'end'}]};}
window.VoyagePorts={economy:D,characters:{
 mei:{name:'Mei Kusanagi',role:'Kurage 33 · Kitchen & homecomings',portrait:'../assets/portraits/mei-manga.webp',chats:['A warm bowl is a perfectly respectable destination. You don’t need to discover an island every time you leave home.','Look at that rain. Even the lanterns want to come inside.','I used to count a good evening by the cash tin. These days I also count who sits down.','Your ferry has a patient engine. That’s a compliment; I’ve met some very dramatic ones.']},
 priya:{name:'Priya Gale',role:'Landing 3 · Harbour office',portrait:'../assets/portraits/priya-manga.webp',chats:['Welcome, captain. You’re not late. I haven’t put you on a timetable. Very generous of me.','The recycled-gold launch reaches this hatch after 00:20. Check the fresh board when you arrive.','A receipt needs a time as well as a number. Otherwise yesterday’s bargain will follow you around all night.','If you find a lantern in the reeds, approach slowly. Not everything that drifts is lost forever.']},
 sora:{name:'Sora Ember',role:'Lantern Market · Gold scale',portrait:'../assets/portraits/sora-manga.webp',chats:['Read both numbers, captain. Buying and selling are different sides of the same little scale.','Extra night crews are expected after 00:55. Their instruments need gold; compare my actual bid before trading.','Blue paper, brass scale, one careful signature. I like business that leaves everyone knowing what happened.','Nao says my lanterns make receipts look romantic. I’ve decided to accept that.']},
 nao:{name:'Nao Mizuno',role:'Lantern Market · Food, tea & a little courage',portrait:'../assets/portraits/nao-manga.webp',chats:['There’s a stool by the kettle. It’s yours until somebody else needs it, which is how most good things should work.','From here I watch the ferries turn their lights into long gold threads. I never get tired of that.','My breakfast menu has my name on it now. I still feel shy when somebody reads it out loud.','A little adventure, then somewhere warm to tell it. That sounds like a very good night to me.']}
},tea:{title:'Mei’s tea for Nao',from:'bar',to:'market',fee:24,deadline:1660},
 meals:{bar:{name:'Mei’s ginger noodles',price:7,minutes:12,who:'mei',text:'Eat while the broth is hot. Nao needs my tea at the market, and the co-op has a gold delivery at Landing 3. Pick a voyage you can afford to bring home.'},market:{name:'Nao’s tea & sesame bun',price:6,minutes:10,who:'nao',text:'The kettle is warm, the bun is yours, and your ferry can rest for ten minutes. I like a captain who remembers they are also a person.'}}
};})();

(function(){'use strict';const P=window.VoyagePorts;
function character(id,name,role,chats){P.characters[id]={name,role,portrait:'../assets/portraits/'+id+'-manga.webp',chats};}
character('kenji','Kenji Arata','Market workshop · Careful repairs',['The engine tune is a practical thing, not a racing promise. You’ll use less fuel for the same distance.','Rin has a lantern kit waiting at the yard. Aki needs it before five; no gold purchase involved.','I label every spare screw. The labels outnumber the screws, but morale is excellent.','A ferry should hum. If it makes a speech, bring it to me.']);
character('rin','Rin Starling','Starling Yard · Salvage engineer',['Every repaired boat is another way for somebody to get home. That’s a good enough reason to keep the shed open.','Aki’s lighthouse kit is sealed and ready. Forty credits on delivery before 05:00; fuel is yours to budget.','Second Helping’s pump needs ten patient minutes. I’ve got the parts; you can hold the light.','The frogs are giving the workshop puddles excellent reviews.']);
character('aki','Aki Hoshimi','Hoshimi Island · Keeper of the light',['A lighthouse isn’t a dramatic job on a good night. I rather treasure the good nights.','Rin’s kit will keep the lens mechanism steady. The beam reaches farther than any thank-you I can shout.','Watch one sweep before you leave. You can see the city breathing between the roofs.','I keep a thermos here for boats that took the long route.']);
character('jun','Jun Arai','Kisaragi · Tea and ceramics',['Warm the pot before you pour. My grandmother was right about that and fiercely competitive at cards.','Mei ordered one case of blue bowls. Twenty credits here, thirty-six on delivery. Check the deadline before making it yours.','I like a receipt with room for a thank-you.','A small ferry fits a small cargo. The view is complimentary.']);
character('hana','Hana Tsukino','Kisaragi · A table for new beginnings',['One dish, one little table. A visiting cook doesn’t need to become a new person for an evening.','If Nao would like to bring a sample, I’ve left space by the bridge. No entrance fee or stock order.','Paper lanterns look effortless because someone climbed the ladder before you arrived.','Four tables, enough chairs, and a kettle. A promising festival already.']);
character('mako','Mako Senda','Kisaragi · Lockkeeper',['A lock gate does one thing at a time. I try to learn from it.','Fuel is here if your return route is longer than your tank. Check your purse too.','The bridge was here before the street lamps. It has heard some excellent arguments about supper.','Take a moment to check your rope. A patient departure saves a surprising amount of excitement.']);
character('lam','Captain Lam','Metro Quay · Tidewise engineer',['A rumour can be a passenger without being your navigator. Check who saw what, and when.','A little boat has more places it can call home. That was always my favourite advantage.','Reefs are very patient. We should aim to be at least as patient as reefs.','The last train passes at 01:40. I’m taking the ferry tonight; I brought a longer story.']);
character('yumi','Yumi Sol','Metro Quay · Harbour healer',['Have you eaten, captain? A working ferry needs a working person.','A safe crossing and a warm meal are perfectly respectable kinds of adventure.','The clinic windows catch the lantern colours. Patients keep asking who put the stars there.','My next sketchbook page is going to be a ferry. You may hold the pose for exactly zero minutes.']);
character('matte','Matte Rook','Pier 9 · Cold-store watch',['An intact seal is a very comforting little circle. I check every one.','The instrument order opens at 02:00. Read the actual bid before you turn a rumour into a voyage.','Kenji’s pump-seal case costs eighteen at the yard; the desk pays thirty-two on timely delivery.','The cold store is loud. A quiet ferry arriving is a welcome change.']);
P.freight={bowls:{title:'Jun’s blue bowls',from:'canal',to:'bar',cost:20,payment:36,deadline:1750,source:'jun',recipient:'mei'},seals:{title:'Workshop pump seals',from:'yard',to:'pier',cost:18,payment:32,deadline:1730,source:'rin',recipient:'matte'}};
P.lamp={deadline:1740,payment:40};
Object.assign(P.meals,{yard:{name:'Workshop miso & rice',price:7,minutes:10,who:'rin',text:'Kenji called this a parts delivery. The part was dinner. We agreed it was essential equipment.'},canal:{name:'Jun’s roasted tea',price:4,minutes:8,who:'jun',text:'The first cup is for tasting. The second is for whatever you meant to say before you got busy tasting.'},metro:{name:'Warm soy milk',price:3,minutes:6,who:'yumi',text:'A little warmth before another crossing. No story required, though I’d be glad to hear one.'},island:{name:'Aki’s watchkeeper tea',price:3,minutes:8,who:'aki',text:'Stay for one sweep of the beam. Tea tastes different when you can see where everybody is trying to go.'}});
})();

(function(){'use strict';const P=window.VoyagePorts;
Object.assign(P.freight,{
 regulators:{title:'Gold-contact regulators',from:'metro',to:'market',cost:48,payment:78,opens:1490,deadline:1640,source:'lam',recipient:'kenji'},
 starter:{title:'Chilled jasmine starter',from:'pier',to:'canal',cost:28,payment:50,opens:1560,deadline:1770,source:'matte',recipient:'hana'}
});
P.characters.lam.chats.push('The platform workshop releases gold-contact regulators at 00:50. Kenji pays seventy-eight for the sealed case; buying it costs forty-eight.');
P.characters.matte.chats.push('Hana’s jasmine starter clears the cold room at 02:00. Twenty-eight to buy, fifty at Kisaragi before 05:30. Keep the seal closed.');
P.characters.hana.chats.push('My evening tea needs the chilled jasmine starter from Frostline. The promise is fifty credits for one sealed case, before half past five.');
P.crossing=function(s,from,n){
 const voices=s.flags.naoAboard?[
 ['Nao','I practised saying “one small table” to the kettle. It listened beautifully. I hope Hana will, too.'],
 ['Nao','Those windows beyond the locks… each one is somebody coming home. I like being allowed to visit without having to stay.'],
 ['Nao',s.flags.naoPreview?'Hana saved the recipe card, not a promise from me. I can feel my shoulders coming down.':'If the sample is too salty, we’ll call it a very accurate portrait of the harbour.'],
 ['Nao','Shall we take a breath before the next quay? Even good adventures can use a little quiet.']
 ]:[
 ['Mako · Harbour radio','Tern, your light is clear from the locks. There’s a kettle beyond the bridge whenever you choose that route.'],
 ['Captain’s log','A homeward ferry passes at a distance. Its windows draw a warm line across the rain; someone raises a hand.'],
 ['Aki · Harbour radio',s.flags.lampDelivered?'Steady sweep from Hoshimi tonight. Your kit is doing its quiet work, captain.':'Hoshimi light to night traffic: clear water by the western marker. Safe crossings, all of you.'],
 ['Captain’s log','The engine finds its comfortable note. Between the buoys, the city sounds smaller and the water feels wide.']
 ];
 const local={bar:['Mei · Harbour radio','You left your scarf by the counter. No heroic turnabouts, please. It will still be here when you come home.'],yard:['Rin · Harbour radio',s.flags.pump?'Second Helping is ready for the day crew. That smooth pump is a little of your work sailing with them.':'The crane is asleep, the workshop isn’t. Give us a wave when you pass the reeds.'],pier:['Captain’s log','Behind the Tern, refrigeration fans fade into rain. Ahead, a string of lanterns marks the warmer water.'],canal:['Mako · Harbour radio','Clear of the lockside quay, Tern. Watch how the lanterns stretch as the channel opens. That is my favourite part.'],metro:['Captain’s log','A train rolls into the terminus. For a moment its lit windows and your wake are travelling side by side.']};
 const pool=local[from]&&!s.flags.naoAboard?[local[from],...voices]:voices;
 const [speaker,text]=pool[n%pool.length];return {speaker,text};
};
})();

(function(){'use strict';const P=window.VoyagePorts;
P.economy.market.local.observatory=5;P.economy.market.dealers.observatory={name:'Mio’s instrument exchange',spread:7,depth:8,stock:8,limit:12};
P.characters.mio={name:'Mio Amami',role:'Tsukimi · Astronomer & patient tinkerer',portrait:'../assets/portraits/mio.svg',chats:[
 'Welcome to the wide part of the night. The kettle is closer than the stars, so we usually begin there.',
 'Gold contacts resist corrosion. In a salt-air observatory, a reliable little connection is worth more than a dramatic machine.',
 'Kenji has a sealed gold-contact kit at the market: fifty-four to buy, one hundred here before 04:50. Mind the return fuel.',
 'A telescope is an invitation to be curious. You don’t need to know the names of everything you see.'
]};
P.characters.kenji.chats.push('Mio’s outer-bay kit clears my desk at 00:40. Fifty-four credits to buy, one hundred at Tsukimi before 04:50. The observatory has a fuel pump.');
P.freight.lenses={title:'Tsukimi gold-contact kit',from:'market',to:'observatory',cost:54,payment:100,opens:1480,deadline:1730,source:'kenji',recipient:'mio'};
P.meals.observatory={name:'Mio’s star-watch cocoa',price:4,minutes:8,who:'mio',text:'A little warmth while the dome turns. The cocoa is real; the stars can take their time.'};
P.discoveryText={
 drift:{intro:'A sealed survey chest rocks beside a buoy. Its salvage tag permits recovery; marking the position is enough if you are in a hurry.',choices:[{id:'recover',label:'Recover released salvage · Receive 18 cr · 8 min',minutes:8,payment:18,result:'The chest is dry inside. You record its release tag and eighteen credits of salvage value.'},{id:'mark',label:'Mark the position · Free · No time',minutes:0,payment:0,result:'You send the position to the survey crew. Someone with room aboard can collect it.'}]},
 boat:{intro:'The little delivery boat Kettle has a tired starter and a cheerful skipper. A small fuel transfer would get it home; the tug can also help.',choices:[{id:'help',label:'Transfer 0.6 fuel · Receive 20 cr · 10 min',minutes:10,payment:20,fuel:.6,result:'The skipper pays the agreed twenty credits. Kettle starts gently, and two little boats have a way home.'},{id:'radio',label:'Call the harbour tug · Free · 5 min',minutes:5,payment:0,result:'You relay Kettle’s position. The skipper waves as the tug answers; no fee or fuel transfer is needed.'}]},
 letter:{intro:'A small lantern carries a waterproof letter addressed to the visiting cook beyond the locks. You can read its public message or let it continue.',choices:[{id:'read',label:'Read the lantern message · Free · 5 min',minutes:5,payment:0,result:'“To the cook beyond the locks: your small table gave this week a place to sit. Thank you. —The day crew.” You copy the message, then set the lantern afloat again.'},{id:'release',label:'Let the lantern continue · Free · No time',minutes:0,payment:0,result:'You turn the lantern toward the canal. Some good messages can find their own crossing.'}]}
};
P.naoTravel=function(s,to,n){const weather=window.VoyageWorld.weather(s).name;
 const destinations={observatory:'The city has become a handful of lights. I thought the outer bay would feel lonely; it feels like room to breathe.',canal:s.flags.naoPreview?'I know which lantern is Hana’s now. That makes the whole canal feel a little nearer.':'One small table, one sample. I can say that without promising the whole festival.',market:'Home is ahead. I’ll bring the view back with me, even if there’s only room for one more postcard.',island:'Aki’s thermos must have the best view in the Basin. Perhaps we can share one sweep of the light.',bar:'Mei will ask whether we ate. I have prepared a thorough and reassuring answer.',yard:'Rin’s workshop smells of tea and useful things. Those are very comforting neighbours.',metro:'The train windows make a second little harbour. I wonder what everybody is taking home.',pier:'From a warm counter to a cold pier. I should ask Matte which tea gets through a long watch.'};
 const revisit=to&&(s.visits[to]||0)>0;
 const pool=[destinations[to]||'A little ferry, a wide piece of water. Thank you for making room for me aboard.',weather==='mist'?'The mist makes each buoy its own little island. We don’t need to hurry to find the next one.':weather==='rain'?'Listen to the rain on the cabin roof. It sounds like a kettle thinking about boiling.':'There’s a clear patch over the bay. Shall we keep a little of this quiet before the next quay?',revisit?'We’ve been this way before, but I notice different windows each time. A familiar route can still be a visit.':'If there’s somewhere warm at the next quay, I’d like to try its tea. No grand expedition needs to forget supper.',s.flags.skySeen?'I looked through Mio’s telescope and then looked back at our little ferry. Both things felt wonderfully real.':'I brought a recipe card for the voyage. The back is becoming a map of places I’d like to visit again.'];
 return {speaker:'Nao',text:pool[n%pool.length]};};
const original=P.crossing;P.crossing=function(s,from,n,to){if(s.flags.naoAboard)return P.naoTravel(s,to,n);if(to==='observatory')return {speaker:'Mio · Outer-bay radio',text:['Tsukimi to Tern: the western buoy leads into our sheltered quay. There’s fuel here for the journey home.','A clear spell is moving over the dome. Bring a little patience; we can wait for the stars together.','The gold-contact kit is small enough for your ferry, captain. A steady crossing is all the drama it needs.'][n%3]};return original(s,from,n);};
})();
