(function(){'use strict';
const clone=x=>JSON.parse(JSON.stringify(x)),D=clone(window.NEON_TIDES_TRADE);
D.market.local={bar:0,landing:-3,market:3};D.market.dealers={bar:D.market.dealers.bar,landing:D.market.dealers.landing,market:{name:'Sora’s lantern scale',spread:4,depth:12,stock:24,limit:30}};
D.events=[{id:'coop',at:'00:20',where:'landing',truths:{}},{id:'crews',at:'00:55',where:'market',truths:{}}];
for(const truth of ['order','vault','both']){D.events[0].truths[truth]={mods:[{loc:'landing',pct:-6,ramp:12,hold:'end'}]};D.events[1].truths[truth]={mods:[{loc:'market',pct:5,ramp:15,hold:'end'}]};}
window.VoyagePorts={economy:D,characters:{
 mei:{name:'Mei Kusanagi',role:'Kurage 33 · Kitchen & homecomings',portrait:'../assets/portraits/mei-manga.webp',chats:['A warm bowl is a perfectly respectable destination. You don’t need to discover an island every time you leave home.','Look at that rain. Even the lanterns want to come inside.','I used to count a good evening by the cash tin. These days I also count who sits down.','Your ferry has a patient engine. That’s a compliment; I’ve met some very dramatic ones.']},
 priya:{name:'Priya Gale',role:'Landing 3 · Harbour office',portrait:'../assets/portraits/priya-manga.webp',chats:['Welcome, captain. You’re not late. I haven’t put you on a timetable. Very generous of me.','The recycled-gold launch reaches this hatch after 00:20. Check the fresh board when you arrive.','A receipt needs a time as well as a number. Otherwise yesterday’s bargain will follow you around all night.','If you find a lantern in the reeds, approach slowly. Not everything that drifts is lost forever.']},
 sora:{name:'Sora Ember',role:'Lantern Market · Gold scale',portrait:'../assets/portraits/sora-manga.webp',chats:['Read both numbers, captain. Buying and selling are different sides of the same little scale.','Extra night crews are expected after 00:55. Their instruments need gold; compare my actual bid before trading.','Blue paper, brass scale, one careful signature. I like business that leaves everyone knowing what happened.','Nao says my lanterns make receipts look romantic. I’ve decided to accept that.']},
 nao:{name:'Nao Mizuno',role:'Lantern Market · Food, tea & a little courage',portrait:'../assets/portraits/nao-manga.webp',chats:['There’s a stool by the kettle. It’s yours until somebody else needs it, which is how most good things should work.','From here I watch the ferries turn their lights into long gold threads. I never get tired of that.','My breakfast menu has my name on it now. I still feel shy when somebody reads it out loud.','A little adventure, then somewhere warm to tell it. That sounds like a very good night to me.']}
},tea:{title:'Mei’s tea for Nao',from:'bar',to:'market',fee:24,deadline:1660},
 meals:{bar:{name:'Mei’s ginger noodles',price:7,minutes:12,who:'mei',text:'Eat while the broth is hot. Nao needs my tea at the market, and the co-op has a gold delivery at Landing 3. Pick a voyage you can afford to bring home.'},market:{name:'Nao’s tea & sesame bun',price:6,minutes:10,who:'nao',text:'The kettle is warm, the bun is yours, and your ferry can rest for ten minutes. I like a captain who remembers they are also a person.'}}
};})();
