/* Local continuity and cosmetics, kept independently of a single voyage. */
(function(){'use strict';const P=window.VoyagePorts,M=window.VoyageModel;
function create(){return {version:1,history:[],letters:[],look:{hull:'sand',lamp:'warm',plate:'TERN'},owned:{hull:['sand'],lamp:['warm'],plate:false}};}
function valid(p){return !!p&&p.version===1&&p.look&&Object.hasOwn(P.styles.hull,p.look.hull)&&Object.hasOwn(P.styles.lamp,p.look.lamp)&&typeof p.look.plate==='string'&&p.look.plate.length<=12&&/^[\p{L}\p{N} '\-]*$/u.test(p.look.plate)&&p.owned&&typeof p.owned.plate==='boolean'&&['hull','lamp'].every(k=>Array.isArray(p.owned[k])&&p.owned[k].length<=3&&p.owned[k].every(id=>Object.hasOwn(P.styles[k],id))&&p.owned[k].includes(p.look[k]))&&Array.isArray(p.history)&&p.history.length<=12&&p.history.every(r=>r&&typeof r.id==='string'&&typeof r.seed==='string'&&Number.isFinite(r.clock)&&r.clock>=1420&&r.clock<=1800&&[r.gold,r.cargo,r.discoveries,r.fuel].every(Number.isFinite)&&typeof r.partialFuel==='boolean'&&(r.goldUnknown===undefined||(Number.isInteger(r.goldUnknown)&&r.goldUnknown>=0))&&Array.isArray(r.moments)&&r.moments.every(t=>typeof t==='string'))&&Array.isArray(p.letters)&&p.letters.length<=48&&p.letters.every(l=>l&&typeof l.id==='string'&&typeof l.voyage==='string'&&Object.hasOwn(P.characters,l.who)&&typeof l.text==='string'&&typeof l.read==='boolean');}
function record(p,s){if(!s.ended)return false;M.hydrate(s);const row={id:s.uid,seed:s.seed,clock:s.clock,gold:M.realised(s).total,goldUnknown:M.realised(s).unknown,cargo:Object.values(s.cargo).reduce((n,c)=>n+c.revenue-c.cost,0),discoveries:Object.keys(s.finds).length+(s.flags.salvage?1:0),fuel:s.expenses.fuel,partialFuel:!s.expenses.complete,moments:M.stories(s).filter(r=>r.done&&!r.id.startsWith('cargo-')&&!r.id.startsWith('find-')).map(r=>r.title)};
 p.history=[row,...p.history.filter(r=>r.id!==row.id)].slice(0,12);const current=P.followup(s).map(l=>{const id=s.uid+'-'+l.who,old=p.letters.find(r=>r.id===id);return {...l,id,voyage:s.uid,read:old&&old.text===l.text?old.read:false};});
 p.letters=[...current,...p.letters.filter(l=>l.voyage!==s.uid)].filter(l=>p.history.some(r=>r.id===l.voyage)).slice(0,48);return true;}
function apply(p,s,kind,id){if(s.ended||!['hull','lamp','plate'].includes(kind)||!['market','yard'].includes(s.docked))return false;let cost=0;
 if(kind==='plate'){id=id.trim().toUpperCase();if(!id||id.length>12||!/^[\p{L}\p{N} '\-]+$/u.test(id))return false;cost=p.owned.plate?0:5;}else{const style=P.styles[kind]&&P.styles[kind][id];if(!style||!Object.hasOwn(P.styles[kind],id))return false;cost=p.owned[kind].includes(id)?0:style.cost;}
 if(s.credits<cost)return false;s.credits-=cost;if(kind==='plate')p.owned.plate=true;else if(!p.owned[kind].includes(id))p.owned[kind].push(id);p.look[kind]=id;M.log(s,'Ferry '+kind+' updated · '+cost+' cr · Cosmetic only.');return true;}
function read(p,id){const letter=p.letters.find(l=>l.id===id);if(!letter)return false;letter.read=true;return true;}
window.VoyageProfile={create,valid,record,apply,read};
})();
