(function(){'use strict';const W=window.VoyageWorld,N=window.VoyageNavigation,P=window.VoyagePorts,M=window.VoyageModel,Gold=window.NeonMarket,KEY='neon-tides:voyage:v1';
const $=id=>document.getElementById(id),canvas=$('sea'),ctx=canvas.getContext('2d'),panel=$('panel');let state,storageOK=true,loadNotice='',tab='people',person=null,speech='',paused=false,path=[],keys=new Set(),last=0,saveAt=0,hudAt=0,toastTimer=0,compareOrders=[],wideView=false,camera={x:0,y:0,scale:1},reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
try{const raw=localStorage.getItem(KEY);if(raw){const saved=JSON.parse(raw);if(M.valid(saved))state=saved;else loadNotice='That voyage save could not be read. A fresh voyage is ready; Classic is untouched.';}}catch(e){loadNotice='Saving is unavailable or the previous voyage could not be read. You can still sail this session.';}
if(!state)state=M.create('lantern-'+Date.now().toString(36));M.hydrate(state);M.observe(state);
// A radio preference is separate from the voyage save. Audio starts on an explicit tune click.
let ghost=false,radioVolume=.6,radioContext=null,radioBus=null,stopGhost=null,fxOn=false,fxVolume=.6,ferryAudio=null;
try{const savedFx=JSON.parse(localStorage.getItem('neon-tides:voyage:sound:v1')||'null');if(savedFx){fxOn=savedFx.enabled===true;if([.3,.6,1].includes(savedFx.volume))fxVolume=savedFx.volume;}}catch(e){}
try{const preference=JSON.parse(localStorage.getItem('neon-tides:voyage:radio:v1')||'null');if(preference){ghost=preference.station==='ghost';if([.3,.6,1].includes(preference.volume))radioVolume=preference.volume;}}catch(e){}
function audioGraph(){if(!radioContext){const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)throw Error('No audio');radioContext=new Ctx();radioBus=radioContext.createGain();radioBus.gain.value=radioVolume;const limiter=radioContext.createDynamicsCompressor();limiter.threshold.value=-18;limiter.ratio.value=4;radioBus.connect(limiter);limiter.connect(radioContext.destination);ferryAudio=window.VoyageSound.create(radioContext,limiter);ferryAudio.enable(fxOn,fxVolume);}return radioContext;}
function fxSave(){try{localStorage.setItem('neon-tides:voyage:sound:v1',JSON.stringify({enabled:fxOn,volume:fxVolume}));}catch(e){}radioView();}
function toggleFx(){try{const pending=fxOn&&!ferryAudio;audioGraph();fxOn=pending||!fxOn;ferryAudio.enable(fxOn,fxVolume);if(fxOn){const resume=radioContext.resume();if(resume&&resume.catch)resume.catch(()=>{fxOn=false;ferryAudio.enable(false,fxVolume);fxSave();toast('Tap Harbour sounds again to listen.');});ferryAudio.update(state,M.weather(state),false);}else if(!stopGhost)setTimeout(()=>{if(!fxOn&&!stopGhost)radioContext.suspend();},500);fxSave();radioMenu();}catch(e){fxOn=false;fxSave();toast('Harbour sounds could not start. You can keep sailing.');}}
function radioView(){document.body.classList.toggle('halloween-radio',ghost);$('radio-button').textContent=ghost?'Radio · Ghost Tide FM'+(!stopGhost?' · Tap to listen':''):'Radio · Off'+(fxOn?' · Sounds on':'');$('radio-button').setAttribute('aria-label','Radio: '+(ghost?'Ghost Tide FM':'Off')+'. Open radio controls.');}
function radioSave(){try{localStorage.setItem('neon-tides:voyage:radio:v1',JSON.stringify({station:ghost?'ghost':'off',volume:radioVolume}));}catch(e){}radioView();}
function radioOff(){ghost=false;if(stopGhost){stopGhost();stopGhost=null;}radioSave();if(radioContext){const c=radioContext;setTimeout(()=>{if(!ghost&&!(fxOn&&ferryAudio))c.suspend();},900);}}
function tuneGhost(){const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx){radioOff();toast('Audio is unavailable in this browser.');return;}try{audioGraph();if(stopGhost)stopGhost();ghost=true;radioBus.gain.setTargetAtTime(radioVolume,radioContext.currentTime,.2);stopGhost=window.NeonGhostRadio.start(radioContext,radioBus);const resume=radioContext.resume();if(resume&&resume.catch)resume.catch(()=>{radioOff();toast('Tap Tune again to start the radio.');});radioSave();panel.close();}catch(e){radioOff();toast('The radio could not start. You can keep sailing.');}}
function radioMenu(){openPanel('Radio & harbour sounds',[el('p','Ghost Tide FM · Halloween special · 72 BPM'),el('p','Soft sea wash, harbour wind and a slow, faded electronic pulse. A little eerie, somewhere warm to return to. Pumpkin accents follow this station.'),button('Tune Ghost Tide FM',tuneGhost),button('Radio off',()=>{radioOff();panel.close();}),button('Volume · '+Math.round(radioVolume*100)+'%',()=>{radioVolume=radioVolume===.3?.6:radioVolume===.6?1:.3;if(radioContext)radioBus.gain.setTargetAtTime(radioVolume,radioContext.currentTime,.2);radioSave();radioMenu();}),el('p','Ferry sounds are independent: a gentle engine, wake, departure horn, mooring bell and weather ambience.'),button('Harbour sounds · '+(fxOn?(ferryAudio?'On':'On · Tap to listen'):'Off'),toggleFx),button('Effects volume · '+Math.round(fxVolume*100)+'%',()=>{fxVolume=fxVolume===.3?.6:fxVolume===.6?1:.3;if(ferryAudio)ferryAudio.enable(fxOn,fxVolume);fxSave();radioMenu();})]);}
function el(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function button(text,fn,disabled,primary){const n=el('button',text,primary?'primary':'');n.type='button';n.disabled=!!disabled;n.addEventListener('click',fn);return n;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){if(storageOK){storageOK=false;toast('This voyage can’t autosave here. Keep this tab open to continue.');}}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4500);}
function formatClock(){return M.time(state.clock);}
function objective(){const rows=M.stories(state),active=rows.find(r=>r.id===state.track&&!r.done)||rows.find(r=>!r.done);return active?active.title+' · '+active.text:'Explore the Basin · New voyages, cargo and neighbours await. Journal lists the quays.';}
function hud(){$('passenger-portrait').hidden=!state.flags.naoAboard;const destination=state.voyage&&state.voyage.to,preview=destination&&M.routePreview(state,destination);$('route-status').textContent=!state.docked&&preview?preview.to+' · ETA about '+M.time(preview.arrival)+' · '+preview.minutes+' min · '+preview.fuel.toFixed(1)+' fuel'+(preview.enough?'':' · Refuel needed'):!state.docked?'Free sailing · Choose a quay for an arrival and fuel estimate.':'';$('route-status').hidden=!!state.docked;const discovery=M.nearDiscovery(state);$('explore-button').hidden=!discovery;$('explore-button').textContent=discovery?'Explore · '+P.encounter(state,discovery.id).title:'Explore nearby';$('moment-button').hidden=!!state.docked||state.ended||!state.voyage||state.voyage.distance<120;const held=Gold.lots.total(state.gold);$('resources').textContent=formatClock()+' · '+Math.round(state.credits)+' cr · '+held.toFixed(0)+' g gold · Fuel '+state.fuel.toFixed(1)+'/6 · Cargo '+M.held(state)+'/'+M.capacity(state)+' · '+({rain:'Light rain',clear:'Clear spell',mist:'Sea mist'}[M.weather(state).name]);$('objective').textContent=objective();const near=M.nearby(state);$('dock-button').disabled=!near||!!state.docked||state.ended;$('dock-button').textContent=near?'Dock · '+near.name:'Dock · Approach a quay';$('find-button').hidden=!!state.docked||state.flags.salvage||Math.hypot(state.ship.x-W.salvage.x,state.ship.y-W.salvage.y)>65;$('pause-button').textContent=paused?'Resume':'Pause';document.body.classList.toggle('docked',!!state.docked);$('port').hidden=!state.docked||state.ended;}
function quote(){return Gold.quote(P.economy,state.truth,state.seed,state.docked,state.clock,state.trades);}
function trade(kind,n){if(M.trade(state,kind,n)){save();portContent();hud();const t=state.trades[state.trades.length-1];toast(kind==='sell'?'Received '+t.total+' cr · Realised '+Math.round(t.total-t.basis)+' cr before fuel.':'Bought '+n+' g · Paid '+t.total+' cr.');}else toast('Check your purse, gold and the dealer’s remaining allowance.');}
function act(id){if(!M.action(state,id)){toast('That action is not available now. Check the cost or delivery deadline.');return false;}path=[];save();hud();if(state.ended){finish();return true;}if(state.docked)renderPort();return true;}
function cargoAction(fn){if(fn()){save();hud();portContent();}else toast('That cargo action is not available now.');}
function doFreight(id,deliver){if(M.freight(state,id,deliver)){save();hud();portContent();toast(deliver?'Cargo delivered. Payment recorded.':'Case aboard. Check the return fuel and deadline.');}else toast('Check the cargo space, purse, destination and deadline.');}
function showPerson(id,text){person=id;speech=text===undefined?M.chat(state,id):text;save();portContent();}
function portContent(){const body=$('port-content');body.replaceChildren();if(!state.docked)return;const port=W.ports.find(p=>p.id===state.docked);$('port-title').textContent=port.name;$('port-subtitle').textContent=port.subtitle;document.querySelectorAll('[data-tab]').forEach(n=>n.setAttribute('aria-pressed',n.dataset.tab===tab?'true':'false'));
if(person){const c=P.characters[person],head=el('div',undefined,'dialogue-head'),img=el('img');img.src=c.portrait;img.alt=c.name;head.append(img);const labels=el('div');labels.append(el('h2',c.name),el('p',c.role));head.append(labels);body.append(head,el('p','“'+speech+'”','speech'));const actions=el('div',undefined,'actions');actions.append(button('Keep chatting',()=>showPerson(person)));
 if(person==='mei'&&!state.flags.teaAccepted)actions.append(button('Collect Nao’s tea · Free · 5 min',()=>{if(act('accept-tea'))showPerson('mei','One sealed case for Nao, twenty-four credits when it arrives. Start the handover by 03:40. Fuel is yours to budget. Bring yourself back as carefully as the tea.');},state.clock+5>P.tea.deadline,true));
 if(person==='nao'&&state.flags.teaAccepted&&!state.flags.teaDelivered)actions.append(button('Deliver Mei’s tea · Receive 24 cr · 5 min',()=>{if(act('deliver-tea'))showPerson('nao','There it is! Mei’s seal, dry paper, everything safe. Here are your twenty-four credits. Stay for a bun if you have a little time.');},state.clock>P.tea.deadline,true));
 if(person==='rin'&&!state.flags.lampAccepted)actions.append(button('Collect Aki’s lighthouse kit · Free · 5 min',()=>{if(act('lamp-collect'))showPerson('rin','One kit for Aki on Hoshimi. Forty credits on delivery; start the five-minute handover by 05:00. Check your return fuel; the yard and Kisaragi have pumps.');},M.held(state)>=M.capacity(state)||state.clock+5>P.lamp.deadline,true));
 if(person==='rin'&&!state.flags.pump)actions.append(button('Help repair Second Helping · Free · 10 min',()=>{if(act('repair-pump')&&!state.ended)showPerson('rin','Hold the light. One cleaned valve, one tightened seal… there! Listen to that calm hum. She’ll carry the day crew home.');}));
 if(person==='aki'&&state.flags.lampAccepted&&!state.flags.lampDelivered)actions.append(button('Deliver lighthouse kit · Receive 40 cr · 5 min',()=>{if(act('lamp-deliver'))showPerson('aki','Seal intact. Forty credits, as promised. Your crossing has become part of the light that will guide the next ferry.');},state.clock>P.lamp.deadline,true));
 if(person==='nao'&&state.docked==='market'&&state.flags.naoReturned&&!state.flags.naoAboard)actions.append(button('Invite Nao on another little voyage · Free · 5 min',()=>{if(act('nao-outing')&&!state.ended)showPerson('nao','Another crossing? Let me put a lid on the kettle. We can choose a view, then come home to the counter.');},false,true));
 if(person==='nao'&&state.docked==='market'&&state.flags.teaDelivered&&!state.flags.naoInvited)actions.append(button('Invite Nao to Kisaragi’s preview supper · Free · 5 min',()=>{if(act('nao-invite')&&!state.ended)showPerson('nao','Hana promised one little table, not a whole new life. Let me prepare a sample. I’d like to make this voyage with you.');},false,true));
 if(['nao','hana'].includes(person)&&state.docked==='canal'&&state.flags.naoAboard&&!state.flags.naoPreview)actions.append(button('Join Nao’s preview supper · Free · 10 min',()=>{if(act('nao-preview')&&!state.ended)showPerson('nao','I put my recipe by the pot and nobody asked me to make the table bigger. I think that was my favourite part. Thank you for bringing me.');},false,true));
 if(person==='nao'&&state.docked==='market'&&state.flags.naoPreview&&state.flags.naoAboard)actions.append(button('Bring Nao back to her counter',()=>{if(act('nao-return'))showPerson('nao','Home again. The invitation is mine, and I can choose a little evening. I’ll keep that crossing for the next busy morning.');},false,true));
 if(person==='mio'&&state.flags.observatorySupplied&&!state.flags.skySeen)actions.append(button('Watch the outer-bay sky · Free · 12 min',()=>{if(act('sky-watch')&&!state.ended)showPerson('mio','There is the little cluster above the bay. When clouds soften it, our saved exposures show what the lens sees. You carried the connection that let us share it.');},false,true));
 if(['mio','nao'].includes(person)&&state.docked==='observatory'&&state.flags.skySeen&&state.flags.naoAboard&&!state.flags.naoSkySeen)actions.append(button('Share the sky watch with Nao · Free · 6 min',()=>{if(act('share-sky')&&!state.ended)showPerson('nao','Those saved exposures make the cloudy parts worth waiting through. I’m glad we brought a little more time this visit.');},false,true));
 if(person==='nao'&&state.flags.naoSkySeen&&!state.flags.constellationAccepted)actions.append(button('Plan a constellation supper · Free',()=>{if(act('constellation-start'))showPerson('nao','Jun’s roasted tea, Mei’s ginger biscuits, and Mio’s star chart. Two small packets in a recipe basket; ten credits in all. Shall we make a table beyond the city lights?');},false,true));
 if(state.flags.constellationAccepted&&!state.flags.constellationDone){if(person==='jun'&&!state.flags.constellationTea)actions.append(button('Collect supper tea · 6 cr · 5 min',()=>{if(act('constellation-tea')&&!state.ended)showPerson('jun','Roasted tea, sealed against the spray. Tell Mio the first cup is for the view.');},state.credits<6,true));if(person==='mei'&&!state.flags.constellationGinger)actions.append(button('Collect ginger biscuits · 4 cr · 5 min',()=>{if(act('constellation-ginger')&&!state.ended)showPerson('mei','A small packet, not a freight case. You have enough business in that hold already. Enjoy your little table.');},state.credits<4,true));if(['mio','nao'].includes(person)&&state.docked==='observatory'&&state.flags.naoAboard&&state.flags.constellationTea&&state.flags.constellationGinger)actions.append(button('Share the constellation supper · Free · 12 min',()=>{if(act('constellation-supper')&&!state.ended)showPerson('nao','Mio folds the sky map between three warm cups. “That one is the Swan,” she says. I name our biscuits the Little Ferry. For a while, nobody needs to be anywhere else.');},false,true));}
 const breakfast=state.clock>=1740&&P.breakfast[state.docked];if(breakfast&&person===breakfast.who)actions.append(button(breakfast.name+' · 4 cr · 8 min',()=>{if(act('breakfast')&&!state.ended)showPerson(breakfast.who,breakfast.text);},state.credits<4,true));
 const meal=P.meals[state.docked];if(meal&&meal.who===person)actions.append(button(meal.name+' · '+meal.price+' cr · '+meal.minutes+' min',()=>{const id=person;if(act('meal')&&!state.ended)showPerson(id,meal.text);},state.credits<meal.price));
 actions.append(button('Back to people',()=>{person=null;portContent();}));body.append(actions);return;}
if(tab==='people'){body.append(button('Plan your next destination',destinationList));body.append(button('Read the harbour board',harbourBoard));body.append(el('p',port.arrival,'muted'));M.people(state).forEach(id=>{const c=P.characters[id],n=button('',()=>showPerson(id));n.className='person';const img=el('img');img.src=c.portrait;img.alt='';const label=el('span');label.append(el('strong',c.name),el('small',c.role));n.append(img,label);body.append(n);});if(state.docked==='bar'&&!state.flags.teaAccepted)body.append(el('p','Mei has a small courier job. Talk to her to collect the case.','cargo-card'));if(state.docked==='market'&&state.flags.teaAccepted&&!state.flags.teaDelivered)body.append(el('p','Your tea case is aboard. Speak to Nao to complete the delivery.','cargo-card'));}
else if(tab==='market'){P.marketNews(state,state.docked).forEach(n=>body.append(el('p',M.time(n.at)+' · '+n.title+' · '+n.text,'cargo-card')));const last=state.trades.filter(t=>t.kind==='sell').slice(-1)[0];if(last)body.append(el('p','Latest gold sale: '+last.total+' cr received · '+(Number.isFinite(last.basis)?Math.round(last.basis)+' cr purchase basis · '+Math.round(last.total-last.basis)+' cr realised before fuel.':'Purchase basis unavailable in this older record.'),'cargo-card'));body.append(button('Local trading talk',()=>{P.signals.filter(r=>r.where===state.docked&&r.at<=state.clock).forEach(r=>M.hear(state,r.id));save();tradingTalk();}));M.observe(state);const q=quote();body.append(el('h2',q.dealer.name),el('p','Observed '+formatClock()+'. Trading pauses the clock.','muted'));const grid=el('div',undefined,'quote-grid');[['You pay to buy',q.buy],['You receive selling',q.sell]].forEach(([label,value])=>{const box=el('div');box.append(el('small',label),el('strong',value+' cr/g'));grid.append(box);});body.append(grid);const controls=el('div',undefined,'trade-controls');[1,3].forEach(n=>{controls.append(button('Buy '+n+' g',()=>trade('buy',n),state.credits<n*q.buy||q.canBuy<n));controls.append(button('Sell '+n+' g',()=>trade('sell',n),Gold.lots.total(state.gold)<n||q.canSell<n));});body.append(controls,el('p','Remaining tray: '+q.canBuy+' g · Buyer allowance: '+(Number.isFinite(q.canSell)?q.canSell+' g':'open'),'muted'),el('p','Your gold: '+Gold.lots.total(state.gold)+' g · Average purchase '+Math.round(Gold.lots.average(state.gold)||0)+' cr/g. Fuel and the spread affect your margin.','muted'));}
else if(tab==='cargo'){
 body.append(el('h2','Small cargo · Clear promises'),el('p','Shared hold: '+M.held(state)+' / '+M.capacity(state)+' cases. Purchases and handovers take five minutes. Fuel costs extra.','muted'));
 let count=0;Object.entries(P.freight).forEach(([id,d])=>{const c=(state.cargo||{})[id];if(state.docked!==d.from&&state.docked!==d.to&&!(c&&c.units&&state.clock>d.deadline))return;count++;const card=el('div',undefined,'cargo-card');card.append(el('h3',d.title),el('p','Purchase '+d.cost+' cr · Promised payment '+d.payment+' cr · Gross margin '+(d.payment-d.cost)+' cr before fuel.'),el('p','Collect at '+W.ports.find(p=>p.id===d.from).name+' → '+W.ports.find(p=>p.id===d.to).name+' · Start handover by '+M.time(d.deadline)+'.','muted'));
 const estimate=M.estimate(state,d);card.append(el('p','Outbound estimate: '+estimate.minutes+' min sailing + 5 min handover · '+estimate.fuel.toFixed(1)+' fuel (about '+Math.ceil(estimate.fuel*5)+' cr at a full-tank rate). Turns, collection, detours and return travel are extra.','muted'));if(d.opens)card.append(el('p','Desk release: '+M.time(d.opens)+'.','muted'));
 if(c&&!c.units)card.append(el('p',c.released?'Unloaded after deadline · No payment or refund.':'Delivered · '+c.revenue+' cr received.'));else if(c)card.append(el('p','Aboard · '+(state.clock>d.deadline?'Delivery window closed.':Math.floor(d.deadline-state.clock)+' minutes remaining.')));
 if(state.docked===d.from&&!c)card.append(button('Buy sealed case · '+d.cost+' cr · 5 min',()=>doFreight(id,false),state.clock<(d.opens||1420)||state.credits<d.cost||M.held(state)>=M.capacity(state)||state.clock+5>d.deadline,true));
 if(state.docked===d.to&&c&&c.units)card.append(button('Deliver · Receive '+d.payment+' cr · 5 min',()=>doFreight(id,true),state.clock>d.deadline,true));if(state.docked===d.from&&!c&&d.opens&&state.clock<d.opens)card.append(button('Wait for desk release · '+Math.ceil(d.opens-state.clock)+' min',()=>cargoAction(()=>M.waitFreight(state,id))));if(c&&c.units&&state.clock>d.deadline)card.append(button('Unload expired case · No refund',()=>cargoAction(()=>M.release(state,id))));body.append(card);});
 if(!count)body.append(el('p','Buyer requests: blue bowls from Kisaragi to Mei; pump seals from the yard to Frostline; regulators from Metro to Kenji after 00:50; jasmine starter from Frostline to Hana after 02:00. Courier work is offered through People.'));
}
else{body.append(el('h2','Keep the Tern ready'));if(['landing','yard','canal','observatory'].includes(state.docked)){body.append(el('p','Fill the tank to 6 · 30 cr · 10 minutes.'));body.append(button('Refuel',()=>act('fuel'),state.fuel>=5.99||state.credits<30,true));}else if(state.docked==='market'){body.append(el('p','Kenji’s engine tuning · 80 cr · 15 minutes. Sail 15% faster and use 20% less fuel per distance.'));body.append(button(state.flags.engine?'Engine tuned':'Tune the engine',()=>act('engine'),!!state.flags.engine||state.credits<80,true));body.append(el('p','Cargo racks · 65 cr · 10 minutes. Increase the shared hold from two cases to three.'));body.append(button(state.flags.hold?'Cargo racks fitted':'Fit cargo racks',()=>act('hold'),!!state.flags.hold||state.credits<65));}else body.append(el('p','Fuel is at Landing 3, Starling Yard, Kisaragi and Tsukimi. Kenji handles upgrades at the Night Market.'));
 body.append(el('p','Finish at any port. Your report separates gold trading, cargo, courier work and salvage.','muted'),button('Finish this voyage',()=>{state.ended=true;save();finish();}));}}
function renderPort(){person=null;portContent();}
function depart(){if(!M.depart(state))return;if(fxOn&&ferryAudio)ferryAudio.cue('depart');paused=false;person=null;keys.clear();path=[];hud();save();canvas.focus();toast('Cast off. WASD or arrows steer; Set course assists.');}
function dock(){if(M.dock(state)){if(fxOn&&ferryAudio)ferryAudio.cue('moor');keys.clear();path=[];tab='people';renderPort();hud();save();$('depart-button').focus();}else toast('Sail inside a quay’s dotted mooring ring, then Dock.');}
function openPanel(title,nodes,closeLabel){keys.clear();state.ship.speed=0;const content=$('panel-content');content.replaceChildren(el('h2',title),...nodes);$('panel-close').textContent=closeLabel||'Close';if(!panel.open)panel.showModal();}
function discoveryPanel(){const d=M.nearDiscovery(state);if(!d)return;const text=P.encounter(state,d.id);openPanel(text.title,[el('p',text.intro),...text.choices.map(c=>button(c.label,()=>{if(M.discover(state,d.id,c.id)){path=[];save();hud();if(state.ended){finish();return;}openPanel(text.title,[el('p',c.result)]);}else toast('Check your distance, fuel and whether this discovery is already settled.');},state.fuel<(c.fuel||0)))]);}
function tradingTalk(){const rows=M.rumourRows(state),nodes=[el('p','Outlooks are uncertain. Contract payments are fixed. Read a fresh gold board before trading; fuel and the spread still cost money.')];if(!rows.length)nodes.push(el('p','Speak to neighbours or read the harbour board to hear trading talk.'));rows.forEach(r=>{const item=el('article',undefined,'journal-card');item.append(el('h3',r.title),el('p',P.characters[r.who].name+' · '+r.kind+' · Posted '+M.time(r.at)+' · Heard '+M.time(r.heard)+' · '+r.age+' min ago','muted'),el('p',r.text));nodes.push(item);});openPanel('Trading talk · Notes, not promises',nodes);}
function harbourBoard(){P.signals.filter(r=>r.at<=state.clock).forEach(r=>M.hear(state,r.id));save();const nodes=[el('p','Messages from the quays. Reading is free and pauses the crossing.'),button('Remembered trading talk',tradingTalk)];P.board(state).filter(p=>p.at<=state.clock).forEach(p=>{const item=el('article',undefined,'board-post');item.append(el('small',P.characters[p.who].name+' · Board checked '+formatClock()),el('h3',p.title));if(p.contract){const d=P.freight[p.contract],c=state.cargo[p.contract];item.append(el('p',c&&!c.units?p.text:state.clock>d.deadline?'Delivery window closed. This request is kept as a harbour record.':'Buy '+d.cost+' cr · Payment '+d.payment+' cr · '+W.ports.find(q=>q.id===d.from).name+' → '+W.ports.find(q=>q.id===d.to).name+' · Release '+M.time(d.opens||1420)+' · Start handover by '+M.time(d.deadline)));}else item.append(el('p',p.text));nodes.push(item);});openPanel('The harbour board',nodes);}
function destinationList(){openPanel('Where shall the Tern go?',[el('p','Preview neighbours, work and fuel before committing. Reading is free.'),...W.ports.map(p=>button(p.name,()=>destinationPreview(p.id)))]);}
function destinationPreview(id){const d=M.destinationInfo(state,id);if(!d)return;const nodes=[el('p','People · '+d.people.join(', ')),el('p',d.fuel?'Fuel pump · 30 cr · 10 min · Fills tank to 6.':'No fuel pump here.'),el('p','Estimated '+d.route.minutes+' min sailing · '+d.route.fuel.toFixed(1)+' fuel · Arrival about '+M.time(d.arrival)+(d.route.fuel>state.fuel?' · Refuel before committing.':'')+' Turns and stops need extra allowance.'+(d.arrival>=1800?' This estimate reaches or passes the 06:00 end of the voyage.':''),'muted'),el('h3','Available work'),...d.jobs.map(text=>el('p',text)),el('h3','Your active stories'),...d.steps.map(text=>el('p',text))];if(!d.jobs.length)nodes.push(el('p','No new cargo request here right now.'));if(!d.steps.length)nodes.push(el('p','No tracked story needs this quay right now.'));if(d.breakfast)nodes.push(el('p',d.breakfast));if(!state.ended&&state.docked!==id)nodes.push(button(state.docked?'Cast off & set course':'Set course',()=>{panel.close();if(state.docked)depart();course(id);},false,true));nodes.push(button('Other destinations',destinationList));openPanel(d.name+' · Before you sail',nodes);}
function routePlanner(){const card=el('div',undefined,'journal-card');card.append(el('h3','Cargo route planner'),el('p','Tank '+state.fuel.toFixed(1)+' / 6 · Hold '+M.held(state)+' / '+M.capacity(state)+'. Estimates exclude turns, detours and refuelling. Return estimates lead to Kurage 33.','muted'));
 const aboard=M.collected(state);if(!aboard.length)card.append(el('p','No cases aboard. Compare buyer requests below before purchasing.'));aboard.forEach(c=>{const to=W.ports.find(p=>p.id===c.to),r=M.routeStats(state,state.ship,to),row=el('div',undefined,'story-row');row.append(el('strong',c.title+' → '+to.name),el('p','Paid '+c.cost+' cr · Promised '+c.payment+' cr · '+(state.clock>c.deadline?'Delivery window closed':Math.floor(c.deadline-state.clock)+' min remaining to '+M.time(c.deadline)), 'muted'),el('p','From here: about '+r.minutes+' min sailing + 5 min handover · '+r.fuel.toFixed(1)+' fuel. '+(r.fuel>state.fuel?'Refuel before this route.':''),'muted'),button(state.track===c.id?'Tracking':'Track this delivery',()=>{state.track=c.id;save();hud();journal();}));card.append(row);});
 const offers=Object.entries(P.freight).filter(([id])=>!state.cargo[id]);if(!offers.length)return card;card.append(el('h3','Compare two orders'));for(let i=0;i<2;i++){const label=el('label','Order '+(i+1)+' '),select=el('select'),empty=el('option','Choose an order');empty.value='';select.append(empty);offers.forEach(([id,d])=>{const option=el('option',d.title);option.value=id;select.append(option);});select.value=compareOrders[i]||'';select.addEventListener('change',()=>{compareOrders[i]=select.value;journal();});label.append(select);card.append(label);}
 const chosen=[...new Set(compareOrders.filter(id=>offers.some(([key])=>key===id)))];if(chosen.length){const wrap=el('div',undefined,'planner-scroll'),table=el('table'),head=el('tr');['Order','Buy / payment','Fuel to deliver / return','Start handover / deadline'].forEach(t=>head.append(el('th',t)));table.append(head);chosen.forEach(id=>{const p=M.plan(state,id),row=el('tr');[P.freight[id].title,p.cost+' / '+p.payment+' cr',p.fuel.toFixed(1)+' / '+p.returnFuel.toFixed(1),M.time(p.handoverAt)+' / '+M.time(p.deadline)+(p.onTime?'':' · Late estimate')].forEach(t=>row.append(el('td',t)));table.append(row);card.append(el('p',P.freight[id].title+': '+(p.payment-p.cost)+' cr gross margin; about '+Math.ceil((p.fuel+p.returnFuel)*5)+' cr fuel at full-tank rate. '+(p.fuel>state.fuel?'Refuel on the way. ':'')+(p.wait?'Includes '+Math.ceil(p.wait)+' min waiting for release.':''),'muted'));});wrap.append(table);card.append(wrap);}return card;}
function journal(){const nodes=[el('p',objective()),button('Harbour board',harbourBoard),button('Remembered trading talk',tradingTalk),routePlanner()];const orders=el('div',undefined,'journal-card');orders.append(el('h3','Buyer requests'));Object.entries(P.freight).filter(([id])=>!state.cargo[id]).forEach(([id,d])=>orders.append(el('p',d.title+' · '+W.ports.find(p=>p.id===d.from).name+' → '+W.ports.find(p=>p.id===d.to).name+' · Buy '+d.cost+' / payment '+d.payment+' cr · '+(d.opens?'Opens '+M.time(d.opens)+' · ':'')+'By '+M.time(d.deadline),'muted')));nodes.push(orders);
 const stories=el('div',undefined,'journal-card');stories.append(el('h3','Active stories & outcomes'));M.stories(state).forEach(row=>{const item=el('div',undefined,'story-row');item.append(el('strong',(row.done?'Completed · ':'')+row.title),el('p',row.text,'muted'));if(!row.done)item.append(button(state.track===row.id?'Tracking':'Track this story',()=>{state.track=row.id;save();hud();journal();}));stories.append(item);});if(!M.stories(state).length)stories.append(el('p','Mei has tea for Nao; Rin has lighthouse work. Visit the counters to begin.'));nodes.push(stories);
 const quays=el('div',undefined,'journal-card');quays.append(el('h3','Basin chart'));W.ports.forEach(p=>{quays.append(button(p.name+(state.visits[p.id]?' · Visited':' · New quay'),()=>{destinationPreview(p.id);}));});quays.append(el('p','Preview a quay, then cast off and set a course. Fuel pumps: Landing 3, Starling Yard, Kisaragi, Tsukimi.','muted'));nodes.push(quays);const cargo=el('div',undefined,'journal-card');cargo.append(el('h3','Cargo & stories'),el('p',state.flags.teaDelivered?'Mei’s tea delivered · 24 cr received.':state.flags.teaAccepted?'One sealed tea case · Cost 0 cr · Nao pays 24 cr at Lantern Market · '+(state.clock>P.tea.deadline?'Delivery window closed.':Math.floor(P.tea.deadline-state.clock)+' minutes to start the five-minute handover.'):'Shared hold: '+M.held(state)+' / '+M.capacity(state)+' cases. Talk to Mei for a first delivery.'),el('p',state.flags.salvage?'Signal-light kit recovered · 36 cr salvage.':'A lantern has been reported in the western reeds. Approach slowly to investigate.'));nodes.push(cargo);const boards=el('div',undefined,'journal-card');boards.append(el('h3','Remembered gold boards'));Object.entries(state.quotes).forEach(([id,q])=>boards.append(el('p',W.ports.find(p=>p.id===id).name+' · '+M.time(q.at)+' · Buy '+q.buy+' / Sell '+q.sell+' cr/g')));boards.append(el('p','Remembered quotes can be old. Read the current scale before trading.','muted'));nodes.push(boards);const log=el('div',undefined,'journal-card');log.append(el('h3','Voyage log'));state.log.slice(0,12).forEach(line=>log.append(el('p',line,'muted')));nodes.push(log);openPanel('Captain’s journal',nodes);}
function help(){openPanel('Welcome aboard the Tern',[el('p','Voyage 0.6 opens the outer bay and Tsukimi Observatory, with nine quays across the Basin. Meet familiar neighbours, trade gold and cargo, help Rin keep the lighthouse turning, or take Nao to Kisaragi. Classic remains available separately. Read the harbour board through People or the Journal; after a shared sky watch, Nao has a new supper idea.'),el('p','WASD or arrow keys steer. On a phone, hold the direction buttons. Click open water or choose Set course for assisted sailing. Steering manually cancels an assisted course.'),el('p','Approach the dotted ring around a port and press Dock or E. Visit People, Market, Cargo or Services. Time moves while sailing and during labelled activities; reading, conversations and menus pause it.'),el('p','Start by speaking to Mei. Take her tea to Nao at the Night Market. Fuel is sold at Landing 3, Starling Yard, Kisaragi and Tsukimi. The harbour tug can recover a stranded ferry. J opens your journal; P pauses sailing. Choose a quay to see estimated arrival and fuel; View switches between close and wide. Radio (R) offers Ghost Tide FM, a mellow Halloween station with pumpkin accents.'),el('p',loadNotice||'Your voyage autosaves separately from Classic. The Journal has a Basin chart and tracked stories. This stage builds on your existing Voyage save.')],'Start exploring');}
function finish(){path=[];keys.clear();state.ship.speed=0;const report=M.realised(state),sold=report.total;openPanel(state.clock>=1800?'The morning harbour wire':'A little light brought home',[el('p',state.clock>=1800?'Daylight reaches the Basin. The Tern rests where your night ended; these messages find you over the harbour wire.':'The Tern rests. Thank you for making a little room for the harbour.'),...P.endMessages(state).map(m=>{const card=el('article',undefined,'board-post');card.append(el('h3',P.characters[m.who].name),el('p',m.text));return card;}),el('p','Recorded fuel purchases: '+state.expenses.fuel+' cr · Tug recovery: '+state.expenses.recovery+' cr.'+(state.expenses.complete?'':' Recorded since '+M.time(state.expenses.since)+'; earlier expenses in this older save are unavailable.')),el('p','Gold results exclude fuel, food and upgrades.'+(report.unknown?' '+report.unknown+' older sale(s) lack purchase basis and are excluded.':''),'muted'),el('p','Purse '+state.credits+' cr · Gold '+Gold.lots.total(state.gold)+' g · Realised gold result '+Math.round(sold)+' cr.'),el('p','Tea delivery: '+(state.flags.teaDelivered?'24 cr received':'not completed')+' · Salvage: '+(state.flags.salvage?'36 cr recovered':'not recovered')+'.'),el('p','Lighthouse courier: '+(state.flags.lampDelivered?'40 cr received':'not completed')+' · Stock cargo: '+Object.values(state.cargo||{}).reduce((n,c)=>n+c.revenue-c.cost,0)+' cr net before fuel.'),el('p','Discoveries settled: '+Object.keys(state.finds).length+' · Payments: '+Object.entries(state.finds).reduce((sum,[id,choice])=>sum+P.discoveryText[id].choices.find(c=>c.id===choice).payment,0)+' cr · Observatory: '+(state.flags.skySeen?'sky watched':state.flags.observatorySupplied?'kit delivered':'not yet supplied')+'.'),el('p','Nao’s preview supper: '+(state.flags.naoAboard&&state.flags.naoPreview?'shared; Nao still aboard':state.flags.naoReturned?'shared, and Nao brought home':state.flags.naoPreview?'shared':'not yet shared')+'.'),button('Continue this voyage',()=>{state.ended=false;panel.close();renderPort();hud();save();},state.clock>=1800),el('p','Useful feedback: Was steering comfortable? Were the ports easy to find? Did People / Market / Cargo / Services feel clear?'),button('Start a fresh voyage',()=>{if(!confirm('Replace this Voyage save? Classic is unaffected.'))return;state=M.create('lantern-'+Date.now().toString(36));M.observe(state);paused=false;tab='people';panel.close();renderPort();hud();save();}),button('Return to game selection',()=>location.href='../index.html')]);}
function course(id){if(state.docked){destinationPreview(id);return;}if(state.ended||panel.open)return;const port=W.ports.find(p=>p.id===id);if(!port)return;path=N.route(state.ship,port);if(path.length){M.destination(state,id);save();}if(path.length)toast('Assisted course to '+port.name+'. Dock when you arrive; steer to take control.');else toast('No safe course from here. Try nearby open water.');}
// One coherent top-down map. Portraits live only in dock conversations.
let width=0,height=0;const TAU=Math.PI*2;
function rounded(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke();}}
function line(x1,y1,x2,y2,color,size){ctx.strokeStyle=color;ctx.lineWidth=size||1;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}
function light(x,y,r,color){const g=ctx.createRadialGradient(x,y,1,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill();}
function roof(x,y,w,h,color){rounded(x+7,y+9,w,h,3,'#06182088');rounded(x,y,w,h,4,color,'#778780');
 for(let yy=10;yy<h;yy+=12)line(x+3,y+yy,x+w-3,y+yy,'#1c333c22',1);
 for(let xx=10;xx<w;xx+=13)line(x+xx,y+3,x+xx,y+h-3,'#aec1b31f',1);
 line(x+w/2,y+1,x+w/2,y+h-1,'#d1c1a988',3);line(x,y+h,x+w,y+h,'#23383a',4);
 for(let i=12;i<w;i+=25){ctx.fillStyle='#ecc386';ctx.fillRect(x+i,y+h-2,9,4);light(x+i+4,y+h+5,22,'#e5b26c22');}
 if(w>100){rounded(x+14,y+14,21,28,2,'#374e58','#8a9c99');line(x+18,y+17,x+30,y+37,'#b9c7bc44',2);rounded(x+w-31,y+15,15,20,2,'#485551','#92a497');ctx.fillStyle='#203940';ctx.fillRect(x+w-28,y+19,9,10);}
}
function crate(x,y,w){rounded(x,y,w,w,2,'#94765a','#b9a47b');line(x+3,y+4,x+w-3,y+w-4,'#5e5545',2);line(x+3,y+w-4,x+w-3,y+4,'#5e5545',2);}
function tree(x,y,r){ctx.fillStyle='#0c282b77';ctx.beginPath();ctx.ellipse(x+4,y+5,r+2,r,0,0,TAU);ctx.fill();ctx.fillStyle='#667d64';ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill();ctx.fillStyle='#89a17b55';ctx.beginPath();ctx.arc(x-3,y-3,r*.58,0,TAU);ctx.fill();}
// Small, readable silhouettes and distinct working waterfronts.
function neighbour(x,y,coat,phase){ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(phase+x)*.045);ctx.fillStyle='#071f2780';ctx.beginPath();ctx.ellipse(3,5,7,10,0,0,TAU);ctx.fill();rounded(-5,-3,10,13,3,coat);ctx.fillStyle='#d2b69c';ctx.beginPath();ctx.arc(0,-5,4,0,TAU);ctx.fill();line(-3,10,-3,15,'#182e37',2);line(3,10,3,15,'#182e37',2);ctx.restore();}
function sign(x,y,label,ink){ctx.font='600 11px system-ui';const w=ctx.measureText(label).width;rounded(x-w/2-8,y-14,w+16,22,3,'#122d35','#6f8175');ctx.fillStyle=ink;ctx.textAlign='center';ctx.fillText(label,x,y+1);}
function ropeCoil(x,y){ctx.strokeStyle='#b5a180';ctx.lineWidth=1;for(let r=2;r<=6;r+=2){ctx.beginPath();ctx.ellipse(x,y,r,r*.65,0,0,TAU);ctx.stroke();}line(x+6,y,x+11,y+4,'#b5a180',1);}
function lifeRing(x,y){ctx.strokeStyle='#c48b69';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,5,0,TAU);ctx.stroke();line(x-5,y,x-3,y,'#eee0b7',2);line(x+3,y,x+5,y,'#eee0b7',2);}
function vessel(x,y,angle,color,kind,scale){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.scale(scale||1,scale||1);
 ctx.fillStyle='#051e2780';ctx.beginPath();ctx.ellipse(2,3,29,12,0,0,TAU);ctx.fill();ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(29,0);ctx.quadraticCurveTo(12,-13,-24,-9);ctx.lineTo(-27,0);ctx.lineTo(-24,9);ctx.quadraticCurveTo(12,13,29,0);ctx.fill();
 line(-20,-8,14,-8,'#c6c2a777',1);line(-20,8,14,8,'#c6c2a777',1);line(15,-7,23,0,'#c6c2a777',1);line(15,7,23,0,'#c6c2a777',1);
 rounded(-10,-6,20,12,2,'#355563','#829e9d');rounded(4,-5,5,10,1,'#b3c6b9');line(-3,-5,-3,5,'#adc2bb',1);line(-17,-5,-17,5,'#8e9b8c',1);
 ctx.fillStyle='#152b30';for(const y of [-10,10]){ctx.beginPath();ctx.ellipse(-14,y,3,2,0,0,TAU);ctx.fill();}
 if(kind==='tug'){rounded(-5,-4,6,8,1,'#d4bd81');ctx.fillStyle='#20303a';ctx.beginPath();ctx.arc(-14,0,4,0,TAU);ctx.fill();line(-15,0,-22,0,'#b4a27e',2);}
 if(kind==='fishing'){line(-17,0,16,0,'#aab4a0',1);line(-9,-6,3,5,'#aab4a0',1);rounded(-23,-5,7,10,1,'#7b8c76');for(let i=0;i<4;i++)line(-22+i*2,-4,-22+i*2,4,'#b0b59466',1);}
 if(kind==='barge'){rounded(-22,-7,13,14,1,'#8b8270');rounded(-7,-7,13,14,1,'#698995');for(let i=-20;i<5;i+=4)line(i,-6,i,6,'#cad0b04a',1);rounded(10,-5,9,10,2,'#bdc0a8');}
 if(kind==='ferry'){rounded(-15,-6,30,12,2,'#718d92');for(let i=-12;i<12;i+=7)rounded(i,-4,4,8,1,'#d9c390');}
 ctx.fillStyle='#c3947a';ctx.fillRect(11,-9,3,2);ctx.fillStyle='#90b89d';ctx.fillRect(11,7,3,2);ctx.restore();}
function skiff(x,y,angle,color){vessel(x,y,angle,color,'fishing',.85);}
function waterfrontDetails(phase){
 // Shore equipment stays outside the captain's mooring circle.
 for(const p of W.ports){const vertical=p.shore.x===p.x;ctx.save();ctx.translate(p.shore.x,p.shore.y);if(!vertical)ctx.rotate(Math.PI/2);if(vertical&&p.shore.y>p.y)ctx.rotate(Math.PI);
 line(-95,-5,95,-5,'#a8afa077',2);for(let i=-90;i<=90;i+=30){if(Math.abs(i)<45)continue;rounded(i-4,-9,8,8,2,'#374b4d','#7c8c80');line(i,-7,i+9,-14,'#b2a48488',1);ctx.strokeStyle='#152a30';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(i,4,4,7,0,0,TAU);ctx.stroke();}
 // Ladder, ring, rope and stacked freight on the landward edge.
 line(69,-4,69,15,'#a7b6ad',2);line(79,-4,79,15,'#a7b6ad',2);for(let y=1;y<=13;y+=5)line(69,y,79,y,'#9fae9f',1);ropeCoil(-65,-18);lifeRing(84,-19);crate(-89,-31,13);rounded(49,-28,12,17,2,'#5f8186','#93aaa2');ctx.restore();
 }
 vessel(137,380,0,'#718d86','tug',1.15);line(120,367,109,322,'#a49b7b66',1);ropeCoil(109,311);
 vessel(153,1017,0,'#839895','ferry',1.2);line(145,1030,145,1060,'#adab8b66',1);
 vessel(2395,571,0,'#627c87','barge',1.4);line(2372,555,2372,520,'#a6b4a166',1);
 vessel(2229,1484,Math.PI/2,'#869587','fishing',1);line(2238,1503,2290,1510,'#b7a28166',1);
 // Worktables, dock carts and drying nets give each quay its own trade.
 rounded(442,295,24,13,2,'#6f867a');line(447,306,447,312,'#24383a',3);line(461,306,461,312,'#24383a',3);ropeCoil(459,287);
 for(let i=0;i<4;i++){line(1545+i*10,315,1545+i*10,328,'#949b7b66',1);line(1545,315+i*4,1575,315+i*4,'#949b7b66',1);}line(1542,313,1579,313,'#afa285',2);
 rounded(1575,897,34,15,2,'#987854');crate(1578,900,10);lifeRing(1651,912);
 rounded(771,1500,13,24,2,'#4f7179','#9eaa94');rounded(771,1540,13,24,2,'#4f7179','#9eaa94');ropeCoil(787,1580);lifeRing(1037,1493);
 rounded(2426,440,37,13,2,'#536f76');for(let i=0;i<3;i++)rounded(2430+i*10,442,7,8,1,'#cad0b1');line(2429,454,2429,461,'#172d33',3);line(2460,454,2460,461,'#172d33',3);
 ropeCoil(2140,1467);lifeRing(2320,1523);rounded(2000,1650,61,6,1,'#a59376');for(let i=0;i<4;i++)line(2007+i*14,1651,2007+i*14,1663,'#7e9181',2);
 rounded(1453,1587,27,14,2,'#847c68');ropeCoil(1500,1589);lifeRing(1392,1560);
}
function ternArt(phase){const s=state.ship;if(state.docked){const p=W.ports.find(p=>p.id===state.docked),vertical=p.shore.x===p.x;for(const d of [-1,1])line(s.x+(vertical?d*9:0),s.y+(vertical?0:d*9),p.shore.x+(vertical?d*20:0),p.shore.y+(vertical?0:d*20),'#c8b48e88',1);}ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.angle);
 if(s.speed>2&&!reduced){const length=16+s.speed*.28;for(const y of [-8,8]){ctx.strokeStyle='#aecfc447';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(-25,y);ctx.quadraticCurveTo(-35,y*1.7,-25-length,y*2.2);ctx.stroke();}for(let i=0;i<3;i++){const x=-30-i*10-(phase*14)%10;line(x,-3-i,x+5,3+i,'#c7ded02e',1);}}
 vessel(0,0,0,'#c5b78f','',1);rounded(-10,-7,23,14,3,'#496d78','#a7b8a7');rounded(6,-5,5,10,1,'#ead1a2');line(-6,-5,-6,5,'#a0b7b0',1);ctx.font='600 6px system-ui';ctx.fillStyle='#ddd8ba';ctx.textAlign='center';ctx.fillText('TERN',-1,2);
 rounded(-15,-4,3,8,1,'#273e48');ropeCoil(20,0);lifeRing(-20,0);line(-3,-9,-3,-15,'#afc0b1',1);line(-5,-15,-1,-15,'#afc0b1',1);
 const cargo=M.held(state);for(let i=0;i<Math.min(cargo,3);i++)rounded(-24+i*4,-5,3,5,1,'#c2a577');
 light(12,-10,9,'#dc8e6e30');light(12,10,9,'#a3c89530');light(24,0,20,'#f0d5a327');
 ctx.restore();
}
function quayDetails(phase,weather){
 // Kurage: orange jellyfish, striped awning, stools, bowls and steam.
 sign(1310,275,'KURAGE 33','#80d4d4');light(1330,294,29,'#f5a96b44');
 rounded(1230,307,185,14,2,'#cb9971');for(let x=1232;x<1412;x+=18)rounded(x,307,8,14,1,'#ead7a6');
 for(let x=1245;x<1400;x+=31){ctx.fillStyle='#bb7758';ctx.beginPath();ctx.arc(x,330,5,0,TAU);ctx.fill();ctx.fillStyle='#ddd8b6';ctx.beginPath();ctx.arc(x,294,3,0,TAU);ctx.fill();}
 for(let i=0;i<3;i++)line(1270+i*16,288,1273+i*16+Math.sin(phase+i)*2,278,'#e7dac432',1);
 neighbour(1290,289,'#797398',phase);neighbour(1373,330,'#496879',phase);skiff(1443,367,0,'#72867c');line(1430,351,1430,334,'#c6b28966',1);
 // Harbour office: queue rails, pump nozzle and clear hatch signage.
 sign(370,242,'BASIN EXCHANGE','#d9c794');rounded(462,260,20,29,3,'#789996','#a8b8a0');line(482,270,489,283,'#20343c',3);line(329,307,422,307,'#b1b9a2',2);neighbour(396,283,'#a6a29b',phase);neighbour(312,307,'#59677e',phase);skiff(261,356,0,'#6f8480');
 // Market counters remain open between the stall roofs.
 for(let i=0;i<4;i++){rounded(1160+i*127,1003,104,13,2,['#bd9367','#7eacb1','#aab786','#9faf83'][i]);for(let j=0;j<4;j++){ctx.fillStyle='#e0c491';ctx.fillRect(1170+i*127+j*20,1006,9,5);}neighbour(1177+i*127,1021,['#456279','#8d7791','#88956e','#b38872'][i],phase);}
 sign(1212,927,'NAO · TEA & BUNS','#e3bf8b');sign(1335,927,'SORA · GOLD','#9cc8d1');neighbour(1255,904,'#8c6d83',phase);neighbour(1473,914,'#a9a080',phase);skiff(1435,850,0,'#7d8980');
 // Metro: a train, shelter benches and the illuminated Line 9 board.
 sign(243,1082,'LINE 9 · HOMEWARD','#cebed5');for(let i=0;i<3;i++){rounded(111+i*91,1241,83,25,3,'#758a94','#b1b7a4');for(let j=0;j<3;j++)rounded(123+i*91+j*19,1245,12,10,1,'#d6cb9b');}
 line(311,1306,402,1306,'#bc9c7b',5);neighbour(326,1300,'#788193',phase);neighbour(381,1107,'#889c9a',phase);
 // Repair yard: slip rails, tool racks, tyre fenders and a crane hook.
 sign(888,1450,'STARLING · REPAIR & REUSE','#b9d5a8');line(820,1585,820,1643,'#899a8c',2);line(990,1585,990,1643,'#899a8c',2);line(1170,1462,1170,1479,'#cfb381',1);ctx.strokeStyle='#cfb381';ctx.beginPath();ctx.arc(1170,1482,4,0,Math.PI);ctx.stroke();
 rounded(1006,1466,22,30,2,'#40554e');for(let i=0;i<3;i++)line(1009,1472+i*8,1023,1472+i*8,'#b6b5a0',2);neighbour(993,1475,'#789d80',phase);neighbour(857,1582,'#b38d71',phase);for(let x=810;x<930;x+=28){ctx.strokeStyle='#162b30';ctx.lineWidth=4;ctx.beginPath();ctx.arc(x,1430,5,0,TAU);ctx.stroke();}
 if(state.flags.pump){skiff(1137,1383,0,'#8f9e87');line(1117,1395,1089,1401,'#b0cab337',1);}
 // Frostline: numbered cold bays and connecting insulated pipework.
 for(let i=0;i<4;i++){rounded(2131+i*59,298,42,20,2,'#273e4b','#98b2b3');sign(2152+i*59,331,'0'+(i+1),'#b2d0cd');line(2152+i*59,342,2152+i*59,365,'#899c9b',4);}
 line(2145,325,2370,325,'#708e98',6);sign(2210,130,'FROSTLINE · COLD CHAIN','#b0d9df');neighbour(2110,433,'#6a869a',phase);neighbour(2390,440,'#9e927d',phase);skiff(2020,566,Math.PI/2,'#6a838c');
 // Canal shops: stepped eaves, tea tables, tiny lanterns and neighbours.
 sign(2064,1315,'JUN · TEA & CLAY','#d8c499');sign(2389,1320,'HANA · SMALL TABLES','#edc7a6');for(let y=1260;y<1620;y+=65){light(2160,y,23,'#e4b77725');ctx.fillStyle='#e0b676';ctx.beginPath();ctx.arc(2160,y,3,0,TAU);ctx.fill();}
 rounded(2026,1475,80,19,3,'#987858');for(let i=0;i<3;i++){ctx.fillStyle='#b3c8ba';ctx.beginPath();ctx.arc(2040+i*21,1482,3,0,TAU);ctx.fill();}neighbour(2110,1450,'#9c8e77',phase);neighbour(2330,1338,'#bc997c',phase);neighbour(2080,1628,'#677e85',phase);skiff(2228,1576,Math.PI/2,'#839185');
 if(state.flags.naoPreview){sign(2066,1508,'NAO’S LITTLE TABLE','#ebc39a');neighbour(2084,1500,'#987a92',phase);}
 // Aki's cottage: path stones, a bench and a keeper by the lens.
 for(let i=0;i<5;i++)rounded(1500+i*10,1510,6,9,2,'#879283');line(1460,1566,1505,1566,'#bba078',4);neighbour(1538,1551,'#9883a7',phase);sign(1450,1460,'HOSHIMI WATCH','#d3c8dc');
 (W.reedBeds||[]).forEach((b,j)=>{for(let i=0;i<13;i++){const x=b.x+(i*19)%58,y=b.y+(i*23)%43;line(x,y,x+Math.sin(phase+i)*2,y-9-i%5,'#8eab7a55',1);}});
 ctx.save();ctx.globalAlpha=weather.mist;(W.fogBanks||[]).forEach((b,i)=>{light(b.x+Math.sin(phase*.3+i)*32,b.y,b.r,'#bfd2cf28');});ctx.restore();
}
function halloweenArt(){for(const p of W.ports){const vertical=p.shore.x===p.x,x=p.shore.x+(vertical?48:22),y=p.shore.y+(vertical?(p.shore.y<p.y?-23:23):48);ctx.save();ctx.translate(x,y);light(0,0,34,'#ef9e4c38');ctx.fillStyle='#bd733c';ctx.beginPath();ctx.ellipse(0,0,9,7,0,0,TAU);ctx.fill();line(0,-7,1,-11,'#8e9c6b',2);for(const x of [-4,4]){ctx.fillStyle='#ffd7a1';ctx.beginPath();ctx.moveTo(x,-3);ctx.lineTo(x-2,0);ctx.lineTo(x+2,0);ctx.closePath();ctx.fill();}line(-4,3,4,3,'#fbd1a0',2);ctx.restore();}}
function dockArt(port){const shore=port.shore,vertical=shore.x===port.x,south=shore.y<port.y;
 if(vertical){rounded(port.x-28,Math.min(shore.y,port.y),56,Math.abs(port.y-shore.y)+18,2,'#5b655e','#9d9579');for(let y=Math.min(shore.y,port.y)+5;y<Math.max(shore.y,port.y)+15;y+=12)line(port.x-26,y,port.x+26,y,'#383f3d',2);}
 else{rounded(Math.min(shore.x,port.x)-10,port.y-28,Math.abs(port.x-shore.x)+20,56,2,'#5b655e','#9d9579');for(let x=Math.min(shore.x,port.x);x<Math.max(shore.x,port.x);x+=12)line(x,port.y-26,x,port.y+26,'#383f3d',2);}
 [-34,34].forEach(d=>{const x=port.x+(vertical?d:0),y=port.y+(vertical?0:d);ctx.fillStyle='#222c2c';ctx.beginPath();ctx.arc(x,y,5,0,TAU);ctx.fill();light(x,y,40,'#e8ba6d32');ctx.fillStyle='#f2d69b';ctx.fillRect(x-2,y-3,4,5);});
 const tracked=M.stories(state).find(r=>r.id===state.track&&!r.done);ctx.setLineDash([4,7]);ctx.strokeStyle=tracked&&tracked.to===port.id?'#f6d58dcc':(ghost?'#efaa6b':port.color)+'88';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(port.x,port.y,63,0,TAU);ctx.stroke();ctx.setLineDash([]);
 ctx.font='600 15px system-ui';const tw=ctx.measureText(port.name).width,y=port.y+(vertical&&south?73:-102);rounded(port.x-tw/2-13,y,tw+26,29,6,'#0b252eea','#74847866');ctx.textAlign='center';ctx.fillStyle='#e9ddbd';ctx.fillText(port.name,port.x,y+20);
}
function mixColor(a,b,t){const channels=[1,3,5].map(i=>Math.round(parseInt(a.slice(i,i+2),16)*(1-t)+parseInt(b.slice(i,i+2),16)*t));return '#'+channels.map(n=>n.toString(16).padStart(2,'0')).join('');}
function outerBayArt(phase,weather){
 roof(2980,620,176,81,'#677d89');roof(3000,845,129,61,'#687a78');sign(3066,617,'TSUKIMI · NIGHT SKY WORKSHOP','#c5d8df');
 ctx.fillStyle='#102a3688';ctx.beginPath();ctx.ellipse(3130,752,63,54,0,0,TAU);ctx.fill();const dome=ctx.createRadialGradient(3090,722,3,3122,741,61);dome.addColorStop(0,'#bdc9c3');dome.addColorStop(1,'#6e8992');ctx.fillStyle=dome;ctx.beginPath();ctx.arc(3120,740,53,0,TAU);ctx.fill();ctx.strokeStyle='#a8b9b3';ctx.lineWidth=2;ctx.stroke();
 line(3120,689,3120,791,'#405a65',7);line(3119,699,3119,771,state.flags.observatorySupplied?'#e0d5aa':'#77928e',3);light(3120,740,63,state.flags.observatorySupplied?'#c8d6ad26':'#b3d0d112');
 for(let y=793;y<852;y+=13)rounded(3110,y,16,7,2,'#8b9e95');neighbour(3029,835,'#778fab',phase);neighbour(3173,881,'#9a968a',phase);ropeCoil(2979,917);lifeRing(3146,910);
 ctx.save();ctx.translate(3188,863);ctx.rotate(-.55);rounded(-22,-7,48,14,4,'#8facae','#c2c9b6');rounded(12,-8,8,16,2,'#324d5e');line(-6,8,-15,26,'#99aaa3',2);line(-6,8,8,26,'#99aaa3',2);ctx.restore();sign(3050,922,'FUEL · COCOA · SAFE HOMECOMINGS','#d4c9a3');
 for(let x=2810;x<3241;x+=23){rounded(x,1039,16,22,3,'#6b817a');line(x,1032,x+16,1032,'#bac7af66',2);}light(2815,1027,31,'#bcceb936');vessel(2860,969,0,'#809394','tug',.9);
 if(weather.clear>.05){ctx.save();ctx.globalAlpha=weather.clear;for(const [x,y]of[[2500,850],[2670,620],[2760,1250],[3220,1250],[1760,1260]]){line(x-5,y,x+5,y,'#d0dfb566',1);line(x,y-3,x,y+3,'#d0dfb544',1);}ctx.restore();}
}
function discoveryArt(){for(const d of W.discoveries){if(state.finds[d.id])continue;const p=W.discoveryPosition(state,d);light(p.x,p.y,32,'#d4c38b1a');if(d.kind==='boat')vessel(p.x,p.y,.3,'#8b9c7c','fishing',1);else if(d.kind==='crate'){crate(p.x-9,p.y-9,18);line(p.x-13,p.y+15,p.x+13,p.y+15,'#a6c4af33',1);}else{ctx.fillStyle='#dab479';ctx.beginPath();ctx.arc(p.x,p.y,6,0,TAU);ctx.fill();light(p.x,p.y,24,'#ecc59030');rounded(p.x-4,p.y-3,8,6,1,'#e7d9b8');}ctx.setLineDash([2,7]);ctx.strokeStyle='#d4c38b70';ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y,42,0,TAU);ctx.stroke();ctx.setLineDash([]);if(Math.hypot(p.x-state.ship.x,p.y-state.ship.y)<230)sign(p.x,p.y-55,P.encounter(state,d.id).title,'#ded4b7');}}
function livingWaterfront(phase){
 // Kitchen chimney and the warm counter stay readable even at the wide view.
 rounded(1210,125,18,24,2,'#3d4c4d','#b59d7e');for(let i=0;i<3;i++){ctx.fillStyle='#c4c7b322';ctx.beginPath();ctx.ellipse(1219+Math.sin(phase+i)*5,119-i*13,5+i*2,8,0,0,TAU);ctx.fill();}
 // Landing's clock tower, market shutters and a quieter terminus after the last train.
 rounded(441,124,22,57,3,'#9b9279','#c1c2a7');ctx.fillStyle='#ddd7b7';ctx.beginPath();ctx.arc(452,139,8,0,TAU);ctx.fill();line(452,139,452,133,'#36484b',1);line(452,139,457,141,'#36484b',1);
 for(let i=0;i<4;i++){const x=1170+i*127;if(state.clock>=1650){rounded(x,998,77,7,1,'#465b59');sign(x+38,1022,i===1?'Kettle still warm':'Morning prep','#c6baa1');}else neighbour(x+32,1016,['#627d83','#a58d6a','#79856d','#836f78'][i],phase);}
 if(state.clock<1540){rounded(120+(reduced?0:Math.min(155,(state.clock-1420)*1.3)),1205,112,15,3,'#a2aaa3','#d8c9a1');for(let i=0;i<5;i++){ctx.fillStyle='#edcf93';ctx.fillRect(128+(reduced?0:Math.min(155,(state.clock-1420)*1.3))+i*20,1208,11,6);}}else sign(265,1203,'Last train departed','#b6c2bd');
 // Yard gantry, unloading crew, canal banners, and observatory supper table.
 line(782,1480,782,1585,'#a3916b',5);line(782,1480,817,1450,'#a3916b',5);line(817,1450,845,1466,'#a3916b',3);crate(789,1601,20);crate(815,1614,15);neighbour(1020,1480,state.flags.pump?'#c0a777':'#738c80',phase);
 if(state.clock>=1560){neighbour(2410,427,'#778f98',phase);neighbour(2442,447,'#a6987e',phase);line(2417,434,2438,447,'#b9a581',2);}
 for(let i=0;i<3;i++){line(2010+i*37,1305,2010+i*37,1332,'#c4ae87',1);ctx.fillStyle=['#ae8575','#8ca594','#c4aa77'][i];ctx.fillRect(2011+i*37,1306,16,10);}
 if(state.flags.constellationDone){rounded(2980,870,52,25,4,'#a28566','#d0b18c');for(let i=0;i<3;i++){ctx.fillStyle='#efd7aa';ctx.beginPath();ctx.arc(2989+i*15,881,3,0,TAU);ctx.fill();}light(3006,880,55,'#edb87326');neighbour(2970,880,'#a28b78',phase);sign(3010,911,'A supper drawn from stars','#edce9a');}
}
function mapArt(now){const phase=reduced?0:now*.0002,weather=M.weather(state),dawn=M.dawn(state);ctx.fillStyle=ghost?'#253038':'#15343e';ctx.fillRect(0,0,W.width,W.height);const water=ctx.createLinearGradient(0,0,0,W.height);water.addColorStop(0,ghost?'#303b40':mixColor(mixColor('#193a44','#2d4e57',weather.clear),'#65878c',dawn));water.addColorStop(.5,ghost?'#253039':mixColor(mixColor('#14313b','#20404c',weather.clear),'#456e78',dawn));water.addColorStop(1,ghost?'#1f2531':mixColor('#102832','#365a6b',dawn));ctx.fillStyle=water;ctx.fillRect(0,0,W.width,W.height);
 for(let y=60;y<W.height;y+=43)for(let x=25;x<W.width;x+=79){const wave=Math.sin(x*.013+y*.02+phase)*4;line(x,y+wave,x+19+(x%3)*4,y+wave,'#79a4a013',1);}
 W.land.forEach((a,i)=>{rounded(a.x-9,a.y-9,a.w+18,a.h+18,18,'#a4b39e15');rounded(a.x,a.y,a.w,a.h,12,'#536861','#799081');rounded(a.x+8,a.y+8,Math.max(1,a.w-16),Math.max(1,a.h-16),7,'#394f4b');});
 // Landing: harbour sheds, small office and a fuel yard.
 roof(130,95,125,125,'#536a70');roof(280,112,176,100,'#5a6d69');roof(297,246,150,50,'#5c757c');rounded(125,242,115,50,5,'#6a7462');[145,185,225].forEach(x=>{ctx.fillStyle='#89958a';ctx.beginPath();ctx.arc(x,260,14,0,TAU);ctx.fill();line(x-10,260,x+10,260,'#526b66',2);});
 // Kurage: brick roofs, warm kitchen lane and a hanging neon jellyfish sign.
 roof(1190,110,235,155,'#886b5b');roof(1450,97,178,121,'#5c7277');roof(1470,248,127,62,'#617969');rounded(1230,278,185,31,3,'#a08067');for(let x=1238;x<1410;x+=20)line(x,280,x,307,'#dab88066',3);light(1320,335,90,'#dfac6026');ctx.fillStyle='#dbb984';ctx.beginPath();ctx.arc(1330,294,12,Math.PI,TAU);ctx.fill();for(let x=1320;x<1345;x+=6)line(x,294,x,308,'#d3b189',1);
 // Night Market: ordered rows of canvas roofs and a lantern promenade.
 for(let i=0;i<4;i++){roof(1160+i*127,938,104,65,['#9a7965','#557682','#7e8060','#667b6c'][i]);roof(1178+i*125,1034,90,50,'#576c69');light(1199+i*125,909,48,'#e7b96430');ctx.fillStyle='#ebc281';ctx.beginPath();ctx.arc(1199+i*125,909,5,0,TAU);ctx.fill();}
 line(1144,908,1660,908,'#aa946d',1);
 // Metro platform, yard machinery, cold chain and the canal's smaller rooftops.
 roof(124,1110,240,90,'#64747c');roof(144,1230,170,60,'#705f70');line(99,1209,448,1209,'#b29b81',3);line(99,1218,448,1218,'#8b9c96',2);
 for(let x=108;x<440;x+=27)line(x,1203,x,1224,'#555d5b',2);rounded(132,1092,185,9,2,'#bed0c5');light(224,1093,50,'#d2dcc526');
 roof(793,1460,190,105,'#5c756f');roof(1010,1510,160,106,'#6f7764');line(1078,1463,1078,1427,'#cdb37c',5);line(1040,1430,1170,1430,'#b1996b',6);line(1170,1430,1170,1462,'#b1996b',2);crate(1035,1465,23);crate(1140,1458,20);
 if(!state.flags.pump){rounded(824,1591,160,42,9,'#304a51','#99a999');rounded(852,1595,62,30,4,'#657d7d');}else rounded(824,1591,160,42,9,'#213b3d','#536b61');
 roof(2110,145,270,160,'#5c7885');roof(2130,338,164,88,'#6d8087');for(let x=2320;x<2480;x+=47){rounded(x,359,33,54,3,'#728187','#adbcaa');line(x+4,380,x+29,380,'#485b66',2);}for(let x=2100;x<2490;x+=46)crate(x,461,25);
 roof(1995,1210,141,86,'#8a7163');roof(1992,1365,145,91,'#6d8171');roof(2005,1515,132,96,'#807467');roof(2320,1215,139,87,'#596d75');roof(2315,1385,146,101,'#8b7b65');roof(2320,1540,138,81,'#747b64');
 line(2155,1350,2299,1350,'#c0a679',3);line(2155,1361,2299,1361,'#786b56',3);for(let x=2160;x<2300;x+=17)line(x,1350,x,1361,'#d0b995',2);
 if(state.flags.naoPreview){for(let y=1275;y<1540;y+=48){light(2160,y,32,'#e6b67735');ctx.fillStyle='#e0b673';ctx.beginPath();ctx.arc(2160,y,4,0,TAU);ctx.fill();}rounded(2025,1475,92,24,3,'#aa8667');}
 // Hoshimi's light and a little keeper's cottage.
 roof(1400,1472,90,67,'#6e7d70');tree(1606,1460,17);tree(1600,1570,19);ctx.save();ctx.translate(1564,1518);ctx.rotate(reduced?.6:phase*.75);ctx.fillStyle=state.flags.lampDelivered?'#efd6a82b':'#efd6a81b';ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(310,-37);ctx.lineTo(310,37);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle='#c8c3a5';ctx.beginPath();ctx.arc(1564,1518,22,0,TAU);ctx.fill();ctx.strokeStyle='#ab7d6d';ctx.lineWidth=6;ctx.stroke();light(1564,1518,37,'#f2d39566');
 // Small harbour details sit on land, leaving every water passage readable.
 [ [115,111],[492,106],[1660,275],[1510,290],[125,1283],[475,1120],[770,1641],[1180,1490],[1990,1230],[2469,1300] ].forEach(([x,y],i)=>tree(x,y,8+i%5));
 [[1214,320],[1438,294],[468,271],[1011,1446],[2040,1487]].forEach(([x,y])=>crate(x,y,16));
 // Central island stays a readable navigational obstacle, rather than a new port.
 for(let i=0;i<16;i++){const x=748+(i*47)%156,y=505+(i*61)%169;light(x,y,17,'#08252750');ctx.fillStyle=i%2?'#5e7966':'#6d8469';ctx.beginPath();ctx.arc(x,y,10+i%5,0,TAU);ctx.fill();}
 quayDetails(phase,weather);waterfrontDetails(phase);outerBayArt(phase,weather);livingWaterfront(phase);discoveryArt();if(ghost)halloweenArt();
 W.beacons.forEach((b,i)=>{ctx.fillStyle='#8e9c89';ctx.beginPath();ctx.arc(b.x,b.y,6,0,TAU);ctx.fill();light(b.x,b.y,25,'#a9d9c426');line(b.x,b.y-3,b.x,b.y+4,'#e0cb90',3);});
 if(!state.flags.salvage){const b=W.salvage;light(b.x,b.y,45,'#e0b86a33');ctx.fillStyle='#b79762';ctx.beginPath();ctx.arc(b.x,b.y,5,0,TAU);ctx.fill();for(let i=0;i<6;i++)line(b.x-22+i*8,b.y+11,b.x-18+i*8,b.y-7,'#7d9876',2);}
 if(!reduced&&weather.rain>.01){ctx.save();ctx.globalAlpha=weather.rain;for(let i=0;i<65;i++){const x=(i*127+now*.012)%W.width,y=(i*173+now*.038)%W.height;if(N.water(x,y))line(x,y,x-3,y+8,'#b8d1d024',1);}ctx.restore();}
 for(const p of W.ports){const y=p.y+45;for(let i=0;i<3;i++)line(p.x-12-i*5,y+i*12,p.x+13+i*5,y+i*12,p.color+'18',2);}
 for(let i=0;i<3;i++){const x=580+i*450,y=180+((reduced?1420:state.clock)*3+i*280)%900;if(N.water(x,y,25)){vessel(x,y,Math.PI/2,'#71877e',i===1?'tug':'fishing',.65);if(!reduced){line(x-5,y-16,x-9,y-30,'#9bc2b32a',1);line(x+5,y-16,x+9,y-30,'#9bc2b32a',1);}}}
 if(dawn>0){ctx.fillStyle='rgba(239,199,144,'+(dawn*.10)+')';ctx.fillRect(0,0,W.width,W.height);if(dawn>.15){sign(1330,316,'Sunrise rice & tea · 05:00','#ecd0a0');sign(1360,1086,'Breakfast buns & tea','#ecd0a0');}}W.ports.forEach(dockArt);
 if(path.length){ctx.setLineDash([5,9]);ctx.strokeStyle='#cfce9677';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(state.ship.x,state.ship.y);path.forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke();ctx.setLineDash([]);}
 ternArt(phase);
}
function draw(now){const rect=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2);if(rect.width!==width||rect.height!==height){width=rect.width;height=rect.height;canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);}ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,width,height);ctx.fillStyle='#15343e';ctx.fillRect(0,0,width,height);camera.scale=Math.max(.32,Math.min(1,width/1120,height/760))*(wideView?.72:1);
 const top=$('sailing-top').getBoundingClientRect(),bottom=$('sailing-bottom').getBoundingClientRect(),touch=$('touch-pad').getBoundingClientRect(),portRect=$('port').getBoundingClientRect();
 const topEdge=state.docked?(width>750?top.bottom-rect.top:0):top.bottom-rect.top;
 const bottomEdge=state.docked?height:Math.min(bottom.top-rect.top,width<=750?touch.top-rect.top:height);
 const rightEdge=state.docked&&width>750?portRect.left-rect.left:width;
 const area=window.VoyageCamera.viewport(width,height,topEdge,bottomEdge,rightEdge),near=M.nearby(state),find=M.nearDiscovery(state),focus=!state.docked?(near||find&&W.discoveryPosition(state,find)):null;
 camera=window.VoyageCamera.follow(camera,state.ship,focus,area,camera.scale,reduced);
 ctx.save();ctx.scale(camera.scale,camera.scale);ctx.translate(-camera.x,-camera.y);mapArt(now);ctx.restore();
 if(!state.docked&&area.bottom-area.top>200){const mw=width<750?105:145,mh=mw*W.height/W.width,x=width-mw-16,y=Math.max(30,area.top+10);rounded(x-5,y-5,mw+10,mh+10,7,'#0d2732dc','#6f8a7a66');ctx.save();ctx.translate(x,y);ctx.scale(mw/W.width,mh/W.height);W.land.forEach(a=>{ctx.fillStyle='#637d71';ctx.fillRect(a.x,a.y,a.w,a.h);});W.ports.forEach(p=>{ctx.fillStyle='#e6c68b';ctx.beginPath();ctx.arc(p.x,p.y,24,0,TAU);ctx.fill();});ctx.fillStyle='#f6efe1';ctx.beginPath();ctx.arc(state.ship.x,state.ship.y,23,0,TAU);ctx.fill();ctx.restore();}
 if(paused){ctx.fillStyle='#071b2855';ctx.fillRect(0,0,width,height);ctx.font='22px Georgia';ctx.fillStyle='#ecdfc1';ctx.textAlign='center';ctx.fillText('The harbour can wait.',width/2,height/2);}
}
function input(){let x=(keys.has('right')?1:0)-(keys.has('left')?1:0),y=(keys.has('down')?1:0)-(keys.has('up')?1:0);if(x||y){path=[];if(state.voyage&&state.voyage.to){M.destination(state,null);save();}return {x,y};}if(path.length){while(path.length&&Math.hypot(path[0].x-state.ship.x,path[0].y-state.ship.y)<18)path.shift();if(path.length)return {x:path[0].x-state.ship.x,y:path[0].y-state.ship.y};state.ship.speed=0;toast('Course complete. Press Dock near a quay.');}return {x:0,y:0};}
function frame(now){const dt=Math.min(.05,last?(now-last)/1000:0);last=now;if(!paused&&!panel.open&&!document.hidden&&!state.docked&&!state.ended){M.move(state,input(),dt);if(state.ended){save();finish();}if(state.fuel<=0&&state.ship.speed===0&&path.length){path=[];toast('Tank empty. The harbour tug can bring you back.');}}
 if(now-hudAt>200){if(ferryAudio&&radioContext.state==='running')ferryAudio.update(state,M.weather(state),!paused&&!panel.open&&!document.hidden);hud();hudAt=now;}if(now-saveAt>2000){save();saveAt=now;}draw(now);requestAnimationFrame(frame);}
const direction={w:'up',ArrowUp:'up',s:'down',ArrowDown:'down',a:'left',ArrowLeft:'left',d:'right',ArrowRight:'right'};
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select'))return;const key=e.key.length===1?e.key.toLowerCase():e.key;if(panel.open)return;if(direction[key]&&!state.docked){e.preventDefault();keys.add(direction[key]);return;}if(e.repeat)return;if(key==='e'&&!state.docked)dock();if(key==='j')journal();if(key==='r')radioMenu();if(key==='p'){paused=!paused;keys.clear();state.ship.speed=0;hud();}if(key==='Escape'){M.destination(state,null);path=[];keys.clear();state.ship.speed=0;}});
document.addEventListener('keyup',e=>{const key=e.key.length===1?e.key.toLowerCase():e.key;if(direction[key])keys.delete(direction[key]);});
window.addEventListener('blur',()=>{if(ferryAudio)ferryAudio.update(state,M.weather(state),false);keys.clear();state.ship.speed=0;save();});document.addEventListener('visibilitychange',()=>{if(ferryAudio)ferryAudio.update(state,M.weather(state),false);keys.clear();last=0;state.ship.speed=0;save();});window.addEventListener('pagehide',save);
$('zoom-button').onclick=()=>{wideView=!wideView;$('zoom-button').textContent='View · '+(wideView?'Wide':'Close');$('zoom-button').setAttribute('aria-pressed',String(wideView));};$('explore-button').onclick=discoveryPanel;$('moment-button').onclick=()=>{if(state.voyage){const portrait=el('img',undefined,'crossing-portrait');portrait.src=P.characters.nao.portrait;portrait.alt='Nao Mizuno';openPanel(state.voyage.line.speaker,[...(state.flags.naoAboard?[portrait]:[]),el('p',state.voyage.line.text),el('p','The crossing waits while you read.','muted')],'Back to the water');}};$('radio-button').onclick=radioMenu;$('journal-button').onclick=journal;$('pause-button').onclick=()=>{paused=!paused;keys.clear();state.ship.speed=0;hud();};$('dock-button').onclick=dock;$('depart-button').onclick=depart;$('stop-button').onclick=()=>{M.destination(state,null);keys.clear();path=[];state.ship.speed=0;toast('Holding position.');};$('find-button').onclick=()=>{if(act('salvage'))openPanel('A lantern in the reeds',[el('p','A little signal light bobs beside a sealed repair kit. You lift it aboard, check its owner’s release tag and log the salvage: 36 credits. Twelve minutes pass while you secure the case.'),el('p','A note in the lid reads: “For safe homecomings.” Some adventures are simply useful things finding another voyage.')]);};$('tow-button').onclick=()=>{if(!confirm('Return to Landing 3 with the tug? 20 minutes; up to 20 cr. Recovery is available even without credits.'))return;act('tow');};$('panel-close').onclick=()=>panel.close();panel.addEventListener('close',()=>{keys.clear();last=0;if(!state.docked&&!state.ended)canvas.focus();});
document.querySelectorAll('[data-tab]').forEach(n=>n.onclick=()=>{tab=n.dataset.tab;person=null;portContent();});$('course-select').addEventListener('change',()=>{const id=$('course-select').value;$('course-select').value='';if(id)destinationPreview(id);});
document.querySelectorAll('[data-steer]').forEach(n=>{const clear=()=>keys.delete(n.dataset.steer);n.addEventListener('pointerdown',e=>{if(state.docked||panel.open||paused)return;e.preventDefault();n.setPointerCapture(e.pointerId);keys.add(n.dataset.steer);});['pointerup','pointercancel','lostpointercapture'].forEach(event=>n.addEventListener(event,clear));});
canvas.addEventListener('pointerdown',e=>{if(state.docked||paused||panel.open||state.ended)return;const rect=canvas.getBoundingClientRect(),point={x:camera.x+(e.clientX-rect.left)/camera.scale,y:camera.y+(e.clientY-rect.top)/camera.scale};const port=W.ports.find(p=>Math.hypot(p.x-point.x,p.y-point.y)<70);path=N.route(state.ship,port||point);if(path.length){M.destination(state,port?port.id:null);save();}if(!path.length)toast('Choose open water. The Tern needs room around the shore.');canvas.focus();});
window.NeonVoyage={getState:()=>JSON.parse(JSON.stringify(state)),model:M,course,openJournal:journal};
radioView();renderPort();hud();save();requestAnimationFrame(frame);if(state.ended)finish();else if(!state.flags.welcome){state.flags.welcome=true;state.flags.expandedSeen=true;state.flags.quayPolishSeen=true;state.flags.arrivalSeen=true;save();help();}else if(!state.flags.arrivalSeen){state.flags.arrivalSeen=true;state.flags.quayPolishSeen=true;state.flags.expandedSeen=true;save();openPanel('Voyage 0.6 · A night worth bringing home',[el('p','Preview destinations before casting off. New encounters vary between voyages, and Nao’s crossing moments have a little passenger portrait.'),el('p','Gold sales show realised results before fuel. Breakfast opens at 05:00 as daylight reaches the water; the closing harbour wire remembers your stories.'),el('p',loadNotice||'Your existing voyage continues with its purse, upgrades and discoveries.')]);}else if(loadNotice)toast(loadNotice);
})();
