(function(){'use strict';const W=window.VoyageWorld,N=window.VoyageNavigation,P=window.VoyagePorts,M=window.VoyageModel,Gold=window.NeonMarket,KEY='neon-tides:voyage:v1';
const $=id=>document.getElementById(id),canvas=$('sea'),ctx=canvas.getContext('2d'),panel=$('panel');let state,storageOK=true,loadNotice='',tab='people',person=null,speech='',paused=false,path=[],keys=new Set(),last=0,saveAt=0,hudAt=0,toastTimer=0,camera={x:0,y:0,scale:1},reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
try{const raw=localStorage.getItem(KEY);if(raw){const saved=JSON.parse(raw);if(M.valid(saved))state=saved;else loadNotice='That voyage save could not be read. A fresh voyage is ready; Classic is untouched.';}}catch(e){loadNotice='Saving is unavailable or the previous voyage could not be read. You can still sail this session.';}
if(!state)state=M.create('lantern-'+Date.now().toString(36));M.hydrate(state);M.observe(state);
function el(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function button(text,fn,disabled,primary){const n=el('button',text,primary?'primary':'');n.type='button';n.disabled=!!disabled;n.addEventListener('click',fn);return n;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){if(storageOK){storageOK=false;toast('This voyage can’t autosave here. Keep this tab open to continue.');}}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4500);}
function formatClock(){return M.time(state.clock);}
function objective(){const rows=M.stories(state),active=rows.find(r=>r.id===state.track&&!r.done)||rows.find(r=>!r.done);return active?active.title+' · '+active.text:'Explore the Basin · New voyages, cargo and neighbours await. Journal lists the quays.';}
function hud(){const held=Gold.lots.total(state.gold);$('resources').textContent=formatClock()+' · '+Math.round(state.credits)+' cr · '+held.toFixed(0)+' g gold · Fuel '+state.fuel.toFixed(1)+'/6 · Cargo '+M.held(state)+'/'+M.capacity(state);$('objective').textContent=objective();const near=M.nearby(state);$('dock-button').disabled=!near||!!state.docked||state.ended;$('dock-button').textContent=near?'Dock · '+near.name:'Dock · Approach a quay';$('find-button').hidden=!!state.docked||state.flags.salvage||Math.hypot(state.ship.x-W.salvage.x,state.ship.y-W.salvage.y)>65;$('pause-button').textContent=paused?'Resume':'Pause';document.body.classList.toggle('docked',!!state.docked);$('port').hidden=!state.docked||state.ended;}
function quote(){return Gold.quote(P.economy,state.truth,state.seed,state.docked,state.clock,state.trades);}
function trade(kind,n){if(M.trade(state,kind,n)){save();portContent();hud();toast((kind==='buy'?'Bought ':'Sold ')+n+' g.');}else toast('Check your purse, gold and the dealer’s remaining allowance.');}
function act(id){if(!M.action(state,id)){toast('That action is not available now. Check the cost or delivery deadline.');return false;}path=[];save();hud();if(state.ended){finish();return true;}if(state.docked)renderPort();return true;}
function doFreight(id,deliver){if(M.freight(state,id,deliver)){save();hud();portContent();toast(deliver?'Cargo delivered. Payment recorded.':'Case aboard. Check the return fuel and deadline.');}else toast('Check the cargo space, purse, destination and deadline.');}
function showPerson(id,text){person=id;speech=text===undefined?M.chat(state,id):text;save();portContent();}
function portContent(){const body=$('port-content');body.replaceChildren();if(!state.docked)return;const port=W.ports.find(p=>p.id===state.docked);$('port-title').textContent=port.name;$('port-subtitle').textContent=port.subtitle;document.querySelectorAll('[data-tab]').forEach(n=>n.setAttribute('aria-pressed',n.dataset.tab===tab?'true':'false'));
if(person){const c=P.characters[person],head=el('div',undefined,'dialogue-head'),img=el('img');img.src=c.portrait;img.alt=c.name;head.append(img);const labels=el('div');labels.append(el('h2',c.name),el('p',c.role));head.append(labels);body.append(head,el('p','“'+speech+'”','speech'));const actions=el('div',undefined,'actions');actions.append(button('Keep chatting',()=>showPerson(person)));
 if(person==='mei'&&!state.flags.teaAccepted)actions.append(button('Collect Nao’s tea · Free · 5 min',()=>{if(act('accept-tea'))showPerson('mei','One sealed case for Nao, twenty-four credits when it arrives. Start the handover by 03:40. Fuel is yours to budget. Bring yourself back as carefully as the tea.');},state.clock+5>P.tea.deadline,true));
 if(person==='nao'&&state.flags.teaAccepted&&!state.flags.teaDelivered)actions.append(button('Deliver Mei’s tea · Receive 24 cr · 5 min',()=>{if(act('deliver-tea'))showPerson('nao','There it is! Mei’s seal, dry paper, everything safe. Here are your twenty-four credits. Stay for a bun if you have a little time.');},state.clock>P.tea.deadline,true));
 if(person==='rin'&&!state.flags.lampAccepted)actions.append(button('Collect Aki’s lighthouse kit · Free · 5 min',()=>{if(act('lamp-collect'))showPerson('rin','One kit for Aki on Hoshimi. Forty credits on delivery; start the five-minute handover by 05:00. Check your return fuel; the yard and Kisaragi have pumps.');},M.held(state)>=M.capacity(state)||state.clock+5>P.lamp.deadline,true));
 if(person==='rin'&&!state.flags.pump)actions.append(button('Help repair Second Helping · Free · 10 min',()=>{if(act('repair-pump')&&!state.ended)showPerson('rin','Hold the light. One cleaned valve, one tightened seal… there! Listen to that calm hum. She’ll carry the day crew home.');}));
 if(person==='aki'&&state.flags.lampAccepted&&!state.flags.lampDelivered)actions.append(button('Deliver lighthouse kit · Receive 40 cr · 5 min',()=>{if(act('lamp-deliver'))showPerson('aki','Seal intact. Forty credits, as promised. Your crossing has become part of the light that will guide the next ferry.');},state.clock>P.lamp.deadline,true));
 if(person==='nao'&&state.docked==='market'&&state.flags.teaDelivered&&!state.flags.naoInvited)actions.append(button('Invite Nao to Kisaragi’s preview supper · Free · 5 min',()=>{if(act('nao-invite')&&!state.ended)showPerson('nao','Hana promised one little table, not a whole new life. Let me prepare a sample. I’d like to make this voyage with you.');},false,true));
 if(['nao','hana'].includes(person)&&state.docked==='canal'&&state.flags.naoAboard&&!state.flags.naoPreview)actions.append(button('Join Nao’s preview supper · Free · 10 min',()=>{if(act('nao-preview')&&!state.ended)showPerson('nao','I put my recipe by the pot and nobody asked me to make the table bigger. I think that was my favourite part. Thank you for bringing me.');},false,true));
 if(person==='nao'&&state.docked==='market'&&state.flags.naoPreview&&state.flags.naoAboard)actions.append(button('Bring Nao back to her counter',()=>{if(act('nao-return'))showPerson('nao','Home again. The invitation is mine, and I can choose a little evening. I’ll keep that crossing for the next busy morning.');},false,true));
 const meal=P.meals[state.docked];if(meal&&meal.who===person)actions.append(button(meal.name+' · '+meal.price+' cr · '+meal.minutes+' min',()=>{const id=person;if(act('meal')&&!state.ended)showPerson(id,meal.text);},state.credits<meal.price));
 actions.append(button('Back to people',()=>{person=null;portContent();}));body.append(actions);return;}
if(tab==='people'){body.append(el('p',port.arrival,'muted'));M.people(state).forEach(id=>{const c=P.characters[id],n=button('',()=>showPerson(id));n.className='person';const img=el('img');img.src=c.portrait;img.alt='';const label=el('span');label.append(el('strong',c.name),el('small',c.role));n.append(img,label);body.append(n);});if(state.docked==='bar'&&!state.flags.teaAccepted)body.append(el('p','Mei has a small courier job. Talk to her to collect the case.','cargo-card'));if(state.docked==='market'&&state.flags.teaAccepted&&!state.flags.teaDelivered)body.append(el('p','Your tea case is aboard. Speak to Nao to complete the delivery.','cargo-card'));}
else if(tab==='market'){M.observe(state);const q=quote();body.append(el('h2',q.dealer.name),el('p','Observed '+formatClock()+'. Trading pauses the clock.','muted'));const grid=el('div',undefined,'quote-grid');[['You pay to buy',q.buy],['You receive selling',q.sell]].forEach(([label,value])=>{const box=el('div');box.append(el('small',label),el('strong',value+' cr/g'));grid.append(box);});body.append(grid);const controls=el('div',undefined,'trade-controls');[1,3].forEach(n=>{controls.append(button('Buy '+n+' g',()=>trade('buy',n),state.credits<n*q.buy||q.canBuy<n));controls.append(button('Sell '+n+' g',()=>trade('sell',n),Gold.lots.total(state.gold)<n||q.canSell<n));});body.append(controls,el('p','Remaining tray: '+q.canBuy+' g · Buyer allowance: '+(Number.isFinite(q.canSell)?q.canSell+' g':'open'),'muted'),el('p','Your gold: '+Gold.lots.total(state.gold)+' g · Average purchase '+Math.round(Gold.lots.average(state.gold)||0)+' cr/g. Fuel and the spread affect your margin.','muted'));}
else if(tab==='cargo'){
 body.append(el('h2','Small cargo · Clear promises'),el('p','Shared hold: '+M.held(state)+' / '+M.capacity(state)+' cases. Purchases and handovers take five minutes. Fuel costs extra.','muted'));
 let count=0;Object.entries(P.freight).forEach(([id,d])=>{const c=(state.cargo||{})[id];if(state.docked!==d.from&&state.docked!==d.to)return;count++;const card=el('div',undefined,'cargo-card');card.append(el('h3',d.title),el('p','Purchase '+d.cost+' cr · Promised payment '+d.payment+' cr · Gross margin '+(d.payment-d.cost)+' cr before fuel.'),el('p','Collect at '+W.ports.find(p=>p.id===d.from).name+' → '+W.ports.find(p=>p.id===d.to).name+' · Start handover by '+M.time(d.deadline)+'.','muted'));
 if(c&&!c.units)card.append(el('p','Delivered · '+c.revenue+' cr received.'));else if(c)card.append(el('p','Aboard · '+(state.clock>d.deadline?'Delivery window closed.':Math.floor(d.deadline-state.clock)+' minutes remaining.')));
 if(state.docked===d.from&&!c)card.append(button('Buy sealed case · '+d.cost+' cr · 5 min',()=>doFreight(id,false),state.credits<d.cost||M.held(state)>=M.capacity(state)||state.clock+5>d.deadline,true));
 if(state.docked===d.to&&c&&c.units)card.append(button('Deliver · Receive '+d.payment+' cr · 5 min',()=>doFreight(id,true),state.clock>d.deadline,true));body.append(card);});
 if(!count)body.append(el('p','No stock offer at this quay. Jun sells bowls in Kisaragi; Rin has pump seals at the yard. Courier work is offered through People.'));
}
else{body.append(el('h2','Keep the Tern ready'));if(['landing','yard','canal'].includes(state.docked)){body.append(el('p','Fill the tank to 6 · 30 cr · 10 minutes.'));body.append(button('Refuel',()=>act('fuel'),state.fuel>=5.99||state.credits<30,true));}else if(state.docked==='market'){body.append(el('p','Kenji’s engine tuning · 80 cr · 15 minutes. Sail 15% faster and use 20% less fuel per distance.'));body.append(button(state.flags.engine?'Engine tuned':'Tune the engine',()=>act('engine'),!!state.flags.engine||state.credits<80,true));body.append(el('p','Cargo racks · 65 cr · 10 minutes. Increase the shared hold from two cases to three.'));body.append(button(state.flags.hold?'Cargo racks fitted':'Fit cargo racks',()=>act('hold'),!!state.flags.hold||state.credits<65));}else body.append(el('p','Fuel is at Landing 3, Starling Yard and Kisaragi. Kenji handles upgrades at the Night Market.'));
 body.append(el('p','Finish at any port. Your report separates gold trading, cargo, courier work and salvage.','muted'),button('Finish this voyage',()=>{state.ended=true;save();finish();}));}}
function renderPort(){person=null;portContent();}
function depart(){if(!M.depart(state))return;paused=false;person=null;keys.clear();path=[];hud();save();canvas.focus();toast('Cast off. WASD or arrows steer; Set course assists.');}
function dock(){if(M.dock(state)){keys.clear();path=[];tab='people';renderPort();hud();save();$('depart-button').focus();}else toast('Sail inside a quay’s dotted mooring ring, then Dock.');}
function openPanel(title,nodes,closeLabel){keys.clear();state.ship.speed=0;const content=$('panel-content');content.replaceChildren(el('h2',title),...nodes);$('panel-close').textContent=closeLabel||'Close';if(!panel.open)panel.showModal();}
function journal(){const nodes=[el('p',objective())];
 const stories=el('div',undefined,'journal-card');stories.append(el('h3','Active stories & outcomes'));M.stories(state).forEach(row=>{const item=el('div',undefined,'story-row');item.append(el('strong',(row.done?'Completed · ':'')+row.title),el('p',row.text,'muted'));if(!row.done)item.append(button(state.track===row.id?'Tracking':'Track this story',()=>{state.track=row.id;save();hud();journal();}));stories.append(item);});if(!M.stories(state).length)stories.append(el('p','Mei has tea for Nao; Rin has lighthouse work. Visit the counters to begin.'));nodes.push(stories);
 const quays=el('div',undefined,'journal-card');quays.append(el('h3','Basin chart'));W.ports.forEach(p=>{quays.append(button(p.name+(state.visits[p.id]?' · Visited':' · New quay'),()=>{panel.close();course(p.id);},!!state.docked));});quays.append(el('p','Cast off before setting a course. Fuel pumps: Landing 3, Starling Yard, Kisaragi.','muted'));nodes.push(quays);const cargo=el('div',undefined,'journal-card');cargo.append(el('h3','Cargo & stories'),el('p',state.flags.teaDelivered?'Mei’s tea delivered · 24 cr received.':state.flags.teaAccepted?'One sealed tea case · Cost 0 cr · Nao pays 24 cr at Lantern Market · '+(state.clock>P.tea.deadline?'Delivery window closed.':Math.floor(P.tea.deadline-state.clock)+' minutes to start the five-minute handover.'):'Shared hold: '+M.held(state)+' / '+M.capacity(state)+' cases. Talk to Mei for a first delivery.'),el('p',state.flags.salvage?'Signal-light kit recovered · 36 cr salvage.':'A lantern has been reported in the western reeds. Approach slowly to investigate.'));nodes.push(cargo);const boards=el('div',undefined,'journal-card');boards.append(el('h3','Remembered gold boards'));Object.entries(state.quotes).forEach(([id,q])=>boards.append(el('p',W.ports.find(p=>p.id===id).name+' · '+M.time(q.at)+' · Buy '+q.buy+' / Sell '+q.sell+' cr/g')));boards.append(el('p','Remembered quotes can be old. Read the current scale before trading.','muted'));nodes.push(boards);const log=el('div',undefined,'journal-card');log.append(el('h3','Voyage log'));state.log.slice(0,12).forEach(line=>log.append(el('p',line,'muted')));nodes.push(log);openPanel('Captain’s journal',nodes);}
function help(){openPanel('Welcome aboard the Tern',[el('p','Voyage 0.2 opens eight quays across the Basin. Meet familiar neighbours, trade gold and cargo, help Rin keep the lighthouse turning, or take Nao to Kisaragi. Classic remains available separately.'),el('p','WASD or arrow keys steer. On a phone, hold the direction buttons. Click open water or choose Set course for assisted sailing. Steering manually cancels an assisted course.'),el('p','Approach the dotted ring around a port and press Dock or E. Visit People, Market, Cargo or Services. Time moves while sailing and during labelled activities; reading, conversations and menus pause it.'),el('p','Start by speaking to Mei. Take her tea to Nao at the Night Market. Fuel is sold at Landing 3, Starling Yard and Kisaragi. The harbour tug can recover a stranded ferry. J opens your journal; P pauses sailing.'),el('p',loadNotice||'Your voyage autosaves separately from Classic. The Journal has a Basin chart and tracked stories. This stage builds on your existing Voyage save.')],'Start exploring');}
function finish(){path=[];keys.clear();state.ship.speed=0;const sold=state.trades.filter(t=>t.kind==='sell').reduce((sum,t)=>sum+t.total-(t.basis||0),0);openPanel('A little light brought home',[el('p','The Tern rests. Thank you for making a little room for the harbour.'),el('p','Purse '+state.credits+' cr · Gold '+Gold.lots.total(state.gold)+' g · Realised gold result '+Math.round(sold)+' cr.'),el('p','Tea delivery: '+(state.flags.teaDelivered?'24 cr received':'not completed')+' · Salvage: '+(state.flags.salvage?'36 cr recovered':'not recovered')+'.'),el('p','Lighthouse courier: '+(state.flags.lampDelivered?'40 cr received':'not completed')+' · Stock cargo: '+Object.values(state.cargo||{}).reduce((n,c)=>n+c.revenue-c.cost,0)+' cr net before fuel.'),el('p','Nao’s preview supper: '+(state.flags.naoReturned?'shared, and Nao brought home':state.flags.naoPreview?'shared; Nao still aboard':'not yet shared')+'.'),button('Continue this voyage',()=>{state.ended=false;panel.close();renderPort();hud();save();},state.clock>=1800),el('p','Useful feedback: Was steering comfortable? Were the ports easy to find? Did People / Market / Cargo / Services feel clear?'),button('Start a fresh voyage',()=>{if(!confirm('Replace this Voyage save? Classic is unaffected.'))return;state=M.create('lantern-'+Date.now().toString(36));M.observe(state);paused=false;tab='people';panel.close();renderPort();hud();save();}),button('Return to game selection',()=>location.href='../index.html')]);}
function course(id){if(state.docked){toast('Cast off first, then set your course.');return;}if(state.ended||panel.open)return;const port=W.ports.find(p=>p.id===id);if(!port)return;path=N.route(state.ship,port);if(path.length)toast('Assisted course to '+port.name+'. Dock when you arrive; steer to take control.');else toast('No safe course from here. Try nearby open water.');}
// One coherent top-down map. Portraits live only in dock conversations.
let width=0,height=0;const TAU=Math.PI*2;
function rounded(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke();}}
function line(x1,y1,x2,y2,color,size){ctx.strokeStyle=color;ctx.lineWidth=size||1;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}
function light(x,y,r,color){const g=ctx.createRadialGradient(x,y,1,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill();}
function roof(x,y,w,h,color){rounded(x+7,y+9,w,h,3,'#06182088');rounded(x,y,w,h,4,color,'#778780');
 for(let yy=10;yy<h;yy+=12)line(x+3,y+yy,x+w-3,y+yy,'#1c333c22',1);
 for(let xx=10;xx<w;xx+=13)line(x+xx,y+3,x+xx,y+h-3,'#aec1b31f',1);
 line(x+w/2,y+1,x+w/2,y+h-1,'#d1c1a988',3);line(x,y+h,x+w,y+h,'#23383a',4);
 for(let i=12;i<w;i+=25){ctx.fillStyle='#ecc386';ctx.fillRect(x+i,y+h-2,9,4);light(x+i+4,y+h+5,22,'#e5b26c22');}
 if(w>100){rounded(x+14,y+14,21,28,2,'#374e58','#8a9c99');line(x+18,y+17,x+30,y+37,'#b9c7bc44',2);rounded(x+w-31,y+15,15,20,2,'#485551','#92a497');ctx.fillStyle='#203940';ctx.fillRect(x+w-28,y+19,9,10);}
}
function crate(x,y,w){rounded(x,y,w,w,2,'#94765a','#b9a47b');line(x+3,y+4,x+w-3,y+w-4,'#5e5545',2);line(x+3,y+w-4,x+w-3,y+4,'#5e5545',2);}
function tree(x,y,r){ctx.fillStyle='#0c282b77';ctx.beginPath();ctx.ellipse(x+4,y+5,r+2,r,0,0,TAU);ctx.fill();ctx.fillStyle='#667d64';ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill();ctx.fillStyle='#89a17b55';ctx.beginPath();ctx.arc(x-3,y-3,r*.58,0,TAU);ctx.fill();}
function dockArt(port){const shore=port.shore,vertical=shore.x===port.x,south=shore.y<port.y;
 if(vertical){rounded(port.x-28,Math.min(shore.y,port.y),56,Math.abs(port.y-shore.y)+18,2,'#5b655e','#9d9579');for(let y=Math.min(shore.y,port.y)+5;y<Math.max(shore.y,port.y)+15;y+=12)line(port.x-26,y,port.x+26,y,'#383f3d',2);}
 else{rounded(Math.min(shore.x,port.x)-10,port.y-28,Math.abs(port.x-shore.x)+20,56,2,'#5b655e','#9d9579');for(let x=Math.min(shore.x,port.x);x<Math.max(shore.x,port.x);x+=12)line(x,port.y-26,x,port.y+26,'#383f3d',2);}
 [-34,34].forEach(d=>{const x=port.x+(vertical?d:0),y=port.y+(vertical?0:d);ctx.fillStyle='#222c2c';ctx.beginPath();ctx.arc(x,y,5,0,TAU);ctx.fill();light(x,y,40,'#e8ba6d32');ctx.fillStyle='#f2d69b';ctx.fillRect(x-2,y-3,4,5);});
 const tracked=M.stories(state).find(r=>r.id===state.track&&!r.done);ctx.setLineDash([4,7]);ctx.strokeStyle=tracked&&tracked.to===port.id?'#f6d58dcc':port.color+'88';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(port.x,port.y,63,0,TAU);ctx.stroke();ctx.setLineDash([]);
 ctx.font='600 15px system-ui';const tw=ctx.measureText(port.name).width,y=port.y+(vertical&&south?73:-102);rounded(port.x-tw/2-13,y,tw+26,29,6,'#0b252eea','#74847866');ctx.textAlign='center';ctx.fillStyle='#e9ddbd';ctx.fillText(port.name,port.x,y+20);
}
function mapArt(now){const phase=reduced?0:now*.0002;ctx.fillStyle='#15343e';ctx.fillRect(0,0,W.width,W.height);const water=ctx.createLinearGradient(0,0,0,W.height);water.addColorStop(0,'#193a44');water.addColorStop(.5,'#14313b');water.addColorStop(1,'#102832');ctx.fillStyle=water;ctx.fillRect(0,0,W.width,W.height);
 for(let y=60;y<W.height;y+=43)for(let x=25;x<W.width;x+=79){const wave=Math.sin(x*.013+y*.02+phase)*4;line(x,y+wave,x+19+(x%3)*4,y+wave,'#79a4a013',1);}
 W.land.forEach((a,i)=>{rounded(a.x-9,a.y-9,a.w+18,a.h+18,18,'#a4b39e15');rounded(a.x,a.y,a.w,a.h,12,'#536861','#799081');rounded(a.x+8,a.y+8,Math.max(1,a.w-16),Math.max(1,a.h-16),7,'#394f4b');});
 // Landing: harbour sheds, small office and a fuel yard.
 roof(130,95,125,125,'#536a70');roof(280,112,176,100,'#5a6d69');roof(297,246,150,50,'#5c757c');rounded(125,242,115,50,5,'#6a7462');[145,185,225].forEach(x=>{ctx.fillStyle='#89958a';ctx.beginPath();ctx.arc(x,260,14,0,TAU);ctx.fill();line(x-10,260,x+10,260,'#526b66',2);});
 // Kurage: brick roofs, warm kitchen lane and a hanging neon jellyfish sign.
 roof(1190,110,235,155,'#886b5b');roof(1450,97,178,121,'#5c7277');roof(1470,248,127,62,'#617969');rounded(1230,278,185,31,3,'#a08067');for(let x=1238;x<1410;x+=20)line(x,280,x,307,'#dab88066',3);light(1320,335,90,'#dfac6026');ctx.fillStyle='#dbb984';ctx.beginPath();ctx.arc(1330,294,12,Math.PI,TAU);ctx.fill();for(let x=1320;x<1345;x+=6)line(x,294,x,308,'#d3b189',1);
 // Night Market: ordered rows of canvas roofs and a lantern promenade.
 for(let i=0;i<4;i++){roof(1160+i*127,938,104,65,['#9a7965','#557682','#7e8060','#667b6c'][i]);roof(1178+i*125,1034,90,50,'#576c69');light(1199+i*125,909,48,'#e7b96430');ctx.fillStyle='#ebc281';ctx.beginPath();ctx.arc(1199+i*125,909,5,0,TAU);ctx.fill();}
 line(1144,908,1660,908,'#aa946d',1);
 // Metro platform, yard machinery, cold chain and the canal's smaller rooftops.
 roof(124,1110,240,90,'#64747c');roof(144,1230,170,60,'#705f70');line(99,1209,448,1209,'#b29b81',3);line(99,1218,448,1218,'#8b9c96',2);
 for(let x=108;x<440;x+=27)line(x,1203,x,1224,'#555d5b',2);rounded(132,1092,185,9,2,'#bed0c5');light(224,1093,50,'#d2dcc526');
 roof(793,1460,190,105,'#5c756f');roof(1010,1510,160,106,'#6f7764');line(1078,1463,1078,1427,'#cdb37c',5);line(1040,1430,1170,1430,'#b1996b',6);line(1170,1430,1170,1462,'#b1996b',2);crate(1035,1465,23);crate(1140,1458,20);
 rounded(824,1591,160,42,9,'#304a51','#99a999');rounded(852,1595,62,30,4,'#657d7d');if(state.flags.pump)light(937,1608,23,'#b1e2a84d');
 roof(2110,145,270,160,'#5c7885');roof(2130,338,164,88,'#6d8087');for(let x=2320;x<2480;x+=47){rounded(x,359,33,54,3,'#728187','#adbcaa');line(x+4,380,x+29,380,'#485b66',2);}for(let x=2100;x<2490;x+=46)crate(x,461,25);
 roof(1995,1210,141,86,'#8a7163');roof(1992,1365,145,91,'#6d8171');roof(2005,1515,132,96,'#807467');roof(2320,1215,139,87,'#596d75');roof(2315,1385,146,101,'#8b7b65');roof(2320,1540,138,81,'#747b64');
 line(2155,1350,2299,1350,'#c0a679',3);line(2155,1361,2299,1361,'#786b56',3);for(let x=2160;x<2300;x+=17)line(x,1350,x,1361,'#d0b995',2);
 if(state.flags.naoPreview){for(let y=1275;y<1540;y+=48){light(2160,y,32,'#e6b67735');ctx.fillStyle='#e0b673';ctx.beginPath();ctx.arc(2160,y,4,0,TAU);ctx.fill();}rounded(2025,1475,92,24,3,'#aa8667');}
 // Hoshimi's light and a little keeper's cottage.
 roof(1400,1472,90,67,'#6e7d70');tree(1606,1460,17);tree(1600,1570,19);ctx.save();ctx.translate(1564,1518);ctx.rotate(reduced?.6:phase*.75);ctx.fillStyle=state.flags.lampDelivered?'#efd6a82b':'#efd6a81b';ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(310,-37);ctx.lineTo(310,37);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle='#c8c3a5';ctx.beginPath();ctx.arc(1564,1518,22,0,TAU);ctx.fill();ctx.strokeStyle='#ab7d6d';ctx.lineWidth=6;ctx.stroke();light(1564,1518,37,'#f2d39566');
 // Small harbour details sit on land, leaving every water passage readable.
 [ [115,111],[492,106],[1660,275],[1510,290],[125,1283],[475,1120],[770,1641],[1180,1490],[1990,1230],[2469,1300] ].forEach(([x,y],i)=>tree(x,y,8+i%5));
 [[1214,320],[1438,294],[468,271],[1011,1446],[2040,1487]].forEach(([x,y])=>crate(x,y,16));
 // Central island stays a readable navigational obstacle, rather than a new port.
 for(let i=0;i<16;i++){const x=748+(i*47)%156,y=505+(i*61)%169;light(x,y,17,'#08252750');ctx.fillStyle=i%2?'#5e7966':'#6d8469';ctx.beginPath();ctx.arc(x,y,10+i%5,0,TAU);ctx.fill();}
 W.beacons.forEach((b,i)=>{ctx.fillStyle='#8e9c89';ctx.beginPath();ctx.arc(b.x,b.y,6,0,TAU);ctx.fill();light(b.x,b.y,25,'#a9d9c426');line(b.x,b.y-3,b.x,b.y+4,'#e0cb90',3);});
 if(!state.flags.salvage){const b=W.salvage;light(b.x,b.y,45,'#e0b86a33');ctx.fillStyle='#b79762';ctx.beginPath();ctx.arc(b.x,b.y,5,0,TAU);ctx.fill();for(let i=0;i<6;i++)line(b.x-22+i*8,b.y+11,b.x-18+i*8,b.y-7,'#7d9876',2);}
 if(!reduced){for(let i=0;i<65;i++){const x=(i*127+now*.012)%W.width,y=(i*173+now*.038)%W.height;if(N.water(x,y))line(x,y,x-3,y+8,'#b8d1d010',1);}}
 for(const p of W.ports){const y=p.y+45;for(let i=0;i<3;i++)line(p.x-12-i*5,y+i*12,p.x+13+i*5,y+i*12,p.color+'18',2);}
 for(let i=0;i<3;i++){const x=580+i*450,y=180+(state.clock*3+i*280)%900;if(N.water(x,y,25)){ctx.save();ctx.translate(x,y);rounded(-5,-12,10,25,3,'#77867d','#a5b5a0');line(-5,16,-11,28,'#9bc2b32a',1);line(5,16,11,28,'#9bc2b32a',1);ctx.restore();}}
 W.ports.forEach(dockArt);
 if(path.length){ctx.setLineDash([5,9]);ctx.strokeStyle='#cfce9677';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(state.ship.x,state.ship.y);path.forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke();ctx.setLineDash([]);}
 const s=state.ship;ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.angle);if(s.speed>2&&!reduced){line(-24,-7,-46-s.speed*.15,-16,'#abcac43a',2);line(-24,7,-46-s.speed*.15,16,'#abcac43a',2);}ctx.fillStyle='#041a2488';ctx.beginPath();ctx.ellipse(2,3,27,13,0,0,TAU);ctx.fill();ctx.fillStyle='#c3b38c';ctx.beginPath();ctx.moveTo(29,0);ctx.quadraticCurveTo(13,-14,-23,-10);ctx.lineTo(-26,0);ctx.lineTo(-23,10);ctx.quadraticCurveTo(13,14,29,0);ctx.fill();rounded(-17,-8,30,16,3,'#46616a','#879c94');rounded(-4,-6,13,12,2,'#dfc18b');line(-11,-7,-11,7,'#a39c83',2);light(23,0,24,'#e7d6a02a');ctx.restore();
}
function draw(now){const rect=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2);if(rect.width!==width||rect.height!==height){width=rect.width;height=rect.height;canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);}ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,width,height);camera.scale=Math.max(.48,Math.min(1,width/1120,height/760));const viewW=width/camera.scale,viewH=height/camera.scale;
 const targetX=state.docked&&width>750?Math.max(0,state.ship.x-(width-480)/camera.scale*.5):Math.max(0,Math.min(W.width-viewW,state.ship.x-viewW*.5)),targetY=Math.max(0,Math.min(W.height-viewH,state.ship.y-viewH*.5));camera.x+=(targetX-camera.x)*(reduced?1:.08);camera.y+=(targetY-camera.y)*(reduced?1:.08);
 ctx.save();ctx.scale(camera.scale,camera.scale);ctx.translate(-camera.x,-camera.y);mapArt(now);ctx.restore();
 if(!state.docked){const mw=width<750?105:145,mh=mw*W.height/W.width,x=width-mw-16,y=width<750?130:30;rounded(x-5,y-5,mw+10,mh+10,7,'#0d2732dc','#6f8a7a66');ctx.save();ctx.translate(x,y);ctx.scale(mw/W.width,mh/W.height);W.land.forEach(a=>{ctx.fillStyle='#637d71';ctx.fillRect(a.x,a.y,a.w,a.h);});W.ports.forEach(p=>{ctx.fillStyle='#e6c68b';ctx.beginPath();ctx.arc(p.x,p.y,24,0,TAU);ctx.fill();});ctx.fillStyle='#f6efe1';ctx.beginPath();ctx.arc(state.ship.x,state.ship.y,23,0,TAU);ctx.fill();ctx.restore();}
 if(paused){ctx.fillStyle='#071b2855';ctx.fillRect(0,0,width,height);ctx.font='22px Georgia';ctx.fillStyle='#ecdfc1';ctx.textAlign='center';ctx.fillText('The harbour can wait.',width/2,height/2);}
}
function input(){let x=(keys.has('right')?1:0)-(keys.has('left')?1:0),y=(keys.has('down')?1:0)-(keys.has('up')?1:0);if(x||y){path=[];return {x,y};}if(path.length){while(path.length&&Math.hypot(path[0].x-state.ship.x,path[0].y-state.ship.y)<18)path.shift();if(path.length)return {x:path[0].x-state.ship.x,y:path[0].y-state.ship.y};state.ship.speed=0;toast('Course complete. Press Dock near a quay.');}return {x:0,y:0};}
function frame(now){const dt=Math.min(.05,last?(now-last)/1000:0);last=now;if(!paused&&!panel.open&&!document.hidden&&!state.docked&&!state.ended){M.move(state,input(),dt);if(state.ended){save();finish();}if(state.fuel<=0&&state.ship.speed===0&&path.length){path=[];toast('Tank empty. The harbour tug can bring you back.');}}
 if(now-hudAt>200){hud();hudAt=now;}if(now-saveAt>2000){save();saveAt=now;}draw(now);requestAnimationFrame(frame);}
const direction={w:'up',ArrowUp:'up',s:'down',ArrowDown:'down',a:'left',ArrowLeft:'left',d:'right',ArrowRight:'right'};
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select'))return;const key=e.key.length===1?e.key.toLowerCase():e.key;if(panel.open)return;if(direction[key]&&!state.docked){e.preventDefault();keys.add(direction[key]);return;}if(e.repeat)return;if(key==='e'&&!state.docked)dock();if(key==='j')journal();if(key==='p'){paused=!paused;keys.clear();state.ship.speed=0;hud();}if(key==='Escape'){path=[];keys.clear();state.ship.speed=0;}});
document.addEventListener('keyup',e=>{const key=e.key.length===1?e.key.toLowerCase():e.key;if(direction[key])keys.delete(direction[key]);});
window.addEventListener('blur',()=>{keys.clear();state.ship.speed=0;save();});document.addEventListener('visibilitychange',()=>{keys.clear();last=0;state.ship.speed=0;save();});window.addEventListener('pagehide',save);
$('journal-button').onclick=journal;$('pause-button').onclick=()=>{paused=!paused;keys.clear();state.ship.speed=0;hud();};$('dock-button').onclick=dock;$('depart-button').onclick=depart;$('stop-button').onclick=()=>{keys.clear();path=[];state.ship.speed=0;toast('Holding position.');};$('find-button').onclick=()=>{if(act('salvage'))openPanel('A lantern in the reeds',[el('p','A little signal light bobs beside a sealed repair kit. You lift it aboard, check its owner’s release tag and log the salvage: 36 credits. Twelve minutes pass while you secure the case.'),el('p','A note in the lid reads: “For safe homecomings.” Some adventures are simply useful things finding another voyage.')]);};$('tow-button').onclick=()=>{if(!confirm('Return to Landing 3 with the tug? 20 minutes; up to 20 cr. Recovery is available even without credits.'))return;act('tow');};$('panel-close').onclick=()=>panel.close();panel.addEventListener('close',()=>{keys.clear();last=0;if(!state.docked&&!state.ended)canvas.focus();});
document.querySelectorAll('[data-tab]').forEach(n=>n.onclick=()=>{tab=n.dataset.tab;person=null;portContent();});$('course-select').addEventListener('change',()=>{const id=$('course-select').value;$('course-select').value='';if(id)course(id);});
document.querySelectorAll('[data-steer]').forEach(n=>{const clear=()=>keys.delete(n.dataset.steer);n.addEventListener('pointerdown',e=>{if(state.docked||panel.open||paused)return;e.preventDefault();n.setPointerCapture(e.pointerId);keys.add(n.dataset.steer);});['pointerup','pointercancel','lostpointercapture'].forEach(event=>n.addEventListener(event,clear));});
canvas.addEventListener('pointerdown',e=>{if(state.docked||paused||panel.open||state.ended)return;const rect=canvas.getBoundingClientRect(),point={x:camera.x+(e.clientX-rect.left)/camera.scale,y:camera.y+(e.clientY-rect.top)/camera.scale};const port=W.ports.find(p=>Math.hypot(p.x-point.x,p.y-point.y)<70);path=N.route(state.ship,port||point);if(!path.length)toast('Choose open water. The Tern needs room around the shore.');canvas.focus();});
window.NeonVoyage={getState:()=>JSON.parse(JSON.stringify(state)),model:M,course,openJournal:journal};
renderPort();hud();save();requestAnimationFrame(frame);if(state.ended)finish();else if(!state.flags.welcome){state.flags.welcome=true;state.flags.expandedSeen=true;save();help();}else if(!state.flags.expandedSeen){state.flags.expandedSeen=true;save();openPanel('Voyage 0.2 · Beyond the harbour',[el('p','Five more quays are ready to explore. Visit Rin at Starling Yard for lighthouse work, or invite Nao to Kisaragi after delivering Mei’s tea.'),el('p','Cargo now has its own tab. Your Journal keeps several stories together, with a choice of which to track.'),el('p',loadNotice||'Your existing voyage continues with its purse, upgrades and discoveries.')]);}else if(loadNotice)toast(loadNotice);
})();
