import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url)),c=vm.createContext({window:{},console});
for(const file of ['trade.js','market.js','voyage/world-map.js','voyage/navigation.js','voyage/ports.js','voyage/model.js'])vm.runInContext(fs.readFileSync(root+file,'utf8'),c,{filename:file});
const {VoyageWorld:W,VoyageNavigation:N,VoyageModel:M,VoyagePorts:P,NeonMarket:G}=c.window;let count=0;const check=(v,msg)=>{assert.ok(v,msg);count++;},equal=(a,b,msg)=>{assert.equal(a,b,msg);count++;};
const shipAt=p=>({x:p.x,y:p.y,angle:0,speed:0});
for(const a of W.ports)for(const b of W.ports){check(N.water(a.x,a.y),'port mooring in navigable water');const route=N.route(a,b);check(route.length>0,a.id+'→'+b.id+' has safe course');let prior=a;for(const p of route){check(N.segment(prior,p),'route stays clear of shore');prior=p;}
 if(a===b)continue;const ship=shipAt(a);let waypoint=0;for(let i=0;i<8000&&waypoint<route.length;i++){const p=route[waypoint];if(Math.hypot(ship.x-p.x,ship.y-p.y)<18){waypoint++;continue;}N.step(ship,{x:p.x-ship.x,y:p.y-ship.y},.016,false);check(N.water(ship.x,ship.y),'ship never crosses land');}equal(waypoint,route.length,'steering can actually follow course '+a.id+'→'+b.id);}
check(!N.water(800,550),'central island collides');equal(N.route(W.ports[0],{x:800,y:550}).length,0,'assisted target on land rejected');
let s=M.create('frost-order');check(M.valid(s),'new state valid');M.observe(s);const before=JSON.stringify(s);M.chat(s,'mei');equal(s.clock,1420,'casual chat pauses clock');equal(s.credits,360,'casual chat free');const lines=Array.from({length:4},()=>M.chat(s,'mei'));equal(new Set(lines).size,4,'fresh casual lines');check(!M.action(s,'deliver-tea'),'cannot deliver before collection');check(M.action(s,'accept-tea'),'real tea collection');equal(s.clock,1425,'collection five minutes');equal(s.credits,360,'courier requires no purchase');check(!M.action(s,'accept-tea'),'cannot duplicate cargo');M.depart(s);
const destination=W.ports.find(p=>p.id==='market'),path=N.route(s.ship,destination);let i=0;for(let frame=0;frame<8000&&i<path.length;frame++){const p=path[i];if(Math.hypot(p.x-s.ship.x,p.y-s.ship.y)<18){i++;continue;}M.move(s,{x:p.x-s.ship.x,y:p.y-s.ship.y},.016);}check(M.dock(s),'actual sailed delivery docks');equal(s.docked,'market','correct destination reached');check(s.fuel<6&&s.clock>1425,'movement spends fuel and advances time');const purse=s.credits;check(M.action(s,'deliver-tea'),'delivered tea accepted');equal(s.credits,purse+24,'promised courier payment');check(!M.action(s,'deliver-tea'),'no duplicate payment');check(M.chat(s,'nao').includes('Mei’s tea'),'Nao acknowledges delivery');check(M.valid(JSON.parse(JSON.stringify(s))),'delivery survives save/reload');
const cash=s.credits;check(M.trade(s,'buy',1),'gold purchase');check(s.credits<cash,'purchase costs credits');const held=G.lots.total(s.gold);check(!M.trade(s,'buy',9999),'unaffordable trade rejected');equal(G.lots.total(s.gold),held,'rejected purchase unchanged');check(M.trade(s,'sell',1),'gold sale');check(!M.trade(s,'sell',999),'cannot sell gold not owned');const tradeTime=s.clock;M.trade(s,'buy',1);equal(s.clock,tradeTime,'trading pauses clock');check(M.action(s,'engine'),'engine upgrade');check(!M.action(s,'engine'),'upgrade cannot repeat');
let slow=M.create('fuel'),fast=M.create('fuel');M.depart(slow);M.depart(fast);fast.flags.engine=true;for(let j=0;j<100;j++){M.move(slow,{x:0,y:1},.016);M.move(fast,{x:0,y:1},.016);}check(fast.ship.y>slow.ship.y,'upgrade improves speed');check(fast.fuel>slow.fuel,'upgrade improves real fuel consumption');
let late=M.create('late');M.action(late,'accept-tea');late.docked='market';late.ship=shipAt(destination);late.clock=P.tea.deadline+1;check(!M.action(late,'deliver-tea'),'late delivery cannot claim fee');late.clock=P.tea.deadline;check(M.action(late,'deliver-tea'),'deadline boundary allowed');
let rescue=M.create('rescue');M.depart(rescue);rescue.fuel=0;rescue.credits=0;const position=JSON.stringify(rescue.ship);M.move(rescue,{x:1,y:0},.016);equal(JSON.stringify(rescue.ship),position,'empty fuel prevents sailing');check(M.action(rescue,'tow'),'recovery available penniless');equal(rescue.docked,'landing','tug recovers at fuel port');equal(rescue.credits,0,'recovery cannot make credits negative');check(M.valid(rescue),'recovered save valid');
let salvage=M.create('salvage');M.depart(salvage);salvage.ship=shipAt(W.salvage);check(M.action(salvage,'salvage'),'close-range exploration');check(!M.action(salvage,'salvage'),'salvage cannot farm credits');M.advance(salvage,999);check(salvage.ended,'dawn closes shift');equal(salvage.clock,1800,'clock bounded at dawn');check(!M.trade(salvage,'buy',1)&&!M.action(salvage,'tow'),'closed voyage cannot spend or earn');
check(!M.valid({...M.create('broken'),version:99}),'incompatible saves rejected');check(!M.valid({...M.create('broken'),fuel:-1}),'invalid fuel rejected');check(!M.valid({...M.create('broken'),ship:{x:800,y:550,angle:0,speed:0}}),'land-position save rejected');
check(fs.readFileSync(root+'index.html','utf8').includes('href="classic.html"'),'launcher exposes Classic');check(fs.readFileSync(root+'index.html','utf8').includes('href="voyage/index.html"'),'launcher exposes Voyage');check(fs.readFileSync(root+'voyage/voyage.js','utf8').includes("KEY='neon-tides:voyage:v1'"),'separate save namespace');

// Expanded voyage: old saves, shared hold, cargo payments and multi-stage stories.
const moor=(s,id)=>{s.docked=id;s.ship=shipAt(W.ports.find(p=>p.id===id));};
let old=M.create('old-save');delete old.cargo;delete old.visits;delete old.track;old.flags.teaDelivered=true;old.flags.teaAccepted=true;old.credits=384;check(M.valid(old),'0.1 optional-field save still valid');M.hydrate(old);equal(old.credits,384,'migration keeps purse');check(old.flags.teaDelivered&&Object.keys(old.cargo).length===0,'migration preserves completed story');
let cargo=M.create('cargo');moor(cargo,'canal');const initial=cargo.credits;check(!M.freight(cargo,'seals',false),'stock must be collected at source');check(M.freight(cargo,'bowls',false),'buy bowl case');equal(cargo.credits,initial-20,'purchase deducts real cost');check(!M.freight(cargo,'bowls',false),'cannot buy same case twice');moor(cargo,'yard');check(M.freight(cargo,'seals',false),'second case fits');equal(M.held(cargo),2,'shared hold counts both cargo cases');check(!M.action(cargo,'lamp-collect'),'full hold rejects courier case');moor(cargo,'market');check(M.action(cargo,'hold'),'fit cargo racks');equal(M.capacity(cargo),3,'hold upgrade adds actual slot');check(!M.action(cargo,'hold'),'hold cannot be charged twice');moor(cargo,'yard');check(M.action(cargo,'lamp-collect'),'courier fits upgraded shared hold');equal(M.held(cargo),3,'courier and stock share capacity');moor(cargo,'bar');const paid=cargo.credits;check(M.freight(cargo,'bowls',true),'bowl handover accepted');equal(cargo.credits,paid+36,'promised payment settles');check(!M.freight(cargo,'bowls',true),'no repeated cargo payment');equal(M.held(cargo),2,'handover releases slot');check(M.valid(JSON.parse(JSON.stringify(cargo))),'stock and upgraded hold save reload');
let lateCargo=M.create('late-stock');moor(lateCargo,'yard');M.freight(lateCargo,'seals',false);moor(lateCargo,'pier');lateCargo.clock=P.freight.seals.deadline+1;const lateCash=lateCargo.credits;check(!M.freight(lateCargo,'seals',true),'expired stock cannot collect payment');equal(lateCargo.credits,lateCash,'expired handover changes no credits');lateCargo.clock=P.freight.seals.deadline;check(M.freight(lateCargo,'seals',true),'stock deadline boundary settles');
let kit=M.create('lighthouse');moor(kit,'island');check(!M.action(kit,'lamp-deliver'),'no uncollected lighthouse payment');moor(kit,'yard');check(M.action(kit,'lamp-collect'),'Rin hands over kit');check(M.action(kit,'repair-pump'),'repair story completes');check(!M.action(kit,'repair-pump'),'repair is once only');moor(kit,'island');const kitCash=kit.credits;check(M.action(kit,'lamp-deliver'),'Aki accepts kit');equal(kit.credits,kitCash+40,'lighthouse payment correct');check(!M.action(kit,'lamp-deliver'),'no duplicate lighthouse fee');check(M.chat(kit,'aki').includes('steady sweep'),'Aki responds to completed quest');check(M.stories(kit).every(r=>r.done),'both outcomes retained');
let nao=M.create('festival');moor(nao,'market');check(!M.action(nao,'nao-invite'),'Nao trust follows tea delivery');nao.flags.teaAccepted=true;check(M.action(nao,'deliver-tea'),'tea prerequisite');const naoCash=nao.credits;check(M.action(nao,'nao-invite'),'Nao joins');moor(nao,'canal');check(M.people(nao).includes('nao'),'Nao appears at destination as companion');check(!M.action(nao,'nao-return'),'cannot return without supper');check(M.action(nao,'nao-preview'),'preview with Hana');check(!M.action(nao,'nao-preview'),'preview cannot repeat');equal(M.stories(nao).find(r=>r.id==='nao').to,'market','next story step points home');moor(nao,'market');check(M.action(nao,'nao-return'),'bring Nao home');check(!nao.flags.naoAboard&&nao.flags.naoReturned,'companion disembarks');equal(nao.credits,naoCash,'social story invents no money');check(M.stories(nao).find(r=>r.id==='nao').done,'journal preserves festival outcome');
for(const id of ['landing','yard','canal']){let fuel=M.create('pump');moor(fuel,id);fuel.fuel=1;check(M.action(fuel,'fuel'),'pump available at '+id);equal(fuel.fuel,6,'tank filled at '+id);}
for(const p of W.ports){let q=M.create('quotes');moor(q,p.id);M.observe(q);check(Number.isFinite(q.quotes[p.id].buy),'each quay has readable board');for(const id of M.people(q)){check(M.chat(q,id),'every character has dialogue');check(fs.existsSync(root+P.characters[id].portrait.replace(/^\.\.\//,'')),'portrait asset exists for '+id);}}
let corrupt=M.create('hold-overflow');corrupt.flags.teaAccepted=true;corrupt.flags.lampAccepted=true;corrupt.cargo.bowls={cost:20,revenue:0,units:1};check(!M.valid(corrupt),'save cannot overflow shared hold');
// Refinement stage: timed orders, cost previews, expired cargo and crossing voices.
let timed=M.create('timed-order');moor(timed,'metro');check(!M.freight(timed,'regulators',false),'timed stock is not released early');const waitCash=timed.credits;check(M.waitFreight(timed,'regulators'),'labelled wait reaches release');equal(timed.clock,1490,'wait uses actual clock cost');equal(timed.credits,waitCash,'wait does not charge hidden fee');check(!M.waitFreight(timed,'regulators'),'cannot repeat release wait');check(M.freight(timed,'regulators',false),'released regulators can be bought');equal(timed.credits,waitCash-48,'regulator purchase cost correct');const plain=M.estimate(timed,P.freight.regulators);check(plain.fuel>0&&plain.minutes>0,'route preview includes fuel and time');timed.flags.engine=true;const tuned=M.estimate(timed,P.freight.regulators);check(tuned.fuel<plain.fuel&&tuned.minutes<=plain.minutes,'preview reflects engine upgrade');moor(timed,'market');check(M.freight(timed,'regulators',true),'Kenji settles regulators');equal(timed.credits,waitCash+30,'gross regulator margin before fuel');check(M.chat(timed,'kenji').includes('arrived safe'),'buyer acknowledges delivery');check(M.valid(timed),'timed stock state validates');
let cold=M.create('cold-chain');moor(cold,'pier');check(!M.freight(cold,'starter',false),'cold room opens at two');check(M.waitFreight(cold,'starter'),'cold room wait');check(M.freight(cold,'starter',false),'jasmine starter released');moor(cold,'canal');cold.clock=P.freight.starter.deadline;check(M.freight(cold,'starter',true),'jasmine handover at boundary');equal(cold.credits,382,'jasmine purchase and payment correct');check(!M.freight(cold,'starter',true),'jasmine payment cannot repeat');
let expired=M.create('expired');moor(expired,'yard');M.freight(expired,'seals',false);expired.clock=1731;moor(expired,'metro');const lost=expired.credits;check(M.release(expired,'seals'),'expired case can unload at another quay');equal(expired.credits,lost,'unloading invents no refund');equal(M.held(expired),0,'unloading frees cargo slot');check(!M.release(expired,'seals'),'cannot unload twice');check(M.valid(JSON.parse(JSON.stringify(expired))),'released cargo persists');check(M.stories(expired).find(r=>r.id==='cargo-seals').text.includes('without payment'),'journal describes failed delivery honestly');
let voices=M.create('voices'),heard=[];const voiceClock=voices.clock;for(let i=0;i<4;i++){moor(voices,'bar');M.depart(voices);heard.push(voices.voyage.line.text);}equal(new Set(heard).size,4,'repeat departures have fresh voices');equal(voices.clock,voiceClock,'crossing text costs no time');voices.flags.naoAboard=true;moor(voices,'market');M.depart(voices);equal(voices.voyage.line.speaker,'Nao','passenger takes priority over generic radio');M.move(voices,{x:0,y:-1},.016);check(voices.voyage.distance>0,'crossing card appears after actual travel');check(M.valid(JSON.parse(JSON.stringify(voices))),'crossing voice survives reload');check(!M.valid({...voices,voyage:{...voices.voyage,distance:-1}}),'corrupt crossing rejected');
let older=M.create('pre-voices');delete older.passages;delete older.voyage;check(M.valid(older),'0.2 save remains compatible');M.hydrate(older);equal(older.voyage,null,'old save gets safe empty crossing');
// Outer bay: deterministic atmosphere, discoveries, planning and telescope story.
const weather=M.weather(M.create('cloud-test'));equal(JSON.stringify(weather),JSON.stringify(M.weather(M.create('cloud-test'))),'weather deterministic for same seed and clock');
let air=M.create('air');const weatherNames=new Set();for(let clock=1420;clock<=1790;clock++){air.clock=clock;const w=M.weather(air);weatherNames.add(w.name);check(Math.abs(w.clear+w.rain+w.mist-1)<1e-9,'weather weights stay normalized');check([w.clear,w.rain,w.mist].every(x=>x>=0&&x<=1),'weather blend remains bounded');}equal(weatherNames.size,3,'all three weather types occur');
for(const d of W.discoveries){const test=M.create('finding-'+d.id);M.depart(test);test.ship=shipAt(W.discoveryPosition(test,d));check(M.nearDiscovery(test)?.id===d.id,'discovery detected in range');const choice=P.discoveryText[d.id].choices[0],cash=test.credits,fuel=test.fuel,clock=test.clock;check(M.discover(test,d.id,choice.id),'discovery choice resolves');equal(test.credits,cash+choice.payment,'discovery fee exact');equal(test.fuel,fuel-(choice.fuel||0),'discovery fuel exact');equal(test.clock,clock+choice.minutes,'discovery time exact');check(!M.discover(test,d.id,choice.id),'discovery reward cannot repeat');check(M.valid(JSON.parse(JSON.stringify(test))),'discovery persists safely');check(M.stories(test).some(r=>r.id==='find-'+d.id&&r.done),'discovery outcome retained');}
let stranded=M.create('no-transfer');M.depart(stranded);stranded.ship=shipAt(W.discoveryPosition(stranded,W.discoveries.find(d=>d.id==='boat')));stranded.fuel=.1;check(!M.discover(stranded,'boat','help'),'cannot transfer unavailable fuel');check(M.discover(stranded,'boat','radio'),'tug alternative available without fuel');
let far=M.create('too-far');M.depart(far);check(!M.discover(far,'letter','read'),'cannot discover from another location');far.finds={drift:'hack'};check(!M.valid(far),'unknown discovery outcome rejected');
let trip=M.create('outer-trip');moor(trip,'market');check(!M.action(trip,'sky-watch'),'no sky watch at wrong quay');check(M.waitFreight(trip,'lenses'),'kit release wait');const quotePlan=M.plan(trip,'lenses'),planCash=trip.credits,planClock=trip.clock;check(quotePlan.onTime&&quotePlan.fuel>0&&quotePlan.returnFuel>0,'planner covers delivery and return');equal(trip.credits,planCash,'comparison cannot spend credits');equal(trip.clock,planClock,'comparison cannot advance clock');check(M.freight(trip,'lenses',false),'observatory kit purchased');check(M.collected(trip).some(r=>r.id==='cargo-lenses'&&r.cost===54&&r.payment===100),'planner lists collected kit and payment');check(M.plan(trip,'lenses').held,'held case skips collection');M.depart(trip);check(M.destination(trip,'observatory'),'destination recorded');check(trip.voyage.line.speaker.includes('Mio'),'outer-bay greeting selected');
const outer=W.ports.find(p=>p.id==='observatory'),outerRoute=N.route(trip.ship,outer);let outerIndex=0;for(let frame=0;frame<12000&&outerIndex<outerRoute.length;frame++){const p=outerRoute[outerIndex];if(Math.hypot(p.x-trip.ship.x,p.y-trip.ship.y)<18){outerIndex++;continue;}M.move(trip,{x:p.x-trip.ship.x,y:p.y-trip.ship.y},.016);}equal(outerIndex,outerRoute.length,'actual kit voyage reaches outer bay');check(M.dock(trip),'dock outer-bay voyage');check(!M.action(trip,'sky-watch'),'uncalibrated telescope unavailable');const outerCash=trip.credits;check(M.freight(trip,'lenses',true),'Mio accepts real delivered kit');equal(trip.credits,outerCash+100,'kit payment exact');check(trip.flags.observatorySupplied,'observatory changes after delivery');check(!M.freight(trip,'lenses',true),'no repeat observatory fee');check(M.action(trip,'sky-watch'),'telescope visit opens after calibration');check(!M.action(trip,'sky-watch'),'sky story once only');check(M.action(trip,'fuel'),'outer-bay return pump works');check(M.valid(trip),'outer-bay save remains valid');
let latePlan=M.create('late-plan');latePlan.clock=1730;check(!M.plan(latePlan,'lenses').onTime,'planner warns about missed deadline');
let deadlineCargo=M.create('sorted-hold');M.action(deadlineCargo,'accept-tea');moor(deadlineCargo,'yard');M.action(deadlineCargo,'lamp-collect');check(M.collected(deadlineCargo)[0].deadline<M.collected(deadlineCargo)[1].deadline,'held cargo sorts by deadline');
let companion=M.create('nao-context');companion.flags.naoAboard=true;M.depart(companion);M.destination(companion,'observatory');check(companion.voyage.line.text.includes('outer bay'),'Nao comments on chosen destination');M.destination(companion,'canal');check(companion.voyage.line.text.includes('small table'),'Nao changes line for canal');moor(companion,'observatory');const dialogueClock=companion.clock,dialogueCash=companion.credits;const companionLines=Array.from({length:4},()=>M.chat(companion,'nao'));equal(new Set(companionLines).size,4,'Nao has fresh destination and weather replies');equal(companion.clock,dialogueClock,'Nao dialogue free in time');equal(companion.credits,dialogueCash,'Nao dialogue free in credits');
let beforeBay=M.create('before-bay');delete beforeBay.finds;check(M.valid(beforeBay),'pre-update save compatible');M.hydrate(beforeBay);equal(Object.keys(beforeBay.finds).length,0,'migration adds empty discovery record');
const outingClock=nao.clock,outingCash=nao.credits;check(M.action(nao,'nao-outing'),'completed festival allows another Nao voyage');equal(nao.clock,outingClock+5,'new outing preparation labelled time');equal(nao.credits,outingCash,'new outing is free');check(!M.action(nao,'nao-outing'),'cannot invite companion twice');check(M.stories(nao).find(r=>r.id==='nao').done,'previous festival outcome retained while travelling again');moor(nao,'observatory');nao.flags.skySeen=true;check(M.action(nao,'share-sky'),'return visit can share earlier sky watch');check(!M.action(nao,'share-sky'),'same shared sky outcome cannot repeat');moor(nao,'market');check(M.action(nao,'nao-return'),'return from optional outing');check(M.stories(nao).find(r=>r.id==='nao-outing').done,'additional outing outcome recorded');
let gentle=M.create('different-weather-a'),storm=M.create('different-weather-b');M.depart(gentle);M.depart(storm);for(let i=0;i<30;i++){M.move(gentle,{x:0,y:1},.016);M.move(storm,{x:0,y:1},.016);}equal(gentle.fuel,storm.fuel,'weather does not penalize fuel');equal(gentle.ship.y,storm.ship.y,'weather does not penalize sailing');

let supper=M.create('constellation-test');const initialCash=supper.credits;
check(!M.action(supper,'constellation-start'),'supper requires shared sky memory');supper.flags.naoSkySeen=true;supper.flags.naoReturned=true;supper.flags.naoPreview=true;supper.flags.naoInvited=true;moor(supper,'market');check(M.action(supper,'constellation-start'),'Nao offers constellation supper after shared sky');check(!M.action(supper,'constellation-start'),'supper cannot start twice');check(!M.action(supper,'constellation-supper'),'ingredients and location required');equal(M.stories(supper).find(r=>r.id==='constellation').to,'canal','first step names tea destination');moor(supper,'canal');check(M.action(supper,'constellation-tea'),'tea purchased at Jun');check(!M.action(supper,'constellation-tea'),'tea cannot be charged twice');equal(M.held(supper),0,'recipe basket uses no freight slot');equal(M.stories(supper).find(r=>r.id==='constellation').to,'bar','second step points to Mei');moor(supper,'bar');check(M.action(supper,'constellation-ginger'),'ginger purchased at Mei');equal(supper.credits,initialCash-10,'ingredients cost exactly ten');equal(M.stories(supper).find(r=>r.id==='constellation').to,'market','collect companion next');moor(supper,'market');check(M.action(supper,'nao-outing'),'invite after festival for supper');moor(supper,'observatory');const supperAt=supper.clock;check(M.action(supper,'constellation-supper'),'supper celebrated with Nao and Mio');equal(supper.clock,supperAt+12,'celebration labelled twelve minutes');check(!M.action(supper,'constellation-supper'),'celebration cannot replay');check(M.stories(supper).find(r=>r.id==='constellation').done,'quest completes in journal');check(P.board(supper).some(p=>p.title.includes('very big sky')),'board reflects supper outcome');check(M.chat(supper,'mio').includes('Warm cups'),'Mio has completion reaction');check(M.valid(supper),'new quest save valid');
let gossip=M.create('trading-notes');const gossipBefore=JSON.stringify(gossip);check(P.board(gossip).length>4,'board populated');equal(JSON.stringify(gossip),gossipBefore,'board generation is read-only');check(!M.hear(gossip,'crews'),'future post cannot be heard early');check(M.hear(gossip,'recycled'),'posted signal heard');equal(gossip.clock,1420,'reading pauses time');gossip.clock+=20;M.hear(gossip,'recycled');equal(M.rumourRows(gossip)[0].heard,1420,'repeat reading preserves original hearing time');equal(M.rumourRows(gossip)[0].age,20,'age follows clock');check(M.valid(gossip),'rumour save valid');const legacy=JSON.parse(JSON.stringify(gossip));delete legacy.rumours;check(M.valid(legacy),'older save without rumours valid');M.hydrate(legacy);equal(Object.keys(legacy.rumours).length,0,'legacy gets empty notebook');legacy.rumours=7;check(!M.valid(legacy),'non-object rumour rejected');legacy.rumours={unknown:1420};check(!M.valid(legacy),'unknown rumour rejected');
let captain=M.create('nav-preview');M.depart(captain);const navBefore=JSON.stringify(captain),nav=M.routePreview(captain,'observatory');check(nav.fuel>0&&nav.minutes>0,'navigation estimates actual safe route');equal(nav.arrival,captain.clock+nav.minutes,'ETA matches sailing estimate');equal(JSON.stringify(captain),navBefore,'preview does not change save');M.destination(captain,'observatory');M.destination(captain,null);equal(captain.voyage.to,null,'cancel removes destination');captain.fuel=.01;check(!M.routePreview(captain,'observatory').enough,'navigation warns when fuel too low');
console.log(`Passed ${count} sailing, routing, trading, story and migration checks.`);
