import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url)),c=vm.createContext({window:{},console});
for(const file of ['trade.js','market.js','voyage/world-map.js','voyage/navigation.js','voyage/ports.js','voyage/model.js'])vm.runInContext(fs.readFileSync(root+file,'utf8'),c,{filename:file});
const {VoyageWorld:W,VoyageNavigation:N,VoyageModel:M,VoyagePorts:P,NeonMarket:G}=c.window;let count=0;const check=(v,msg)=>{assert.ok(v,msg);count++;},equal=(a,b,msg)=>{assert.equal(a,b,msg);count++;};
const shipAt=p=>({x:p.x,y:p.y,angle:0,speed:0});
for(const a of W.ports)for(const b of W.ports){check(N.water(a.x,a.y),'port mooring in navigable water');const route=N.route(a,b);check(route.length>0,a.id+'→'+b.id+' has safe course');let prior=a;for(const p of route){check(N.segment(prior,p),'route stays clear of shore');prior=p;}
 if(a===b)continue;const ship=shipAt(a);let waypoint=0;for(let i=0;i<8000&&waypoint<route.length;i++){const p=route[waypoint];if(Math.hypot(ship.x-p.x,ship.y-p.y)<18){waypoint++;continue;}N.step(ship,{x:p.x-ship.x,y:p.y-ship.y},.016,false);check(N.water(ship.x,ship.y),'ship never crosses land');}equal(waypoint,route.length,'steering can actually follow course '+a.id+'→'+b.id);}
check(!N.water(800,550),'central island collides');equal(N.route(W.ports[0],{x:800,y:550}).length,0,'assisted target on land rejected');
let s=M.create('frost-order');check(M.valid(s),'new state valid');M.observe(s);const before=JSON.stringify(s);M.chat(s,'mei');equal(s.clock,1420,'casual chat pauses clock');equal(s.credits,360,'casual chat free');const lines=Array.from({length:4},()=>M.chat(s,'mei'));equal(new Set(lines).size,4,'fresh casual lines');check(!M.action(s,'deliver-tea'),'cannot deliver before collection');check(M.action(s,'accept-tea'),'real tea collection');equal(s.clock,1425,'collection five minutes');equal(s.credits,360,'courier requires no purchase');check(!M.action(s,'accept-tea'),'cannot duplicate cargo');M.depart(s);
const destination=W.ports.find(p=>p.id==='market'),path=N.route(s.ship,destination);let i=0;for(let frame=0;frame<8000&&i<path.length;frame++){const p=path[i];if(Math.hypot(p.x-s.ship.x,p.y-s.ship.y)<18){i++;continue;}M.move(s,{x:p.x-s.ship.x,y:p.y-s.ship.y},.016);}check(M.dock(s),'actual sailed delivery docks');equal(s.docked,'market','correct destination reached');check(s.fuel<6&&s.clock>1425,'movement spends fuel and advances time');const purse=s.credits;check(M.action(s,'deliver-tea'),'delivered tea accepted');equal(s.credits,purse+24,'promised courier payment');check(!M.action(s,'deliver-tea'),'no duplicate payment');check(M.chat(s,'nao').includes('Mei’s tea'),'Nao acknowledges delivery');check(M.valid(JSON.parse(JSON.stringify(s))),'delivery survives save/reload');
const cash=s.credits;check(M.trade(s,'buy',1),'gold purchase');check(s.credits<cash,'purchase costs credits');const held=G.lots.total(s.gold);check(!M.trade(s,'buy',9999),'unaffordable trade rejected');equal(G.lots.total(s.gold),held,'rejected purchase unchanged');check(M.trade(s,'sell',1),'gold sale');check(!M.trade(s,'sell',999),'cannot sell gold not owned');const tradeTime=s.clock;M.trade(s,'buy',1);equal(s.clock,tradeTime,'trading pauses clock');check(M.action(s,'engine'),'engine upgrade');check(!M.action(s,'engine'),'upgrade cannot repeat');
let slow=M.create('fuel'),fast=M.create('fuel');M.depart(slow);M.depart(fast);fast.flags.engine=true;for(let j=0;j<100;j++){M.move(slow,{x:0,y:1},.016);M.move(fast,{x:0,y:1},.016);}check(fast.ship.y>slow.ship.y,'upgrade improves speed');check(fast.fuel>slow.fuel,'upgrade improves real fuel consumption');
let late=M.create('late');M.action(late,'accept-tea');late.docked='market';late.ship=shipAt(destination);late.clock=P.tea.deadline+1;check(!M.action(late,'deliver-tea'),'late delivery cannot claim fee');late.clock=P.tea.deadline;check(M.action(late,'deliver-tea'),'deadline boundary allowed');
let rescue=M.create('rescue');M.depart(rescue);rescue.fuel=0;rescue.credits=0;const position=JSON.stringify(rescue.ship);M.move(rescue,{x:1,y:0},.016);equal(JSON.stringify(rescue.ship),position,'empty fuel prevents sailing');check(M.action(rescue,'tow'),'recovery available penniless');equal(rescue.docked,'landing','tug recovers at fuel port');equal(rescue.credits,0,'recovery cannot make credits negative');check(M.valid(rescue),'recovered save valid');
let salvage=M.create('salvage');M.depart(salvage);salvage.ship=shipAt(W.salvage);check(M.action(salvage,'salvage'),'close-range exploration');check(!M.action(salvage,'salvage'),'salvage cannot farm credits');M.advance(salvage,999);check(salvage.ended,'dawn closes shift');equal(salvage.clock,1800,'clock bounded at dawn');check(!M.trade(salvage,'buy',1)&&!M.action(salvage,'tow'),'closed voyage cannot spend or earn');
check(!M.valid({...M.create('broken'),version:99}),'incompatible saves rejected');check(!M.valid({...M.create('broken'),fuel:-1}),'invalid fuel rejected');check(!M.valid({...M.create('broken'),ship:{x:800,y:550,angle:0,speed:0}}),'land-position save rejected');
check(fs.readFileSync(root+'index.html','utf8').includes('href="classic.html"'),'launcher exposes Classic');check(fs.readFileSync(root+'index.html','utf8').includes('href="voyage/index.html"'),'launcher exposes Voyage');check(fs.readFileSync(root+'voyage/voyage.js','utf8').includes("KEY='neon-tides:voyage:v1'"),'separate save namespace');
console.log(`Passed ${count} sailing, routing, trading, story and save checks.`);
